"""Compact revision text in Turkish, German and Italian."""

CLEAN_PAGES = {
    'Hidden margins. Optional routes.': ('Gizli kenarlar. Yan yollar.', 'Versteckte Ränder. Nebenwege.', 'Margini nascosti. Percorsi facoltativi.'),
    'Enter / click: choose': ('Enter / tıkla: seç', 'Enter / Klick: wählen', 'Enter / clic: scegli'),
    'PAD-A: choose': ('PAD-A: seç', 'PAD-A: wählen', 'PAD-A: scegli'),
    'PAD-A / PAD-B   Back': ('PAD-A / PAD-B   Geri', 'PAD-A / PAD-B   Zurück', 'PAD-A / PAD-B   Indietro'),
    'Learned techniques survive every redraw.': ('Öğrendiğin teknikler yeniden çizilince de kalır.', 'Gelernte Techniken bleiben beim Neuzeichnen.', 'Le tecniche apprese restano quando vieni ridisegnato.'),
    'MUSIC CREDITS': ('MÜZİK KÜNYESİ', 'MUSIKNACHWEISE', 'CREDITI MUSICALI'),
    'Music credits': ('Müzik künyesi', 'Musiknachweise', 'Crediti musicali'),
    'Source': ('Kaynak', 'Quelle', 'Fonte'),
    'ESC / BACK': ('ESC / GERİ', 'ESC / ZURÜCK', 'ESC / INDIETRO'),
    'The recordings selected for the original first three pages.': ('İlk üç sayfa için seçilen kayıtlar.', 'Aufnahmen für die ersten drei Seiten.', 'Registrazioni scelte per le prime tre pagine.'),
    'Recording titles retain their original spelling.': ('Kayıt adları özgün yazımıyla gösterilir.', 'Aufnahmetitel behalten ihre Originalschreibweise.', 'I titoli delle registrazioni mantengono la grafia originale.'),
    'E / trace the blue mark': ('E / mavi izi çiz', 'E / blaue Marke nachzeichnen', 'E / traccia il segno blu'),
    '+1 HEART': ('+1 KALP', '+1 HERZ', '+1 CUORE'),
    'Route drawn. +1 heart.': ('Rota çizildi. +1 kalp.', 'Weg gezeichnet. +1 Herz.', 'Percorso tracciato. +1 cuore.'),
    'Route drawn.': ('Rota çizildi.', 'Weg gezeichnet.', 'Percorso tracciato.'),
    'JUMP THE GUST': ('RÜZGÂRIN ÜSTÜNDEN ZIPLA', 'SPRING ÜBER DIE BÖE', 'SALTA LA RAFFICA'),
    'LEAVE THE TAIL MARK': ('KUYRUK İZİNDEN ÇIK', 'VERLASS DIE SCHWEIFMARKE', 'LASCIA IL SEGNO DELLA CODA'),
    'DIVE — STEP ASIDE': ('DALIŞ — YANA KAÇ', 'STURZFLUG — TRITT ZUR SEITE', 'PICCHIATA — SPOSTATI DI LATO'),
    'LOOSE STRING — HIT': ('İP GEVŞEDİ — VUR', 'LOSE SCHNUR — SCHLAG ZU', 'FILO ALLENTATO — COLPISCI'),
    'A / D or Left / Right: move.': ('A / D ya da ← / →: hareket et.', 'A / D oder ← / →: bewegen.', 'A / D o ← / →: muoviti.'),
    'Space / W / Up: jump. Release for a short jump. Pick up the tool.': ('Space / W / ↑: zıpla. Kısa zıplama için bırak. Silahı al.', 'Leertaste / W / ↑: springen. Kurz drücken für kurzen Sprung. Nimm das Werkzeug.', 'Spazio / W / ↑: salta. Rilascia per un salto breve. Prendi l\'arma.'),
    'F / J or left click: break four targets.': ('F / J ya da sol tık: dört hedefi kır.', 'F / J oder Linksklick: vier Ziele zerstören.', 'F / J o clic sinistro: rompi quattro bersagli.'),
    'Shift / K or right click: dash out of three red warnings.': ('Shift / K ya da sağ tık: üç kırmızı uyarıdan atılmayla çık.', 'Shift / K oder Rechtsklick: drei roten Warnungen ausweichen.', 'Shift / K o clic destro: scatta fuori da tre avvisi rossi.'),
    'E: ask the Artist for stairs, then read the rune seal.': ('E: Ressamdan merdiven iste, sonra rün mührünü oku.', 'E: Treppe zeichnen lassen, dann das Runensiegel lesen.', 'E: chiedi una scala, poi leggi il sigillo della runa.'),
    'Good dodge.': ('Güzel kaçış.', 'Gut ausgewichen.', 'Bella schivata.'),
    'Dash after the red warning appears.': ('Kırmızı uyarı belirince atıl.', 'Weiche nach Erscheinen der roten Warnung aus.', 'Scatta quando appare l\'avviso rosso.'),
    'E / draw the stairs': ('E / merdiveni çiz', 'E / Treppe zeichnen', 'E / disegna la scala'),
    'E / read the rune seal': ('E / rün mührünü oku', 'E / Runensiegel lesen', 'E / leggi il sigillo della runa'),
    'Sketch runes grant permanent techniques. Find them on optional routes.': ('Eskiz rünleri kalıcı teknikler verir. Yan yollarda bulabilirsin.', 'Skizzenrunen lehren bleibende Techniken. Suche sie auf Nebenwegen.', 'Le rune insegnano tecniche permanenti. Cercale nei percorsi facoltativi.'),
    'FOUR TARGETS': ('DÖRT HEDEF', 'VIER ZIELE', 'QUATTRO BERSAGLI'),
    'THREE RED WARNINGS': ('ÜÇ KIRMIZI UYARI', 'DREI ROTE WARNUNGEN', 'TRE AVVISI ROSSI'),
    "THE ARTIST'S STAIRS": ('RESSAMIN MERDİVENİ', 'DIE TREPPE DES ZEICHNERS', 'LA SCALA DEL DISEGNATORE'),
}
