"""Turkish authored dialogue and marginalia; English source strings stay canonical.

Only text shown to players belongs here. Gameplay IDs, flags and save keys
continue to use the original identifiers in their owning modules.
"""
from __future__ import annotations


TR_CONTENT = {
    # Achievement headings and conditions fit the two-column sketchbook.
    "A SAFE FIRST DRAFT": "GÜVENLİ İLK TASLAK",
    "Cross out the opening practice drawing.": "İlk alıştırma çizimini yok et.",
    "I CAN HEAR YOU": "SENİ DUYABİLİYORUM",
    "Reply to the Artist's margin note.": "Ressamın kenar notuna cevap ver.",
    "A SMALL CONVERSATION": "KÜÇÜK BİR SOHBET",
    "Reply to the Artist five times.": "Ressama beş kez cevap ver.",
    "A LINE OF YOUR OWN": "KENDİ ÇİZGİN",
    "Solve a physical page puzzle.": "Sayfadaki bir bulmacayı çöz.",
    "REWRITE THE ROUTE": "ROTAYI YENİDEN ÇİZ",
    "Solve all three page route puzzles.": "Üç sayfa rotası bulmacasını çöz.",
    "FIELD NOTES": "SAHA NOTLARI",
    "Defeat twelve different enemy kinds.": "On iki farklı düşman türünü yen.",
    "UNFAMILIAR INK": "YABANCI MÜREKKEP",
    "Defeat a Fold Duelist, Margin Sniper and Split Lantern.": "Kat Düellocusu, Kenar Nişancısı ve Çatlak Feneri yen.",
    "EVERY LOST LINE": "TÜM KAYIP ÇİZGİLER",
    "Collect all twelve Lost Sketches.": "Tüm Kayıp Eskizleri topla.",
    "Collect every Lost Sketch and secret rune.": "Tüm Kayıp Eskizleri ve gizli rünleri topla.",
    "SIX SIGNATURES": "ALTI İMZA",
    "Defeat all six named bosses.": "Altı ana düşmanı da yen.",
    "POST OFFICE": "POSTANE",
    "Perfectly return ten incoming shots.": "On gelen atışı kusursuz geri yansıt.",
    "MARGIN EXPLORER": "KENAR KAŞİFİ",
    "Clear twenty encounters.": "Yirmi çatışmayı tamamla.",
    "FIRST CROSS-OUT": "İLK ÇİZİK",
    "Defeat the first hostile doodle.": "İlk düşman karalamasını yen.",
    "BRAVEMAN": "CESUR ADAM",
    "Reach a page turn while avoiding more than attacking.": "Saldırıdan çok kaçınarak bir sayfayı bitir.",
    "THE AGGRO MAN": "SALDIRGAN ADAM",
    "Attack 90 times, mostly with the Pencil Blade.": "Ağırlıkla Kalem Bıçağıyla 90 kez saldır.",
    "NO RED MARKS": "KIRMIZI İZ YOK",
    "Finish a page without taking damage.": "Bir sayfayı hasar almadan bitir.",
    "BACK-PAGE READER": "ARKA SAYFA OKURU",
    "Clip three Lost Sketches into the back pages.": "Deftere üç Kayıp Eskiz ekle.",
    "TEMPORARY TOOLBOX": "GEÇİCİ SİLAH ÇANTASI",
    "Attack with every ordinary page weapon.": "Her sıradan sayfa silahıyla saldır.",
    "QUICK REVISION": "HIZLI DÜZELTME",
    "Clear a named boss in under 45 seconds.": "Bir ana düşmanı 45 saniyeden önce yen.",
    "TURN ONE OVER": "İLK SAYFAYI ÇEVİR",
    "Finish the samurai page.": "Samuray sayfasını bitir.",
    "THREE BAD DRAFTS": "ÜÇ KÖTÜ TASLAK",
    "Finish the first three pages.": "İlk üç sayfayı bitir.",
    "KING ARTHUR": "KRAL ARTHUR",
    "Pull the Artist's impossible sword from the page.": "Ressamın imkansız kılıcını sayfadan çıkar.",
    "FINAL PROOF": "SON PROVA",
    "Defeat the Final Editor's chosen revision.": "Son Editörün seçtiği düzeltmeyi yen.",
    "FIVE NAMES CROSSED OUT": "BEŞ İSİM SİLİNDİ",
    "Defeat the five original named bosses.": "İlk beş ana düşmanı yen.",
    "THE PAGE REMAINS OPEN": "SAYFA AÇIK KALIYOR",
    "Reach the blank page.": "Boş sayfaya ulaş.",
    "FIVE PAGES LATER": "BEŞ SAYFA SONRA",
    "Finish all five pages.": "Beş sayfanın hepsini bitir.",
    "CUT THAT OUT": "KES ŞUNU",
    "Defeat the Head of Redaction.": "Sansür Müdürünü yen.",
    "MIRROR": "AYNA",
    "Face the proof made from your clean play.": "Temiz oyunundan doğan provayla yüzleş.",
    "RETURN TO SENDER": "GÖNDERENE İADE",
    "Return three shots with a perfectly timed dash.": "Üç atışı tam zamanında atılarak geri yansıt.",

    # Optional Artist conversations retain the two voices and concrete advice.
    "Throw this chalk over cover. Its little cloud buys space.": "Tebeşiri siperin üstünden at. Bulutu sana yer açar.",
    "One straight carbon line can pass through a crowd. Then reload.": "Düz karbon çizgisi kalabalığı deler. Sonra doldur.",
    "The fold comes back. Catch it for a faster next throw.": "Katlama geri döner. Yakalarsan sonraki atış hızlanır.",
    "I made that pencil too heavy. Wind up before you swing.": "Kalemi fazla ağır çizmişim. Vurmadan önce hazırlan.",
    "This ink travels fast. Leave yourself time to reload.": "Bu mürekkep hızlı uçar. Doldurmaya zaman ayır.",
    "A broad marker stroke works best when you stand close.": "Geniş keçeli çizgisi yakından daha iyi işler.",
    "The eraser removes incoming marks as well as enemies.": "Silgi, düşmanlarla birlikte gelen atışları da siler.",
    "Bank that shot off a line. Straight ahead is not the only way.": "Atışı bir çizgiden sektir. Tek yol dümdüz gitmek değil.",
    "I may have overdrawn the sword. Its reach is the point.": "Kılıcı abartmış olabilirim. Mesele erişim mesafesi.",
    "I left that edge too faint. I have redrawn the landing.": "O kenarı silik bırakmışım. Basamağı yeniden çizdim.",
    "I see it now. Leave the next line visible, please.": "Şimdi görüyorum. Sonraki çizgi belirgin olsun lütfen.",
    "That sketch came apart. I kept your place.": "Eskiz dağıldı. Yerini sakladım.",
    "Draw me back crooked if you must. I am still here.": "Gerekirse eğri çiz. Hâlâ buradayım.",
    "That tool began as a margin doodle. Try how it moves.": "O silah bir kenar karalamasıydı. Nasıl işlediğini dene.",
    "I will. Keep drawing different answers.": "Denerim. Farklı cevaplar çizmeye devam et.",
    "Back to a close line. Its timing matters more than its ink.": "Yine yakın dövüş. Zamanlaması mürekkebinden önemli.",
    "That pencil is slow. Start the swing before they close in.": "O kalem yavaş. Düşman yaklaşmadan vuruşa başla.",
    "A wider mark. Make room before you draw the next one.": "Daha geniş bir iz. Sonrakini çizmeden yer aç.",
    "Different tool, different rhythm. Show me what this one can do.": "Başka silah, başka ritim. Bunun ne yaptığını göster.",
    "Then watch the space it leaves behind.": "O zaman ardında açtığı boşluğa bak.",
    "You changed that fight without my hand on the page.": "Ben sayfaya dokunmadan o savaşı değiştirdin.",
    "I had to. You gave me room to move.": "Mecburdum. Bana hareket edecek yer verdin.",
    "You put that step where my first line failed.": "İlk çizgimin yetmediği yere basamağı sen koydun.",
    "Then leave space for my next answer.": "O zaman bir sonraki cevabıma yer bırak.",
    "You tore the poster exactly where I left the paper weak.": "Posteri tam zayıf bıraktığım yerden yırttın.",
    "You drew the seam. I chose when to hit it.": "Dikişi sen çizdin. Ne zaman vuracağıma ben karar verdim.",
    "I drew the star. You carried it farther than I planned.": "Yıldızı ben çizdim. Sen planladığımdan uzağa götürdün.",
    "The next connection can be ours.": "Sonraki bağlantıyı birlikte yapabiliriz.",
    "You found an answer I did not draw in the margin.": "Kenara çizmediğim bir cevap buldun.",
    "Leave the next one unfinished. I want to try.": "Sonrakini yarım bırak. Ben de denemek istiyorum.",
    "You asked me to change the page. That changes my plan too.": "Sayfayı değiştirmemi istedin. Planım da değişti.",
    "Good. Let me choose where the line goes next.": "Güzel. Sonraki çizginin yerini ben seçeyim.",
    "I drew you a new foothold. The next move is yours.": "Sana yeni bir basamak çizdim. Sonraki hamle senin.",
    "I see it. Do not erase it yet.": "Gördüm. Daha silme.",
    "I rubbed one out. You still have to cross this page.": "Birini sildim. Sayfayı yine sen aşmalısın.",
    "I know. Thanks for the breath.": "Biliyorum. Soluklanma fırsatı için sağ ol.",
    "That mark was mine to warn you about. Watch its red outline.": "O izi haber vermeliydim. Kırmızı çizgisine bak.",
    "I saw it late. I will move before it lands.": "Geç gördüm. Bir dahakine isabet etmeden kaçarım.",
    "Oh. You can hear me? Try moving. I will keep drawing.": "Aa, beni duyuyor musun? Hareket et. Çizmeye devam ederim.",
    "A small nod. That counts. The red circle is yours to cross out.": "Ufak bir baş selamı yeter. Kırmızı daireyi sen sil.",
    "I drew you a hat. The gun needs time to reload.": "Sana bir şapka çizdim. Silahın dolması zaman alır.",
    "Six shots. Make a little space before the seventh.": "Altı atış. Yedinciden önce biraz yer aç.",
    "The stars were meant to stay still. Sorry.": "Yıldızlar yerinde duracaktı. Kusura bakma.",
    "Bank the pulse off a line. You can reach around a shield.": "Darbeyi çizgiden sektir. Kalkanın arkasına ulaşabilirsin.",
    "Keep your head down. This page has very good aim.": "Başını eğ. Bu sayfanın nişanı çok iyi.",
    "When the long red line stops moving, leave it behind.": "Uzun kırmızı çizgi durduğunda çizgiden çık.",
    "You have changed how I draw. One more page?": "Çizimimi değiştirdin. Bir sayfa daha mı?",
    "All right. I will leave the last word to you.": "Peki. Son sözü sana bırakacağım.",
    "Three cuts, then breathe. Dash past the red warning.": "Üç vuruş, sonra soluklan. Kırmızı uyarıyı atılmayla aş.",
    "The blue marks show a boss opening. Spend them carefully.": "Mavi izler ana düşmanın açığını gösterir. Fırsatı iyi kullan.",
    "PAD-Y: nod back": "PAD-Y: başınla cevap ver",
    "E: nod back": "E: başınla cevap ver",
    "Out, then back. The fold remembers your hand.": "Git ve dön. Katlama elini hatırlıyor.",
    "F / J  send it, then watch it return": "F / J  gönder, sonra dönüşünü izle",

    # Notebook schoolwork: numerical working and mathematical notation remain.
    "GEOMETRY / 04": "GEOMETRİ / 04",
    "draw the diagram first!": "önce şekli çiz!",
    "CIRCLES": "ÇEMBERLER",
    "circumference = 2πr": "çevre = 2πr",
    "area = πr²": "alan = πr²",
    "bring my compass back :)": "pergelimi geri getir :)",
    "TRIANGLES": "ÜÇGENLER",
    "CIRCULAR MOTION": "DAİRESEL HAREKET",
    "one turn = 2π radians": "bir tur = 2π radyan",
    "why is there a sword here?": "burada niye kılıç var?",
    "INK PRESSURE": "MÜREKKEP BASINCI",
    "force / area = pressure": "kuvvet / alan = basınç",
    "a narrow tip cuts deeper": "ince uç daha derin keser",
    "do not press through the page": "sayfayı delene kadar bastırma",
    "MOON GATE SKETCH": "AY KAPISI ESKİZİ",
    "arc length = rθ": "yay uzunluğu = rθ",
    "watch the end of the blade": "kılıcın ucuna bak",
    "there is a gap under the swing": "vuruşun altında boşluk var",
    "PHYSICS / MOTION": "FİZİK / HAREKET",
    "remember the units!": "birimleri unutma!",
    "PROJECTILES": "ATIŞ HAREKETİ",
    "ignore air resistance...": "hava direncini yok say...",
    "FRICTION": "SÜRTÜNME",
    "N = mg  (level ground)": "N = mg  (düz zemin)",
    "keep coffee off the notebook": "deftere kahve dökme",
    "THE TRAIN PROBLEM": "TREN PROBLEMİ",
    "distance = speed × time": "yol = hız × zaman",
    "the train is not drawn yet": "tren daha çizilmedi",
    "BOUNTY POSTERS": "ARANIYOR AFİŞLERİ",
    "three copies / one original": "üç kopya / bir asıl",
    "ink dries from the outside": "mürekkep dıştan kurur",
    "circle the wet signature": "ıslak imzayı daireye al",
    "RAILWAY TIMETABLE": "TREN TARİFESİ",
    "arrival - departure = delay": "varış - kalkış = gecikme",
    "23:07 - 22:40 = 27 min": "23:07 - 22:40 = 27 dk",
    "jump before the second whistle": "ikinci düdükten önce zıpla",
    "PHYSICS / GRAVITY": "FİZİK / YERÇEKİMİ",
    "double r  →  one quarter F": "r iki katı  →  F dörtte biri",
    "space was not empty after all": "uzay da boş değilmiş",
    "ORBITAL NOTES": "YÖRÜNGE NOTLARI",
    "the satellite needs batteries": "uyduya pil gerekiyor",
    "VECTORS": "VEKTÖRLER",
    "write the direction too!": "yönü de yaz!",
    "FREE FALL": "SERBEST DÜŞME",
    "Earth: g ≈ 9.8 m/s²": "Dünya: g ≈ 9.8 m/s²",
    "SATELLITE POWER": "UYDUNUN GÜCÜ",
    "the panels face the light": "paneller ışığa bakar",
    "the left one is folded wrong": "soldaki yanlış katlanmış",
    "REENTRY ERROR": "DÖNÜŞ HATASI",
    "heat ∝ speed²": "ısı ∝ hız²",
    "the suit is too large": "elbise fazla büyük",
    "erase the pressure seal again?": "basınç mührünü yine silelim mi?",
    "OPTICS / REFLECTION": "OPTİK / YANSIMA",
    "incident angle = reflected angle": "gelme açısı = yansıma açısı",
    "the mirror sees everything": "ayna her şeyi görür",
    "BINARY NUMBERS": "İKİLİ SAYILAR",
    "13 (decimal) = 1101 (binary)": "13 (onluk) = 1101 (ikilik)",
    "is this a secret message?": "bu gizli bir mesaj mı?",
    "COORDINATES": "KOORDİNATLAR",
    "connect the dots": "noktaları birleştir",
    "LENSES": "MERCEKLER",
    "converging lens: f > 0": "ince kenarlı mercek: f > 0",
    "I cannot see the blackboard": "tahtayı göremiyorum",
    "CARBON COPIES": "KARBON KOPYALAR",
    "copy 03 ≠ original": "kopya 03 ≠ asıl",
    "pressure transfers the mark": "basınç izi aktarır",
    "the folder is still running": "dosya hâlâ kaçıyor",
    "EVIDENCE VAULT": "KANIT KASASI",
    "file 04 / access denied": "dosya 04 / erişim yok",
    "one stamp, two shadows": "bir damga, iki gölge",
    "follow the red line upstairs": "kırmızı çizgiyi yukarı izle",
    "FINAL LESSON / REVISION": "SON DERS / DÜZELTME",
    "show your working!": "işlemlerini göster!",
    "NEWTON'S THIRD LAW": "NEWTON'UN ÜÇÜNCÜ YASASI",
    "action and reaction": "etki ve tepki",
    "the paper hits back": "kağıt karşılık veriyor",
    "EQUATIONS": "DENKLEMLER",
    "revise it; do not start over": "düzelt; baştan başlama",
    "IS CLASS OVER?": "DERS BİTTİ Mİ?",
    "answer = ?": "cevap = ?",
    "the back of this page is blank": "bu sayfanın arkası boş",
    "wait for the bell": "zili bekle",
    "REVISION HISTORY": "DÜZELTME GEÇMİŞİ",
    "the first answer is crossed out": "ilk cevap silinmiş",
    "you can keep the crooked one": "eğri olanı saklayabilirsin",
    "LAST CORRIDOR": "SON KORİDOR",
    "jump over what was erased": "silinenin üstünden zıpla",
    "turning the page is your answer": "cevabın sayfayı çevirmek",

    # Page names and notes already drawn through NotebookMaterial.hand.
    "boring lesson": "sıkıcı ders",
    "do not tear": "yırtma",
    "turn me over": "beni çevir",
    "ink on my hand": "elim mürekkep oldu",
    "first attempt": "ilk deneme",
    "bamboo exercise": "bambu alıştırması",
    "broken footbridge": "kırık köprü",
    "ink dojo": "mürekkep dojosu",
    "roof of the shrine": "tapınağın çatısı",
    "lantern festival": "fener şenliği",
    "rejected warriors": "reddedilen savaşçılar",
    "moon gate": "ay kapısı",
    "the sword lesson": "kılıç dersi",
    "after the duel": "düellodan sonra",
    "a quieter line": "daha sessiz bir çizgi",
    "end of the scroll": "tomarın sonu",
    "railway timetable": "tren tarifesi",
    "wanted / alive?": "aranıyor / canlı mı?",
    "six shots only": "yalnızca altı atış",
    "coffee spill town": "kahve dökülen kasaba",
    "beyond the red rule": "kırmızı çizginin ötesi",
    "empty saloon": "boş salon",
    "windmill repairs": "yel değirmeni tamiri",
    "cactus country": "kaktüs diyarı",
    "water tower": "su kulesi",
    "midnight freight": "gece yük treni",
    "bounty archive": "ödül arşivi",
    "last station": "son istasyon",
    "train home": "eve giden tren",
    "missed the train": "treni kaçırdım",
    "gravity homework": "yerçekimi ödevi",
    "failed launch": "başarısız fırlatma",
    "orbit laboratory": "yörünge laboratuvarı",
    "zero garden": "sıfır bahçesi",
    "telescope repairs": "teleskop tamiri",
    "debris forecast": "enkaz tahmini",
    "moon survey": "ay araştırması",
    "radio silence": "radyo sessizliği",
    "null chamber": "boşluk odası",
    "star nursery": "yıldız yuvası",
    "wrong equation": "yanlış denklem",
    "escape velocity": "kaçış hızı",
    "observatory": "gözlemevi",
    "erased orbit": "silinen yörünge",
    "the big mistake": "büyük hata",
    "one giant baby": "bir dev bebek",
    "back to earth": "dünyaya dönüş",
    "end of experiment": "deneyin sonu",
    "classified homework": "gizli ödev",
    "checkpoint sketch": "kayıt noktası eskizi",
    "service tunnel": "servis tüneli",
    "carbon copy office": "karbon kopya bürosu",
    "missing personnel": "kayıp personel",
    "rooftop surveillance": "çatı gözetimi",
    "dead letter drop": "gizli posta noktası",
    "the archive": "arşiv",
    "office floor plan": "büro kat planı",
    "director of redaction": "sansür müdürü",
    "case closed": "dosya kapandı",
    "unsigned report": "imzasız rapor",
    "last lesson": "son ders",
    "unfinished answer": "yarım cevap",
    "discard pile": "atılan çizimler",
    "paper cemetery": "kağıt mezarlığı",
    "what survived": "geriye kalanlar",
    "the rebels": "isyancılar",
    "wrong endings": "yanlış sonlar",
    "your handwriting": "senin el yazın",
    "the final question": "son soru",
    "a new ending": "yeni bir son",
    "keep drawing": "çizmeye devam et",
    "after the bell": "zilden sonra",
    "do not sharpen the sword": "kılıcı sivriltme",
    "bamboo bends / ink does not": "bambu eğilir / mürekkep eğilmez",
    "balance before speed": "hızdan önce denge",
    "three cuts, then breathe": "üç vuruş, sonra soluklan",
    "depart 23:07 / never on time": "kalkış 23:07 / hep gecikir",
    "reward: one clean sheet": "ödül: temiz bir sayfa",
    "wind from the coffee stain": "kahve lekesinden gelen rüzgar",
    "draw another way out": "başka bir çıkış çiz",
    "mass = mistake / time²": "kütle = hata / zaman²",
    "signal lost ... try again": "sinyal yok ... tekrar dene",
    "oxygen? forgot that part": "oksijen? onu unutmuşum",
    "the moon is drifting": "ay sürükleniyor",
    "copy 03 / original missing": "kopya 03 / aslı kayıp",
    "NO NAMES PAST THIS LINE": "BU ÇİZGİDEN SONRA İSİM YOK",
    "blind spot: roof access": "kör nokta: çatı girişi",
    "evidence must not be erased": "kanıtlar silinmemeli",
    "not every mistake needs fixing": "her hata düzeltilmez",
    "this answer is yours": "bu cevap senin",
    "I kept the first version": "ilk halini sakladım",
    "the last word is unwritten": "son söz henüz yazılmadı",
    "revised after the bell": "zilden sonra düzeltildi",
    "roof route?": "çatı yolu mu?",
    "wind ->": "rüzgar ->",
    "a different face in every lantern": "her fenerde başka bir yüz",
    "do not draw the moon twice": "ayı iki kez çizme",
    "WANTED": "ARANIYOR",
    "for stealing my lunch": "öğle yemeğimi çaldığı için",
    "next stop: wrong side of the page": "sonraki durak: sayfanın yanlış yüzü",
    "water / probably coffee": "su / muhtemelen kahve",
    "SALOON": "SALOON",
    "closed during maths": "matematik dersinde kapalı",
    "the missing moon goes here ->": "kayıp ay buraya ->",
    "launch postponed (again)": "fırlatma ertelendi (yine)",
    "someone is looking back": "birisi geri bakıyor",
    "debris / do not stand here": "enkaz / burada durma",
    "ORIGINAL / COPY / COPY?": "ASIL / KOPYA / KOPYA MI?",
    "names removed by the Director": "isimleri Müdür sildi",
    "my route / his blind spot": "benim rotam / onun kör noktası",
    "it follows the line, not you": "seni değil, çizgiyi izler",
    "FILE 04 / missing original": "DOSYA 04 / aslı kayıp",
    "archive route / guard crossed out": "arşiv yolu / muhafız silindi",
    "keep the crooked one": "eğri olanı sakla",
    "some endings are only drafts": "bazı sonlar sadece taslaktır",
    "your turn to answer": "cevap sırası sende",
    "no perfect version": "kusursuz hali yok",
    "SWORD": "KILIÇ",
    "TICKET": "BİLET",
    "ORBIT": "YÖRÜNGE",
    "FILE": "DOSYA",
    "keep one answer": "bir cevabı sakla",
    "a line can still change direction": "çizgi hâlâ yön değiştirebilir",
    "unfinished": "yarım kaldı",
    "check this": "buna bak",
    "needs another line": "bir çizgi daha gerek",
    "not on the test": "sınavda yok",
    "TRAIN / PAGE": "TREN / SAYFA",
    "COPY 00": "KOPYA 00",
    "PAGE I  /  CUT": "SAYFA I / KES",
    "PAGE II /  AIM": "SAYFA II / NİŞAN",
    "PAGE III / FLOAT": "SAYFA III / SÜZÜL",
    "PAGE IV / HIDE": "SAYFA IV / GİZLEN",
    "03    ERASED": "03    SİLİNDİ",
    "BRIDGE / TRY 2": "KÖPRÜ / DENEME 2",
    "THE BLADE REMEMBERS": "KILIÇ HATIRLAR",
    "A TREE I COULD NOT ERASE": "SİLEMEDİĞİM BİR AĞAÇ",
    "FESTIVAL AFTER CLASS": "DERSTEN SONRA ŞENLİK",
    "THE ARC IS NOT A WALL": "YAY BİR DUVAR DEĞİL",
    "MISSED THE FIRST TRAIN": "İLK TRENİ KAÇIRDIM",
    "CLOSED FOR HOMEWORK": "ÖDEV İÇİN KAPALI",
    "THE WIND GOT BORED": "RÜZGAR SIKILDI",
    "WATER? / COFFEE": "SU MU? / KAHVE",
    "LAST TRAIN / 23:07": "SON TREN / 23:07",
    "GRAVITY / PLEASE WORK": "YERÇEKİMİ / LÜTFEN ÇALIŞ",
    "LAUNCH ATTEMPT 04": "FIRLATMA DENEMESİ 04",
    "SOME ASSEMBLY REQUIRED": "BİRAZ MONTAJ GEREK",
    "SIGNAL LOST": "SİNYAL YOK",
    "NOT TO SCALE": "ÖLÇEKLİ DEĞİL",
    "YOU ARE FILE 00": "SEN DOSYA 00'SIN",
    "FILE 03 / ORIGINAL?": "DOSYA 03 / ASLI MI?",
    "THE SECOND COPY MOVES": "İKİNCİ KOPYA HAREKET EDİYOR",
    "BLIND SPOT": "KÖR NOKTA",
    "EVIDENCE / DO NOT ERASE": "KANIT / SİLME",
    "NO ONE DREW THIS THREAD": "BU İPİ KİMSE ÇİZMEDİ",
    "ONE LAST LESSON": "SON BİR DERS",
    "ANSWERS IN THE MARGIN": "CEVAPLAR KENARDA",
    "THE OTHER FOUR PAGES": "DİĞER DÖRT SAYFA",
    "THE OLD VERSIONS": "ESKİ HALLERİ",
    "KEEP THE WRONG ANSWER": "YANLIŞ CEVABI SAKLA",
    "YOUR NEXT LINE": "SONRAKİ ÇİZGİN",
    "CLASSIFIED / carbon copy": "GİZLİ / karbon kopya",
    "F = ma ... maybe": "F = ma ... galiba",
    "x + y = another problem": "x + y = başka bir sorun",
    "DO NOT ERASE THE HERO": "KAHRAMANI SİLME",

    # Other nearby player-facing notices and short arsenal descriptions.
    "THE ARTIST: A small revision. Next wave in a moment.": "RESSAM: Küçük bir düzeltme. Yeni dalga birazdan.",
    "the ink is still wet": "mürekkep hâlâ ıslak",
    "FIELD KNIFE": "SAHA BIÇAĞI",
    "rapid chain · execute wounded targets": "hızlı seri · yaralı hedefi bitir",
    "quick, precise fire · light recoil": "hızlı, isabetli atış · hafif geri tepme",
    "tight grouping · controlled shove": "dar saçılım · kontrollü itiş",
    "third cut fires a piercing wave": "üçüncü kesiş delici dalga atar",
    "stay close · mark twice · cash out": "yaklaş · iki kez işaretle · bitir",
    "eight fast shots · quiet · reload often": "sekiz hızlı atış · sessiz · sık doldur",
    "tight burst · controlled shove": "dar saçılım · kontrollü itiş",
    "every stroke returns as a delayed trace": "her vuruş gecikmeli bir iz olarak döner",
    "two ricochets · hold to fire": "iki sekme · ateş için basılı tut",
    "lob two capsules · small paper burst": "iki kapsül at · küçük kağıt patlaması",
    "A / D   ·   Left / Right": "A / D   ·   ← / →",
    "the roots are lines too": "kökler de birer çizgi",
    "the page tears down here": "sayfa burada yırtılıyor",
    "gravity homework / use the working lines": "yerçekimi ödevi / çizgileri kullan",
    "original above / carbon copy below": "aslı yukarıda / karbon kopyası aşağıda",
    "the answer climbs out of the margin": "cevap kenardan yukarı tırmanır",
    "01 / FALSE ID": "01 / SAHTE KİMLİK",
    "The agent commits to three shots. Then reloads.": "Ajan üç atış yapar. Sonra doldurur.",
    "02 / CARBON CROSSFIRE": "02 / KARBON ÇAPRAZ ATEŞİ",
    "Climb the ink line; drop behind the shield.": "Mürekkep çizgisine çık; kalkanın arkasına in.",
    "03 / ROOFTOP REVISION": "03 / ÇATI DÜZELTMESİ",
    "Leave the violet column before the ink falls.": "Mürekkep düşmeden mor sütundan çık.",
    "04 / THE OFFICE BITES": "04 / BÜRO ISIRIYOR",
    "Deal with the turret before the next copy.": "Yeni kopyadan önce tareti etkisiz hale getir.",
    "05 / EVIDENCE VAULT": "05 / KANIT KASASI",
    "Copies guard the files. Break their line of sight.": "Dosyaları kopyalar koruyor. Görüş hattından çık.",
    "THE HEAD OF REDACTION": "SANSÜR MÜDÜRÜ",
    "Jump his baton. Leave the firing lines. Strike the exposed core.": "Copun üstünden zıpla. Atış hattından çık. Açık çekirdeği vur.",
    "01 / WRONG CLASS": "01 / YANLIŞ SINIF",
    "Five pages of enemies. One small stick figure.": "Beş sayfa düşman. Bir küçük çöp adam.",
    "02 / ERASED ANSWERS": "02 / SİLİNEN CEVAPLAR",
    "A platform can save you. Watch the eraser.": "Bir basamak seni kurtarır. Silgiye dikkat et.",
    "03 / MARGIN REVOLT": "03 / KENAR İSYANI",
    "Jump the gold rake, then break the ranged line.": "Altın tırmığı zıplayarak aş, sonra atış hattını boz.",
    "04 / THE LAST CROSSOUT": "04 / SON ÇİZİK",
    "The blue trail stays hot. Cross it in the air.": "Mavi iz tehlikeli kalır. Havadan geç.",
    "05 / UNFINISHED CORRIDOR": "05 / YARIM KORİDOR",
    "Old drafts can still fight. Move between their styles.": "Eski taslaklar da savaşır. Tarzlarına göre hareket et.",
    "THE REJECTED HERO": "REDDEDİLEN KAHRAMAN",
    "Read your old draft. Attack when its guard drops.": "Eski taslağını oku. Savunması düşünce saldır.",
    "THE REJECTED CAST": "REDDEDİLEN KADRO",
    "I left my first attempts here. They do not want to be forgotten.": "İlk denemelerimi burada bıraktım. Unutulmak istemiyorlar.",
    "You gave the old drawing a second chance. Keep what it taught you.": "Eski çizime ikinci şans verdin. Öğrettiğini sakla.",
    "THE BOUNTY IN THE MARGIN": "KENARDAKİ ÖDÜL",
    "That scrap has a bounty on it. Shall I draw the ones hunting it?": "O parçanın ödülü var. Peşindekileri çizeyim mi?",
    "I was going to write a price. You made it a name instead.": "Bir fiyat yazacaktım. Sen ona bir isim verdin.",
    "THE FAILED EXPERIMENT": "BAŞARISIZ DENEY",
    "This experiment escaped the calculation. Help me finish it?": "Bu deney hesabı aştı. Bitirmeme yardım eder misin?",
    "The mistake was useful. I will leave your answer in the margin.": "Hata işe yaradı. Cevabını kenarda bırakacağım.",
    "THE CARBON ARCHIVE": "KARBON ARŞİVİ",
    "That file is being watched. Open it and they will know you are here.": "O dosyayı izliyorlar. Açarsan burada olduğunu anlarlar.",
    "A copy can hide a name. It cannot hide what you just did.": "Kopya bir ismi gizler. Az önce yaptığını gizleyemez.",
    "THE UNFINISHED ANSWER": "YARIM CEVAP",
    "These are the endings I threw away. Can you face them?": "Bunlar attığım sonlar. Onlarla yüzleşebilir misin?",
    "All right. Your answer stays. I am putting the eraser down.": "Peki. Cevabın kalıyor. Silgiyi bırakıyorum.",
}

# Finite authored pickup labels share their canonical weapon identities.
# Cover the complete notice before any wrapping, so the tool name is translated
# together with the prompt instead of leaving a mixed English/Turkish sentence.
_DRAWN_TOOL_LABELS = {
    "FOLD CROSSBOW": "KATLAMA ARBALETİ",
    "BAMBOO CROSSBOW": "BAMBU ARBALETİ",
    "ORBIT SAW": "YÖRÜNGE TESTERESİ",
    "REVISION WHEEL": "DÜZELTME ÇARKI",
    "INK KATANA": "MÜREKKEP KATANA",
    "PENCIL BLADE": "KALEM BIÇAĞI",
    "RETURNING FOLD": "GERİ DÖNEN KATLAMA",
    "OVERSIZED PENCIL": "DEV KALEM",
    "CHALK CAPSULE": "TEBEŞİR KAPSÜLÜ",
    "METEOR CHALK": "METEOR TEBEŞİRİ",
    "CARBON RIFLE": "KARBON TÜFEĞİ",
    "INK PISTOL": "MÜREKKEP TABANCASI",
    "SIX-SHOOTER": "ALTIPATLAR",
    "SUPPRESSED PISTOL": "SUSTURUCULU TABANCA",
    "MARKER SHOTGUN": "KEÇELİ POMPALI",
    "DOUBLE BARREL": "ÇİFTE",
    "BREACH SHOTGUN": "YARMA POMPALISI",
    "ERASER CANNON": "SİLGİ TOPU",
    "NULL CANNON": "BOŞLUK TOPU",
    "RUBBER BAND": "LASTİK SAPAN",
    "ORBIT PULSE": "YÖRÜNGE DARBESİ",
    "BOWIE KNIFE": "BOWIE BIÇAĞI",
    "FIELD KNIFE": "SAHA BIÇAĞI",
    "ION EDGE": "İYON KESKİNİ",
    "REDRAW PENCIL": "YENİDEN ÇİZİM KALEMİ",
    "THE VERY DRAMATIC SWORD": "AŞIRI DRAMATİK KILIÇ",
    "ORBITAL RUBBER BAND": "YÖRÜNGE SAPANI",
}
for _source, _translated in _DRAWN_TOOL_LABELS.items():
    TR_CONTENT[_source] = _translated
    TR_CONTENT[f"E  take {_source}"] = f"E  {_translated} al"
    TR_CONTENT[f"NEW DRAWING — {_source}"] = f"YENİ ÇİZİM — {_translated}"


__all__ = ["TR_CONTENT"]
