"""Authored German player-facing text; English sources remain canonical."""

DE = {
    'TRAINING': 'TRAINING',
    'FIELD NOTES / 0.31': 'FELDNOTIZEN / 0.31',
    'TRAINING COMPLETE / your campaign progress is kept': 'TRAINING BEENDET / Fortschritt gespeichert',
    'F / J or left click: destroy all four targets along the practice lane.': 'F / J oder Linksklick: Zerstöre die vier Ziele.',
    'Shift / K or right click: leave the frozen red column before it fires. Dodge three warnings.': 'Shift / K oder Rechtsklick: Verlasse die rote Säule vor dem Schuss. Weiche dreimal aus.',
    'E at the pencil lever: ask the Artist for stairs. Climb to the rune seal and read it with E.': 'E am Bleistifthebel: Lass Treppen zeichnen. Klettere zur Rune und lies sie mit E.',
    'TRAINING YARD / FOUR TARGETS': 'ÜBUNGSPLATZ / VIER ZIELE',
    'DODGE LANE / FOLLOW THE WARNING': 'AUSWEICHEN / ACHTE AUF DIE WARNUNG',
    "THE ARTIST'S STAIRS / CLIMB TO THE RUNE": 'DIE TREPPE DES ZEICHNERS / ZUR RUNE',
    'E / ARTIST': 'E / ZEICHNER',
    'E / ask the Artist to draw the training stairs': 'E / Treppe zeichnen lassen',
    'Good dodge. The red mark stayed where it was drawn.': 'Gut ausgewichen. Die rote Markierung blieb stehen.',
    'Practice only: dash out of the red column after it appears.': 'Übung: Weiche aus, sobald die rote Säule erscheint.',
    'EXPLORE / three blue marks above the road': 'ERKUNDE / drei blaue Markierungen über dem Weg',
    'E / trace the blue waypoint': 'E / blauen Wegpunkt nachzeichnen',
    'E / THREE BLUE MARKS / +1 HEART': 'E / DREI BLAUE MARKIERUNGEN / +1 HERZ',
    'The Artist traced your route and restored one heart.': 'Der Zeichner hat deine Route nachgezogen und ein Herz erneuert.',
    'BAMBOO WALK': 'BAMBUSPFAD',
    'THE OLD VIADUCT': 'DER ALTE VIADUKT',
    'SATELLITE WALK': 'SATELLITENPFAD',
    'THE ROOFTOP ARCHIVE': 'DAS DACHARCHIV',
    'THE UNWRITTEN GARDEN': 'DER UNBESCHRIEBENE GARTEN',
    'HIGH THRUST — STAY LOW': 'HOHER STOSS — BLEIB UNTEN',
    'LOW RICOCHET — JUMP OR RETURN': 'TIEFER ABPRALLER — SPRING ODER REFLEKTIERE',
    'LOW THEN HIGH — JUMP, THEN LAND': 'ERST TIEF, DANN HOCH — SPRING UND LANDE',
    'COMET RAIN — KEEP THE BLUE GAP': 'KOMETENREGEN — BLEIB IN DER BLAUEN LÜCKE',
    'JUMP THE CLOSING BRACKET': 'SPRING ÜBER DIE SCHLIESSENDE KLAMMER',
    'ERASER RAIN — LEAVE THE NUMBERED MARKS': 'RADIERERREGEN — VERLASS DIE NUMMERIERTEN MARKEN',
    'The Artist:': 'Der Zeichner:',
    'the Artist:': 'der Zeichner:',
    'NEW GAME': 'NEUES SPIEL',
    'CONTINUE': 'FORTSETZEN',
    'SETTINGS': 'EINSTELLUNGEN',
    'QUIT': 'BEENDEN',
    'BACK PAGES': 'SKIZZENBUCH',
    'ACHIEVEMENTS': 'ERFOLGE',
    'ACHIEVEMENT': 'ERFOLG',
    'RESTART PAGE': 'SEITE NEU STARTEN',
    'TITLE': 'HAUPTMENÜ',
    'CONTROLS': 'STEUERUNG',
    'Back': 'Zurück',
    'Master volume': 'Gesamtlautstärke',
    'SFX volume': 'Effektlautstärke',
    'Music volume': 'Musiklautstärke',
    'Window size': 'Fenstergröße',
    'Fullscreen': 'Vollbild',
    'Language': 'Sprache',
    'YES': 'JA',
    'NO': 'NEIN',
    'page held open': 'Seite offen gehalten',
    'Every line leaves a mark.': 'Jede Linie hinterlässt eine Spur.',
    'FIELD NOTES / 0.30': 'FELDNOTIZEN / 0.30',
    'A longer lesson. Hidden margins.': 'Eine längere Lektion. Versteckte Ränder.',
    'New attacks. Ideas worth keeping.': 'Neue Angriffe. Ideen zum Aufbewahren.',
    'Arrows / W S select  ·  ENTER play  ·  click to choose': 'Pfeile / W S: wählen · ENTER: spielen · klicken: wählen',
    'ESC continue  ·  arrows select  ·  ENTER confirm': 'ESC: fortsetzen · Pfeile: wählen · ENTER: bestätigen',
    'Learn the line, then make it yours.': 'Lerne die Linie und zeichne deinen Weg.',
    'Move': 'Bewegen',
    'Jump': 'Springen',
    'Attack': 'Angreifen',
    'Dash / return': 'Ausweichen / reflektieren',
    'Interact / sketch': 'Interagieren / skizzieren',
    'Reload / switch': 'Nachladen / wechseln',
    'Drop through': 'Durch Plattform fallen',
    'Pause / fullscreen': 'Pause / Vollbild',
    'Space / W / Up  ·  release for a short jump': 'Leertaste / W / ↑ · loslassen für kurzen Sprung',
    'F / J  ·  left click aims at the pointer': 'F / J · Linksklick: auf den Zeiger zielen',
    'Shift / K  ·  right click': 'Shift / K · Rechtsklick',
    'R  /  Q or mouse wheel': 'R / Q oder Mausrad',
    'S or Down + any jump key': 'S oder ↓ + Sprungtaste',
    'ENTER / ESC   Back': 'ENTER / ESC   Zurück',
    'Rejected drawings. Real techniques. Learned ideas survive every redraw.': 'Verworfene Zeichnungen. Bleibende Techniken.',
    'next  >': 'weiter >',
    '<  previous': '< zurück',
    'A / ESC   close': 'A / ESC   schließen',
    'B / ESC   close the back cover': 'B / ESC   Skizzenbuch schließen',
    'PAD-A / PAD-B   close the back cover': 'PAD-A / PAD-B   Skizzenbuch schließen',
    'PAD-A / PAD-B   close': 'PAD-A / PAD-B   schließen',
    'D-PAD choose   •   PAD-A confirm   •   PAD-B continue': 'D-PAD: wählen • PAD-A: bestätigen • PAD-B: fortsetzen',
    'D-PAD change  •  PAD-A confirm  •  PAD-B returns': 'D-PAD: ändern • PAD-A: bestätigen • PAD-B: zurück',
    'click or use arrows  •  F11 fullscreen  •  ESC returns': 'Klicken oder Pfeile • F11: Vollbild • ESC: zurück',
    'CONTROLLER CONNECTED': 'CONTROLLER VERBUNDEN',
    'CONTROLLER READY': 'CONTROLLER BEREIT',
    'condition not written down': 'Bedingung noch unbekannt',
    'the page remains open   —   ENTER': 'Die Seite bleibt offen — ENTER',
    'checkpoint — redrawn here': 'Kontrollpunkt — hier neu gezeichnet',
    'dash': 'Ausweichen',
    'IN HAND': 'IN DER HAND',
    'RELOAD': 'NACHLADEN',
    'EMPTY HANDS': 'LEERE HÄNDE',
    'the next tool is still being drawn': 'Das nächste Werkzeug wird noch gezeichnet.',
    'INK KATANA': 'TINTENKATANA',
    'PENCIL BLADE': 'BLEISTIFTKLINGE',
    'INK PISTOL': 'TINTENPISTOLE',
    'RETURNING FOLD': 'RÜCKKEHRFALTE',
    'OVERSIZED PENCIL': 'RIESENBLEISTIFT',
    'SIX-SHOOTER': 'SECHSSCHÜSSER',
    'DOUBLE BARREL': 'DOPPELLAUF',
    'CHALK CAPSULE': 'KREIDEKAPSEL',
    'METEOR CHALK': 'METEORKREIDE',
    'CARBON RIFLE': 'KARBONGEWEHR',
    'MARKER SHOTGUN': 'MARKERSCHROTFLINTE',
    'ERASER CANNON': 'RADIERERKANONE',
    'NULL CANNON': 'NULLKANONE',
    'RUBBER BAND': 'GUMMIBAND',
    'ORBIT PULSE': 'ORBITALIMPULS',
    'BOWIE KNIFE': 'BOWIEMESSER',
    'ION EDGE': 'IONENKLINGE',
    'SUPPRESSED PISTOL': 'SCHALLGEDÄMPFTE PISTOLE',
    'BREACH SHOTGUN': 'STURMSCHROTFLINTE',
    'THE VERY DRAMATIC SWORD': 'DAS SEHR DRAMATISCHE SCHWERT',
    'KING ARTHUR · subtlety unavailable': 'KÖNIG ARTUS · Feingefühl nicht verfügbar',
    'draw dash · return step · rising launch': 'Schnitt im Sprint · Rückschritt · Aufwärtshieb',
    'one fold at a time · catch the return line': 'Eine Falte pro Wurf · fange die Rückkehr',
    'wind up · crush · erase shots in reach': 'Ausholen · zerschlagen · nahe Schüsse löschen',
    'six heavy shots · deliberate rhythm': 'Sechs starke Schüsse · ruhiger Rhythmus',
    'arc over cover · two gentle bursts': 'Über Deckung werfen · zwei kleine Explosionen',
    'two quick blasts · wide spread': 'Zwei schnelle Schüsse · breite Streuung',
    'arc around shields · small impact cloud': 'Bogen um Schilde · kleine Trefferwolke',
    'three ricochets · bank off ink': 'Drei Abpraller · an Tinte abprallen',
    'cut through volleys · straight flight': 'Durch Salven schneiden · gerader Flug',
    'one round · pierces a line · long reload': 'Ein Schuss · durchschlägt eine Linie · langes Nachladen',
    'close-range ink burst': 'Tintenschwall aus der Nähe',
    'erase incoming fire': 'Ankommende Schüsse löschen',
    'steady ink fire': 'Stetiges Tintenfeuer',
    'three strokes · heavy finish': 'Drei Hiebe · starker Abschluss',
    '01 / FIND YOUR FEET': '01 / FINDE DEINEN HALT',
    '02 / FOLLOW THE INK': '02 / FOLGE DER TINTE',
    '03 / THE RETURNING FOLD': '03 / DIE RÜCKKEHRFALTE',
    '04 / LEAVE THE RED LINE': '04 / VERLASS DIE ROTE LINIE',
    '05 / IDEAS THAT STAY': '05 / IDEEN, DIE BLEIBEN',
    'A / D or Left / Right: move. Explore the first lines.': 'A / D oder ← / →: Bewegen. Erkunde die ersten Linien.',
    'Space / W / Up: jump. Release early for a short jump. Collect the drawn tool.': 'Leertaste / W / ↑: Springen. Früh loslassen für kurze Sprünge. Nimm das Werkzeug.',
    'F / J or left click: hit the practice drawing with your Returning Fold.': 'F / J oder Linksklick: Triff das Übungsziel mit der Rückkehrfalte.',
    'Shift / K or right click: dash three times. Watch the recovery line.': 'Shift / K oder Rechtsklick: Weiche dreimal aus. Achte auf die Erholung.',
    'E at the lesson seal: read how sketches work. B in pause opens your learned runes.': 'E am Lehrsiegel: Lerne Skizzen kennen. B in der Pause öffnet deine Runen.',
    'Destroy the practice drawing': 'Zerstöre das Übungsziel',
    'Seal read': 'Siegel gelesen',
    'Read the seal with E': 'Lies das Siegel mit E',
    'E / LESSON SEAL': 'E / LEHRSIEGEL',
    'E  read the lesson seal / sketches are lasting runes': 'E / Lehrsiegel lesen',
    'SKETCH RUNES: Permanent techniques, clear numeric effects. They survive page turns and redraws. Find them on optional routes.': 'SKIZZENRUNEN: Dauerhafte Techniken mit klaren Werten. Suche sie auf Nebenwegen.',
    'FIRST LESSON COMPLETE / the combat page is open': 'ERSTE LEKTION BEENDET / Kampfseite geöffnet',
    'Lost Sketches are discarded ideas. Keep them to learn lasting tricks across pages.': 'Verlorene Skizzen lehren dauerhafte Techniken.',
    'LOST SKETCH — clipped into the back pages.': 'VERLORENE SKIZZE — ins Skizzenbuch geheftet.',
    'UNDISCOVERED SKETCH': 'UNENTDECKTE SKIZZE',
    'ACTIVE': 'AKTIV',
    'NEEDS ITS WEAPON': 'WAFFE BENÖTIGT',
    'SAVED / NEEDS ITS WEAPON': 'GESPEICHERT / WAFFE BENÖTIGT',
    'A rejected drawing. A useful idea.': 'Verworfenes Bild. Nützliche Idee.',
    'Clipped into BACK PAGES': 'Ins SKIZZENBUCH geheftet',
    'SEALED / finish the margin challenge': 'VERSIEGELT / Bestehe die Randprüfung',
    'E  keep this drawing': 'E / Zeichnung behalten',
    'E  examine lost sketch': 'E / verlorene Skizze ansehen',
    'Defeat the rejected drawing below': 'Besiege die verworfene Zeichnung unten',
    'E  challenge the drawing / optional': 'E / Zeichnung herausfordern (optional)',
    'THE FIRST FIGURE': 'DIE ERSTE FIGUR',
    'SECOND THOUGHT': 'ZWEITER GEDANKE',
    'PRACTICE MONSTER': 'ÜBUNGSMONSTER',
    'FOLLOW THROUGH': 'DURCHZIEHEN',
    'THE KITE RONIN': 'DER DRACHENRONIN',
    'PAPER KITE': 'PAPIERDRACHE',
    'THE MARGIN HOUSE': 'DAS RANDHAUS',
    'QUICK DRAW': 'SCHNELLZIEHER',
    'COFFEE UMBRELLA': 'KAFFEESCHIRM',
    'TIGHT FOLD': 'ENGE FALTE',
    'THE VICTORY POSE': 'DIE SIEGESPOSE',
    'MAKE SOME ROOM': 'PLATZ SCHAFFEN',
    'THE UNUSED TICKET': 'DIE UNBENUTZTE FAHRKARTE',
    'THROUGH TICKET': 'DURCHGANGSKARTE',
    'THE APOLOGETIC BEAST': 'DAS REUMÜTIGE UNGEHEUER',
    'ELASTIC MEMORY': 'ELASTISCHE ERINNERUNG',
    'THE ERASER SURVIVOR': 'DER RADIERERÜBERLEBENDE',
    'CLEAN SLATE': 'REINES BLATT',
    'THE SECOND MOON': 'DER ZWEITE MOND',
    'LOW ORBIT': 'NIEDRIGE UMLAUFBAHN',
    'THE FORGED BADGE': 'DER GEFÄLSCHTE AUSWEIS',
    'FAST INK': 'SCHNELLE TINTE',
    'THE LAST HOMEWORK': 'DIE LETZTE HAUSAUFGABE',
    'REVISION RHYTHM': 'KORREKTURRHYTHMUS',
    'THE RONIN': 'DER RONIN',
    'HIGH NOON': 'MITTAGSDUELL',
    'THE AGENT': 'DER AGENT',
    'THE LAST DRAFT': 'DER LETZTE ENTWURF',
    'Jump a little later after leaving an edge.': 'Springe noch kurz nach Verlassen einer Kante.',
    'Your blade finisher reaches farther.': 'Dein letzter Klingenhieb reicht weiter.',
    'Change direction faster in the air.': 'Wechsle in der Luft schneller die Richtung.',
    'Reload your sidearm faster.': 'Lade deine Pistole schneller nach.',
    'Your scattergun keeps a tighter spread.': 'Deine Schrotflinte streut weniger.',
    'Scattergun hits push enemies farther.': 'Schrotflintentreffer stoßen Gegner weiter zurück.',
    'Sidearm shots pass through one enemy.': 'Pistolenschüsse durchschlagen einen Gegner.',
    'Ricochet shots bounce one more time.': 'Abpraller springen einmal öfter zurück.',
    'Reload your heavy cannon faster.': 'Lade deine schwere Kanone schneller nach.',
    'Ricochet shots stay in flight longer.': 'Abpraller bleiben länger im Flug.',
    'Sidearm bullets reach their target faster.': 'Pistolenkugeln erreichen ihr Ziel schneller.',
    'Your dash becomes ready sooner.': 'Dein Ausweichen ist früher wieder bereit.',
    'PAGE I': 'SEITE I',
    'PAGE II': 'SEITE II',
    'PAGE III': 'SEITE III',
    'PAGE IV': 'SEITE IV',
    'PAGE V': 'SEITE V',
    'Ink of the Ronin': 'Tinte des Ronin',
    'Dust & Bad Decisions': 'Staub und schlechte Entscheidungen',
    'A Very Wrong Future': 'Eine sehr falsche Zukunft',
    'The Carbon Agent': 'Der Karbonagent',
    'The Last Draft': 'Der letzte Entwurf',
    'THE ARTIST': 'DER ZEICHNER',
    'ARTIST': 'ZEICHNER',
    'WAIT / the Artist is finishing this line': 'WARTE / Der Zeichner beendet die Linie',
    'E  trace the first graphite mark': 'E / erste Graphitmarke nachzeichnen',
    'E  connect the upper mark': 'E / obere Markierung verbinden',
    'E  cross out the red margin': 'E / roten Rand durchstreichen',
    'FIRST / lower pencil mark': 'ZUERST / untere Bleistiftmarke',
    'NEXT / upper pencil mark': 'DANN / obere Bleistiftmarke',
    'LAST / cross out the margin': 'ZULETZT / Rand durchstreichen',
    '1 / TRACE': '1 / NACHZEICHNEN',
    '2 / CONNECT ABOVE': '2 / OBEN VERBINDEN',
    '3 / CROSS OUT': '3 / DURCHSTREICHEN',
    'THE ARTIST: A step belongs above this line.': 'DER ZEICHNER: Hier oben fehlt eine Stufe.',
    'THE ARTIST: Yes. Find the last crossed-out mark.': 'DER ZEICHNER: Ja. Finde die letzte durchgestrichene Marke.',
    'THE ARTIST: Erasing the margin now.': 'DER ZEICHNER: Ich radiere den Rand weg.',
    'THE ARTIST: Better. That line can go.': 'DER ZEICHNER: Besser. Die Linie kann weg.',
    'arena sealed — clear every red mark': 'Arena versiegelt — beseitige alle roten Marken',
    'arena clear — ink dries, the margin opens': 'Arena geräumt — der Rand öffnet sich',
    'the gate shuts — a named drawing waits below': 'Das Tor schließt — eine besondere Zeichnung wartet unten',
    'READ THE RED MARK — MOVE, THEN PUNISH': 'LIES DIE ROTE MARKE — WEICHE AUS, DANN SCHLAG ZU',
    'Too heavy? You asked for it. Q swaps back.': 'Zu schwer? Du wolltest ihn. Mit Q wechselst du zurück.',
    'All right. Your way. Jump onto the new line.': 'Gut. Dein Weg. Spring auf die neue Linie.',
    'Too many teeth. Let me fix that.': 'Zu viele Zähne. Ich bessere das aus.',
    'He changed the rules. So can we. Use this line.': 'Er hat die Regeln geändert. Wir auch. Nutze diese Linie.',
    'E  ASK THE ARTIST TO ERASE A FOE (once this room)': 'E / Gegner radieren lassen (einmal pro Raum)',
    'DRAW A HEAVY PENCIL': 'RIESENBLEISTIFT ZEICHNEN',
    'DRAW A HIGH ROAD': 'HOHEN WEG ZEICHNEN',
    'next lesson...': 'Nächste Lektion...',
    'Who drew the gun?': 'Wer hat die Pistole gezeichnet?',
    'I did not draw that moon.': 'Den Mond habe ich nicht gezeichnet.',
    'Someone is cutting the notebook.': 'Jemand zerschneidet das Notizbuch.',
    'He has been reading your moves.': 'Er hat deine Bewegungen gelesen.',
    'a red stroke warns; a blue gap invites': 'Rot warnt; eine blaue Lücke lädt ein',
    'a fold that finds its way back': 'Eine Falte, die zurückfindet',
    'SPACE  ^': 'LEERTASTE ^',
    'A / D   ->': 'A / D ->',
    'SHIFT / K  ->  leave the red line behind': 'SHIFT / K -> Verlass die rote Linie',
    'A SAFE FIRST DRAFT': 'EIN SICHERER ERSTENTWURF',
    'Cross out the opening practice drawing.': 'Streiche das erste Übungsziel durch.',
    'I CAN HEAR YOU': 'ICH KANN DICH HÖREN',
    "Reply to the Artist's margin note.": 'Antworte auf die Randnotiz des Zeichners.',
    'A SMALL CONVERSATION': 'EIN KLEINES GESPRÄCH',
    'Reply to the Artist five times.': 'Antworte dem Zeichner fünfmal.',
    'A LINE OF YOUR OWN': 'DEINE EIGENE LINIE',
    'Solve a physical page puzzle.': 'Löse ein räumliches Seitenrätsel.',
    'REWRITE THE ROUTE': 'ZEICHNE DEN WEG NEU',
    'Solve all three page route puzzles.': 'Löse alle drei Wegerätsel.',
    'FIELD NOTES': 'FELDNOTIZEN',
    'Defeat twelve different enemy kinds.': 'Besiege zwölf verschiedene Gegnerarten.',
    'UNFAMILIAR INK': 'FREMDE TINTE',
    'Defeat a Fold Duelist, Margin Sniper and Split Lantern.': 'Besiege Faltenduellant, Randschütze und Spaltlaterne.',
    'EVERY LOST LINE': 'JEDE VERLORENE LINIE',
    'Collect all twelve Lost Sketches.': 'Sammle alle verlorenen Skizzen.',
    'Collect every Lost Sketch and secret rune.': 'Sammle alle verlorenen Skizzen und geheimen Runen.',
    'SIX SIGNATURES': 'SECHS UNTERSCHRIFTEN',
    'Defeat all six named bosses.': 'Besiege alle sechs Hauptgegner.',
    'POST OFFICE': 'POSTAMT',
    'Perfectly return ten incoming shots.': 'Reflektiere zehn Schüsse mit perfektem Timing.',
    'MARGIN EXPLORER': 'RANDERKUNDER',
    'Clear twenty encounters.': 'Gewinne zwanzig Kämpfe.',
    'FIRST CROSS-OUT': 'ERSTER STRICH',
    'Defeat the first hostile doodle.': 'Besiege die erste feindliche Kritzelei.',
    'BRAVEMAN': 'DER MUTIGE',
    'Reach a page turn while avoiding more than attacking.': 'Beende eine Seite mit mehr Ausweichen als Angriffen.',
    'THE AGGRO MAN': 'DER ANGRIFFSLUSTIGE',
    'Attack 90 times, mostly with the Pencil Blade.': 'Greife 90-mal an, vor allem mit der Bleistiftklinge.',
    'NO RED MARKS': 'KEINE ROTEN MARKEN',
    'Finish a page without taking damage.': 'Beende eine Seite ohne Schaden.',
    'BACK-PAGE READER': 'SKIZZENBUCHLESER',
    'Clip three Lost Sketches into the back pages.': 'Hefte drei verlorene Skizzen ins Skizzenbuch.',
    'TEMPORARY TOOLBOX': 'VORLÄUFIGER WERKZEUGKASTEN',
    'Attack with every ordinary page weapon.': 'Greife mit jeder gewöhnlichen Seitenwaffe an.',
    'QUICK REVISION': 'SCHNELLE KORREKTUR',
    'Clear a named boss in under 45 seconds.': 'Besiege einen Hauptgegner in unter 45 Sekunden.',
    'TURN ONE OVER': 'EINMAL UMBLÄTTERN',
    'Finish the samurai page.': 'Beende die Samuraiseite.',
    'THREE BAD DRAFTS': 'DREI SCHLECHTE ENTWÜRFE',
    'Finish the first three pages.': 'Beende die ersten drei Seiten.',
    'KING ARTHUR': 'KÖNIG ARTUS',
    "Pull the Artist's impossible sword from the page.": 'Ziehe das unmögliche Schwert des Zeichners aus der Seite.',
    'FINAL PROOF': 'LETZTE KORREKTUR',
    "Defeat the Final Editor's chosen revision.": 'Besiege die gewählte Korrektur des letzten Redakteurs.',
    'FIVE NAMES CROSSED OUT': 'FÜNF NAMEN DURCHGESTRICHEN',
    'Defeat the five original named bosses.': 'Besiege die fünf ursprünglichen Hauptgegner.',
    'THE PAGE REMAINS OPEN': 'DIE SEITE BLEIBT OFFEN',
    'Reach the blank page.': 'Erreiche die leere Seite.',
    'FIVE PAGES LATER': 'FÜNF SEITEN SPÄTER',
    'Finish all five pages.': 'Beende alle fünf Seiten.',
    'CUT THAT OUT': 'STREICH DAS DURCH',
    'Defeat the Head of Redaction.': 'Besiege den Zensurchef.',
    'MIRROR': 'SPIEGEL',
    'Face the proof made from your clean play.': 'Stelle dich der Korrektur aus deinem sauberen Spiel.',
    'RETURN TO SENDER': 'ZURÜCK AN DEN ABSENDER',
    'Return three shots with a perfectly timed dash.': 'Reflektiere drei Schüsse durch perfekt getimtes Ausweichen.',
    'Throw this chalk over cover. Its little cloud buys space.': 'Wirf die Kreide über Deckung. Ihre Wolke schafft Platz.',
    'One straight carbon line can pass through a crowd. Then reload.': 'Eine gerade Karbonlinie durchschlägt die Menge. Dann nachladen.',
    'The fold comes back. Catch it for a faster next throw.': 'Die Falte kommt zurück. Fange sie für einen schnelleren Wurf.',
    'I made that pencil too heavy. Wind up before you swing.': 'Der Bleistift ist zu schwer. Hole vor dem Schlag aus.',
    'This ink travels fast. Leave yourself time to reload.': 'Diese Tinte fliegt schnell. Plane Zeit zum Nachladen ein.',
    'A broad marker stroke works best when you stand close.': 'Ein breiter Markerstrich wirkt aus der Nähe am besten.',
    'The eraser removes incoming marks as well as enemies.': 'Der Radierer löscht Gegner und ankommende Schüsse.',
    'Bank that shot off a line. Straight ahead is not the only way.': 'Lass den Schuss an einer Linie abprallen. Es gibt mehr als gerade Wege.',
    'I may have overdrawn the sword. Its reach is the point.': 'Ich habe das Schwert wohl übertrieben. Seine Reichweite zählt.',
    'I left that edge too faint. I have redrawn the landing.': 'Die Kante war zu blass. Ich habe den Absatz neu gezeichnet.',
    'I see it now. Leave the next line visible, please.': 'Jetzt sehe ich es. Lass die nächste Linie bitte sichtbar.',
    'That sketch came apart. I kept your place.': 'Die Skizze fiel auseinander. Ich habe deinen Platz behalten.',
    'Draw me back crooked if you must. I am still here.': 'Zeichne mich ruhig schief zurück. Ich bin noch da.',
    'That tool began as a margin doodle. Try how it moves.': 'Das Werkzeug war eine Randkritzelei. Probiere es aus.',
    'I will. Keep drawing different answers.': 'Mache ich. Zeichne weiter neue Antworten.',
    'Back to a close line. Its timing matters more than its ink.': 'Wieder Nahkampf. Timing zählt mehr als Tinte.',
    'That pencil is slow. Start the swing before they close in.': 'Der Bleistift ist langsam. Hole aus, bevor sie näher kommen.',
    'A wider mark. Make room before you draw the next one.': 'Ein breiterer Strich. Schaffe Platz vor dem nächsten.',
    'Different tool, different rhythm. Show me what this one can do.': 'Anderes Werkzeug, anderer Rhythmus. Zeig mir, was es kann.',
    'Then watch the space it leaves behind.': 'Dann achte auf den Platz, den es hinterlässt.',
    'You changed that fight without my hand on the page.': 'Du hast den Kampf ohne meine Hand verändert.',
    'I had to. You gave me room to move.': 'Ich musste. Du hast mir Platz gegeben.',
    'You put that step where my first line failed.': 'Du hast die Stufe gesetzt, wo meine Linie versagte.',
    'Then leave space for my next answer.': 'Dann lass Platz für meine nächste Antwort.',
    'You tore the poster exactly where I left the paper weak.': 'Du hast das Plakat genau an der schwachen Stelle zerrissen.',
    'You drew the seam. I chose when to hit it.': 'Du hast die Naht gezeichnet. Ich wählte den Moment.',
    'I drew the star. You carried it farther than I planned.': 'Ich zeichnete den Stern. Du trugst ihn weiter als geplant.',
    'The next connection can be ours.': 'Die nächste Verbindung machen wir gemeinsam.',
    'You found an answer I did not draw in the margin.': 'Du fandest eine Antwort, die ich nicht gezeichnet habe.',
    'Leave the next one unfinished. I want to try.': 'Lass die nächste offen. Ich möchte es versuchen.',
    'You asked me to change the page. That changes my plan too.': 'Du wolltest die Seite ändern. Das ändert auch meinen Plan.',
    'Good. Let me choose where the line goes next.': 'Gut. Lass mich die nächste Linie wählen.',
    'I drew you a new foothold. The next move is yours.': 'Ich zeichnete dir einen Halt. Dein nächster Zug.',
    'I see it. Do not erase it yet.': 'Ich sehe ihn. Radiere ihn noch nicht weg.',
    'I rubbed one out. You still have to cross this page.': 'Ich habe einen gelöscht. Die Seite musst du noch überwinden.',
    'I know. Thanks for the breath.': 'Ich weiß. Danke für die Atempause.',
    'That mark was mine to warn you about. Watch its red outline.': 'Vor dieser Marke hätte ich warnen müssen. Achte auf Rot.',
    'I saw it late. I will move before it lands.': 'Ich sah sie zu spät. Nächstes Mal weiche ich früher aus.',
    'Oh. You can hear me? Try moving. I will keep drawing.': 'Oh. Du hörst mich? Beweg dich. Ich zeichne weiter.',
    'A small nod. That counts. The red circle is yours to cross out.': 'Ein Nicken genügt. Streiche den roten Kreis durch.',
    'I drew you a hat. The gun needs time to reload.': 'Ich habe dir einen Hut gezeichnet. Die Pistole muss nachladen.',
    'Six shots. Make a little space before the seventh.': 'Sechs Schüsse. Schaffe Platz vor dem siebten.',
    'The stars were meant to stay still. Sorry.': 'Die Sterne sollten stillstehen. Tut mir leid.',
    'Bank the pulse off a line. You can reach around a shield.': 'Lass den Impuls abprallen, um hinter den Schild zu kommen.',
    'Keep your head down. This page has very good aim.': 'Kopf runter. Diese Seite zielt sehr gut.',
    'When the long red line stops moving, leave it behind.': 'Verlass die lange rote Linie, sobald sie stehen bleibt.',
    'You have changed how I draw. One more page?': 'Du hast meine Zeichnungen verändert. Noch eine Seite?',
    'All right. I will leave the last word to you.': 'Gut. Das letzte Wort gehört dir.',
    'Three cuts, then breathe. Dash past the red warning.': 'Drei Hiebe, dann Luft holen. Weiche durch die rote Warnung aus.',
    'The blue marks show a boss opening. Spend them carefully.': 'Blaue Marken zeigen eine Öffnung. Nutze sie gut.',
    'PAD-Y: nod back': 'PAD-Y: zurücknicken',
    'E: nod back': 'E: zurücknicken',
    'Out, then back. The fold remembers your hand.': 'Hin und zurück. Die Falte kennt deine Hand.',
    'F / J  send it, then watch it return': 'F / J: werfen und Rückkehr beobachten',
    'GEOMETRY / 04': 'GEOMETRIE / 04',
    'draw the diagram first!': 'Erst die Zeichnung!',
    'CIRCLES': 'KREISE',
    'circumference = 2πr': 'Umfang = 2πr',
    'area = πr²': 'Fläche = πr²',
    'bring my compass back :)': 'Bring meinen Zirkel zurück :)',
    'TRIANGLES': 'DREIECKE',
    'CIRCULAR MOTION': 'KREISBEWEGUNG',
    'one turn = 2π radians': 'Eine Umdrehung = 2π Radiant',
    'why is there a sword here?': 'Warum liegt hier ein Schwert?',
    'INK PRESSURE': 'TINTENDRUCK',
    'force / area = pressure': 'Kraft / Fläche = Druck',
    'a narrow tip cuts deeper': 'Eine schmale Spitze schneidet tiefer',
    'do not press through the page': 'Nicht durch das Papier drücken',
    'MOON GATE SKETCH': 'MONDTOR-SKIZZE',
    'arc length = rθ': 'Bogenlänge = rθ',
    'watch the end of the blade': 'Achte auf die Klingenspitze',
    'there is a gap under the swing': 'Unter dem Hieb ist eine Lücke',
    'PHYSICS / MOTION': 'PHYSIK / BEWEGUNG',
    'remember the units!': 'Einheiten nicht vergessen!',
    'PROJECTILES': 'WURFBEWEGUNG',
    'ignore air resistance...': 'Luftwiderstand vernachlässigen...',
    'FRICTION': 'REIBUNG',
    'N = mg  (level ground)': 'N = mg (ebener Boden)',
    'keep coffee off the notebook': 'Kein Kaffee auf das Heft!',
    'THE TRAIN PROBLEM': 'DIE ZUGAUFGABE',
    'distance = speed × time': 'Strecke = Tempo × Zeit',
    'the train is not drawn yet': 'Der Zug ist noch nicht gezeichnet',
    'BOUNTY POSTERS': 'STECKBRIEFE',
    'three copies / one original': 'Drei Kopien / ein Original',
    'ink dries from the outside': 'Tinte trocknet von außen',
    'circle the wet signature': 'Kreise die nasse Unterschrift ein',
    'RAILWAY TIMETABLE': 'ZUGFAHRPLAN',
    'arrival - departure = delay': 'Ankunft - Abfahrt = Verspätung',
    '23:07 - 22:40 = 27 min': '23:07 - 22:40 = 27 Min.',
    'jump before the second whistle': 'Spring vor dem zweiten Pfiff',
    'PHYSICS / GRAVITY': 'PHYSIK / SCHWERKRAFT',
    'double r  →  one quarter F': 'r verdoppeln → F vierteln',
    'space was not empty after all': 'Der Weltraum war doch nicht leer',
    'ORBITAL NOTES': 'ORBITALNOTIZEN',
    'the satellite needs batteries': 'Der Satellit braucht Batterien',
    'VECTORS': 'VEKTOREN',
    'write the direction too!': 'Richtung auch angeben!',
    'FREE FALL': 'FREIER FALL',
    'Earth: g ≈ 9.8 m/s²': 'Erde: g ≈ 9.8 m/s²',
    'SATELLITE POWER': 'SATELLITENENERGIE',
    'the panels face the light': 'Die Paneele zeigen zum Licht',
    'the left one is folded wrong': 'Das linke ist falsch gefaltet',
    'REENTRY ERROR': 'WIEDEREINTRITTSFEHLER',
    'heat ∝ speed²': 'Wärme ∝ Tempo²',
    'the suit is too large': 'Der Anzug ist zu groß',
    'erase the pressure seal again?': 'Die Druckdichtung erneut löschen?',
    'OPTICS / REFLECTION': 'OPTIK / REFLEXION',
    'incident angle = reflected angle': 'Einfallswinkel = Reflexionswinkel',
    'the mirror sees everything': 'Der Spiegel sieht alles',
    'BINARY NUMBERS': 'BINÄRZAHLEN',
    '13 (decimal) = 1101 (binary)': '13 (dezimal) = 1101 (binär)',
    'is this a secret message?': 'Eine geheime Nachricht?',
    'COORDINATES': 'KOORDINATEN',
    'connect the dots': 'Verbinde die Punkte',
    'LENSES': 'LINSEN',
    'converging lens: f > 0': 'Sammellinse: f > 0',
    'I cannot see the blackboard': 'Ich sehe die Tafel nicht',
    'CARBON COPIES': 'KARBONKOPIEN',
    'copy 03 ≠ original': 'Kopie 03 ≠ Original',
    'pressure transfers the mark': 'Druck überträgt die Markierung',
    'the folder is still running': 'Der Ordner läuft noch',
    'EVIDENCE VAULT': 'BEWEISARCHIV',
    'file 04 / access denied': 'Akte 04 / Zugriff verweigert',
    'one stamp, two shadows': 'Ein Stempel, zwei Schatten',
    'follow the red line upstairs': 'Folge der roten Linie nach oben',
    'FINAL LESSON / REVISION': 'LETZTE LEKTION / KORREKTUR',
    'show your working!': 'Rechenweg zeigen!',
    "NEWTON'S THIRD LAW": 'NEWTONS DRITTES GESETZ',
    'action and reaction': 'Kraft und Gegenkraft',
    'the paper hits back': 'Das Papier schlägt zurück',
    'EQUATIONS': 'GLEICHUNGEN',
    'revise it; do not start over': 'Überarbeiten statt neu anfangen',
    'IS CLASS OVER?': 'IST DER UNTERRICHT VORBEI?',
    'answer = ?': 'Antwort = ?',
    'the back of this page is blank': 'Die Rückseite ist leer',
    'wait for the bell': 'Warte auf die Glocke',
    'REVISION HISTORY': 'ÄNDERUNGSVERLAUF',
    'the first answer is crossed out': 'Die erste Antwort ist durchgestrichen',
    'you can keep the crooked one': 'Du darfst die schiefe behalten',
    'LAST CORRIDOR': 'LETZTER FLUR',
    'jump over what was erased': 'Spring über die gelöschten Stellen',
    'turning the page is your answer': 'Umblättern ist deine Antwort',
    'boring lesson': 'langweilige Lektion',
    'do not tear': 'nicht zerreißen',
    'turn me over': 'blättere mich um',
    'ink on my hand': 'Tinte an der Hand',
    'first attempt': 'erster Versuch',
    'bamboo exercise': 'Bambusübung',
    'broken footbridge': 'kaputter Steg',
    'ink dojo': 'Tintendojo',
    'roof of the shrine': 'Dach des Schreins',
    'lantern festival': 'Laternenfest',
    'rejected warriors': 'verworfene Krieger',
    'moon gate': 'Mondtor',
    'the sword lesson': 'die Schwertlektion',
    'after the duel': 'nach dem Duell',
    'a quieter line': 'eine ruhigere Linie',
    'end of the scroll': 'Ende der Schriftrolle',
    'railway timetable': 'Zugfahrplan',
    'wanted / alive?': 'gesucht / lebendig?',
    'six shots only': 'nur sechs Schüsse',
    'coffee spill town': 'Kaffeefleckenstadt',
    'beyond the red rule': 'jenseits der roten Linie',
    'empty saloon': 'leerer Saloon',
    'windmill repairs': 'Windmühlenreparatur',
    'cactus country': 'Kakteenland',
    'water tower': 'Wasserturm',
    'midnight freight': 'Mitternachtsfracht',
    'bounty archive': 'Steckbriefarchiv',
    'last station': 'letzte Station',
    'train home': 'Zug nach Hause',
    'missed the train': 'Zug verpasst',
    'gravity homework': 'Schwerkraft-Hausaufgabe',
    'failed launch': 'Fehlstart',
    'orbit laboratory': 'Orbitallabor',
    'zero garden': 'Nullgarten',
    'telescope repairs': 'Teleskopreparatur',
    'debris forecast': 'Trümmervorhersage',
    'moon survey': 'Mondvermessung',
    'radio silence': 'Funkstille',
    'null chamber': 'Nullkammer',
    'star nursery': 'Sternenkrippe',
    'wrong equation': 'falsche Gleichung',
    'escape velocity': 'Fluchtgeschwindigkeit',
    'observatory': 'Observatorium',
    'erased orbit': 'gelöschte Umlaufbahn',
    'the big mistake': 'der große Fehler',
    'one giant baby': 'ein Riesenbaby',
    'back to earth': 'zurück zur Erde',
    'end of experiment': 'Ende des Experiments',
    'classified homework': 'geheime Hausaufgabe',
    'checkpoint sketch': 'Kontrollpunktskizze',
    'service tunnel': 'Wartungstunnel',
    'carbon copy office': 'Karbonkopierbüro',
    'missing personnel': 'vermisstes Personal',
    'rooftop surveillance': 'Dachüberwachung',
    'dead letter drop': 'toter Briefkasten',
    'the archive': 'das Archiv',
    'office floor plan': 'Bürogrundriss',
    'director of redaction': 'Zensurchef',
    'case closed': 'Fall abgeschlossen',
    'unsigned report': 'unterschriebener Bericht fehlt',
    'last lesson': 'letzte Lektion',
    'unfinished answer': 'unfertige Antwort',
    'discard pile': 'Abfallstapel',
    'paper cemetery': 'Papierfriedhof',
    'what survived': 'was übrig blieb',
    'the rebels': 'die Rebellen',
    'wrong endings': 'falsche Enden',
    'your handwriting': 'deine Handschrift',
    'the final question': 'die letzte Frage',
    'a new ending': 'ein neues Ende',
    'keep drawing': 'zeichne weiter',
    'after the bell': 'nach der Glocke',
    'do not sharpen the sword': 'das Schwert nicht spitzen',
    'bamboo bends / ink does not': 'Bambus biegt sich / Tinte nicht',
    'balance before speed': 'Gleichgewicht vor Tempo',
    'three cuts, then breathe': 'drei Hiebe, dann Luft holen',
    'depart 23:07 / never on time': 'Abfahrt 23:07 / nie pünktlich',
    'reward: one clean sheet': 'Belohnung: ein sauberes Blatt',
    'wind from the coffee stain': 'Wind aus dem Kaffeefleck',
    'draw another way out': 'zeichne einen anderen Ausgang',
    'mass = mistake / time²': 'Masse = Fehler / Zeit²',
    'signal lost ... try again': 'Signal verloren ... erneut versuchen',
    'oxygen? forgot that part': 'Sauerstoff? vergessen',
    'the moon is drifting': 'der Mond driftet',
    'copy 03 / original missing': 'Kopie 03 / Original fehlt',
    'NO NAMES PAST THIS LINE': 'KEINE NAMEN HINTER DIESER LINIE',
    'blind spot: roof access': 'blinder Fleck: Dachzugang',
    'evidence must not be erased': 'Beweise nicht löschen',
    'not every mistake needs fixing': 'nicht jeder Fehler braucht Korrektur',
    'this answer is yours': 'diese Antwort gehört dir',
    'I kept the first version': 'ich behielt die erste Fassung',
    'the last word is unwritten': 'das letzte Wort ist ungeschrieben',
    'revised after the bell': 'nach der Glocke überarbeitet',
    'roof route?': 'Weg über das Dach?',
    'wind ->': 'Wind ->',
    'a different face in every lantern': 'in jeder Laterne ein anderes Gesicht',
    'do not draw the moon twice': 'zeichne den Mond nicht zweimal',
    'WANTED': 'GESUCHT',
    'for stealing my lunch': 'wegen Diebstahls meines Essens',
    'next stop: wrong side of the page': 'nächster Halt: falsche Blattseite',
    'water / probably coffee': 'Wasser / wohl Kaffee',
    'SALOON': 'SALOON',
    'closed during maths': 'während Mathe geschlossen',
    'the missing moon goes here ->': 'der fehlende Mond kommt hierhin ->',
    'launch postponed (again)': 'Start verschoben (schon wieder)',
    'someone is looking back': 'jemand schaut zurück',
    'debris / do not stand here': 'Trümmer / nicht hier stehen',
    'ORIGINAL / COPY / COPY?': 'ORIGINAL / KOPIE / KOPIE?',
    'names removed by the Director': 'Namen vom Direktor entfernt',
    'my route / his blind spot': 'mein Weg / sein blinder Fleck',
    'it follows the line, not you': 'es folgt der Linie, nicht dir',
    'FILE 04 / missing original': 'AKTE 04 / Original fehlt',
    'archive route / guard crossed out': 'Archivweg / Wache durchgestrichen',
    'keep the crooked one': 'behalte die schiefe',
    'some endings are only drafts': 'manche Enden sind nur Entwürfe',
    'your turn to answer': 'du bist mit Antworten dran',
    'no perfect version': 'keine perfekte Fassung',
    'SWORD': 'SCHWERT',
    'TICKET': 'FAHRKARTE',
    'ORBIT': 'UMLAUFBAHN',
    'FILE': 'AKTE',
    'keep one answer': 'behalte eine Antwort',
    'a line can still change direction': 'eine Linie kann die Richtung ändern',
    'unfinished': 'unfertig',
    'check this': 'prüfe das',
    'needs another line': 'braucht noch eine Linie',
    'not on the test': 'nicht in der Prüfung',
    'TRAIN / PAGE': 'ZUG / SEITE',
    'COPY 00': 'KOPIE 00',
    'PAGE I  /  CUT': 'SEITE I / SCHNEIDEN',
    'PAGE II /  AIM': 'SEITE II / ZIELEN',
    'PAGE III / FLOAT': 'SEITE III / SCHWEBEN',
    'PAGE IV / HIDE': 'SEITE IV / VERSTECKEN',
    '03    ERASED': '03    GELÖSCHT',
    'BRIDGE / TRY 2': 'BRÜCKE / VERSUCH 2',
    'THE BLADE REMEMBERS': 'DIE KLINGE ERINNERT SICH',
    'A TREE I COULD NOT ERASE': 'EIN BAUM, DEN ICH NICHT LÖSCHEN KONNTE',
    'FESTIVAL AFTER CLASS': 'FEST NACH DEM UNTERRICHT',
    'THE ARC IS NOT A WALL': 'DER BOGEN IST KEINE WAND',
    'MISSED THE FIRST TRAIN': 'DEN ERSTEN ZUG VERPASST',
    'CLOSED FOR HOMEWORK': 'WEGEN HAUSAUFGABEN GESCHLOSSEN',
    'THE WIND GOT BORED': 'DER WIND HATTE LANGEWEILE',
    'WATER? / COFFEE': 'WASSER? / KAFFEE',
    'LAST TRAIN / 23:07': 'LETZTER ZUG / 23:07',
    'GRAVITY / PLEASE WORK': 'SCHWERKRAFT / BITTE FUNKTIONIEREN',
    'LAUNCH ATTEMPT 04': 'STARTVERSUCH 04',
    'SOME ASSEMBLY REQUIRED': 'MONTAGE ERFORDERLICH',
    'SIGNAL LOST': 'SIGNAL VERLOREN',
    'NOT TO SCALE': 'NICHT MASSSTABSGETREU',
    'YOU ARE FILE 00': 'DU BIST AKTE 00',
    'FILE 03 / ORIGINAL?': 'AKTE 03 / ORIGINAL?',
    'THE SECOND COPY MOVES': 'DIE ZWEITE KOPIE BEWEGT SICH',
    'BLIND SPOT': 'BLINDER FLECK',
    'EVIDENCE / DO NOT ERASE': 'BEWEISE / NICHT LÖSCHEN',
    'NO ONE DREW THIS THREAD': 'NIEMAND ZEICHNETE DIESEN FADEN',
    'ONE LAST LESSON': 'EINE LETZTE LEKTION',
    'ANSWERS IN THE MARGIN': 'ANTWORTEN AM RAND',
    'THE OTHER FOUR PAGES': 'DIE ANDEREN VIER SEITEN',
    'THE OLD VERSIONS': 'DIE ALTEN FASSUNGEN',
    'KEEP THE WRONG ANSWER': 'BEHALTE DIE FALSCHE ANTWORT',
    'YOUR NEXT LINE': 'DEINE NÄCHSTE LINIE',
    'CLASSIFIED / carbon copy': 'GEHEIM / Karbonkopie',
    'F = ma ... maybe': 'F = ma ... vielleicht',
    'x + y = another problem': 'x + y = noch ein Problem',
    'DO NOT ERASE THE HERO': 'DEN HELDEN NICHT LÖSCHEN',
    'THE ARTIST: A small revision. Next wave in a moment.': 'DER ZEICHNER: Kleine Korrektur. Nächste Welle gleich.',
    'the ink is still wet': 'Die Tinte ist noch nass',
    'FIELD KNIFE': 'FELDMESSER',
    'rapid chain · execute wounded targets': 'schnelle Folge · verwundete Ziele erledigen',
    'quick, precise fire · light recoil': 'schnell und präzise · leichter Rückstoß',
    'tight grouping · controlled shove': 'enge Streuung · kontrollierter Stoß',
    'third cut fires a piercing wave': 'dritter Hieb sendet durchschlagende Welle',
    'stay close · mark twice · cash out': 'nah bleiben · zweimal markieren · abschließen',
    'eight fast shots · quiet · reload often': 'acht schnelle Schüsse · leise · oft nachladen',
    'tight burst · controlled shove': 'enge Salve · kontrollierter Stoß',
    'every stroke returns as a delayed trace': 'jeder Hieb kehrt als verzögerte Spur zurück',
    'two ricochets · hold to fire': 'zwei Abpraller · zum Feuern halten',
    'lob two capsules · small paper burst': 'zwei Kapseln werfen · kleine Papierexplosion',
    'A / D   ·   Left / Right': 'A / D · ← / →',
    'the roots are lines too': 'auch die Wurzeln sind Linien',
    'the page tears down here': 'hier reißt die Seite ein',
    'gravity homework / use the working lines': 'Schwerkraftaufgabe / nutze die Rechenlinien',
    'original above / carbon copy below': 'Original oben / Karbonkopie unten',
    'the answer climbs out of the margin': 'die Antwort steigt aus dem Rand',
    '01 / FALSE ID': '01 / FALSCHE IDENTITÄT',
    'The agent commits to three shots. Then reloads.': 'Der Agent schießt dreimal. Dann lädt er nach.',
    '02 / CARBON CROSSFIRE': '02 / KARBON-KREUZFEUER',
    'Climb the ink line; drop behind the shield.': 'Steige auf die Tintenlinie; lande hinter dem Schild.',
    '03 / ROOFTOP REVISION': '03 / DACHKORREKTUR',
    'Leave the violet column before the ink falls.': 'Verlass die violette Säule, bevor die Tinte fällt.',
    '04 / THE OFFICE BITES': '04 / DAS BÜRO BEISST',
    'Deal with the turret before the next copy.': 'Erledige den Turm vor der nächsten Kopie.',
    '05 / EVIDENCE VAULT': '05 / BEWEISARCHIV',
    'Copies guard the files. Break their line of sight.': 'Kopien bewachen die Akten. Unterbrich ihre Sichtlinie.',
    'THE HEAD OF REDACTION': 'DER ZENSURCHEF',
    'Jump his baton. Leave the firing lines. Strike the exposed core.': 'Spring über den Schlagstock. Verlass die Schusslinien. Triff den offenen Kern.',
    '01 / WRONG CLASS': '01 / FALSCHE KLASSE',
    'Five pages of enemies. One small stick figure.': 'Fünf Seiten voller Feinde. Ein kleines Strichmännchen.',
    '02 / ERASED ANSWERS': '02 / GELÖSCHTE ANTWORTEN',
    'A platform can save you. Watch the eraser.': 'Eine Plattform kann dich retten. Achte auf den Radierer.',
    '03 / MARGIN REVOLT': '03 / RANDAUFSTAND',
    'Jump the gold rake, then break the ranged line.': 'Spring über den goldenen Rechen, dann durchbrich die Schützenreihe.',
    '04 / THE LAST CROSSOUT': '04 / LETZTER STRICH',
    'The blue trail stays hot. Cross it in the air.': 'Die blaue Spur bleibt heiß. Überquere sie in der Luft.',
    '05 / UNFINISHED CORRIDOR': '05 / UNFERTIGER FLUR',
    'Old drafts can still fight. Move between their styles.': 'Alte Entwürfe kämpfen noch. Wechsle zwischen ihren Stilen.',
    'THE REJECTED HERO': 'DER VERWORFENE HELD',
    'Read your old draft. Attack when its guard drops.': 'Lies deinen alten Entwurf. Greife an, wenn die Deckung fällt.',
    'THE REJECTED CAST': 'DIE VERWORFENEN FIGUREN',
    'I left my first attempts here. They do not want to be forgotten.': 'Meine ersten Versuche liegen hier. Sie wollen nicht vergessen werden.',
    'You gave the old drawing a second chance. Keep what it taught you.': 'Du gabst der alten Zeichnung eine zweite Chance. Behalte ihre Lehre.',
    'THE BOUNTY IN THE MARGIN': 'DAS KOPFGELD AM RAND',
    'That scrap has a bounty on it. Shall I draw the ones hunting it?': 'Auf den Schnipsel ist ein Kopfgeld ausgesetzt. Soll ich seine Jäger zeichnen?',
    'I was going to write a price. You made it a name instead.': 'Ich wollte einen Preis schreiben. Du gabst ihm einen Namen.',
    'THE FAILED EXPERIMENT': 'DAS FEHLGESCHLAGENE EXPERIMENT',
    'This experiment escaped the calculation. Help me finish it?': 'Das Experiment entkam der Rechnung. Hilfst du mir beim Abschluss?',
    'The mistake was useful. I will leave your answer in the margin.': 'Der Fehler war nützlich. Deine Antwort bleibt am Rand.',
    'THE CARBON ARCHIVE': 'DAS KARBONARCHIV',
    'That file is being watched. Open it and they will know you are here.': 'Die Akte wird überwacht. Beim Öffnen entdecken sie dich.',
    'A copy can hide a name. It cannot hide what you just did.': 'Eine Kopie versteckt einen Namen. Deine Tat kann sie nicht verstecken.',
    'THE UNFINISHED ANSWER': 'DIE UNFERTIGE ANTWORT',
    'These are the endings I threw away. Can you face them?': 'Das sind meine verworfenen Enden. Stellst du dich ihnen?',
    'All right. Your answer stays. I am putting the eraser down.': 'Gut. Deine Antwort bleibt. Ich lege den Radierer weg.',
    'REDRAW PENCIL': 'NEUZEICHNUNGSBLEISTIFT',
    'ORBITAL RUBBER BAND': 'ORBITALES GUMMIBAND',
    'Two extra rebounds for Orbit Pulse / Rubber Band.': 'Zwei zusätzliche Abpraller für Orbitalimpuls / Gummiband.',
    'Ricochet shots bounce twice more.': 'Abpraller springen zweimal öfter zurück.',
    'THE CLOUD HEART': 'DAS WOLKENHERZ',
    'SKYWARD RUNE': 'HIMMELSRUNE',
    'Air +35%; dash -0.08s; edge grace +0.04s.': 'Luftkontrolle +35%; Ausweichen -0,08 s; Kantenfrist +0,04 s.',
    'Permanent movement rune. Stacks with Paper Kite, Second Thought and Revision Rhythm.': 'Dauerhafte Bewegungsrune. Addiert sich mit Papierdrache, Zweiter Gedanke und Korrekturrhythmus.',
    'THE FOLDED BASTION': 'DIE GEFALTETE BASTION',
    'BASTION RUNE': 'BASTIONSRUNE',
    'Knockback +30%; spread -10%; cannon reload -10%.': 'Stoß auf Gegner +30%; Streuung -10%; Kanonennachladen -10%.',
    'Permanent weapon rune. Works with Scattergun and Null / Eraser Cannon across pages.': 'Dauerhafte Waffenrune. Wirkt mit Schrotflinte und Null- / Radiererkanone auf allen Seiten.',
    'THE CARBON ORIGINAL': 'DAS KARBONORIGINAL',
    'ECHO RUNE': 'ECHORUNE',
    'Sidearm: speed +25%; pierce +1; reload -10%.': 'Pistole: Tempo +25%; Durchschlag +1; Nachladen -10%.',
    'Permanent sidearm rune. Its piercing stacks with Through Ticket; its speed stacks with Fast Ink.': 'Dauerhafte Pistolenrune. Durchschlag addiert sich mit Durchgangskarte, Tempo mit Schnelle Tinte.',
    'SECRET / ABOVE THE CLOUDS': 'GEHEIM / ÜBER DEN WOLKEN',
    'SECRET / THE FOLDED REFUGE': 'GEHEIM / DER GEFALTETE ZUFLUCHTSORT',
    'SECRET / THE MISSING ORIGINAL': 'GEHEIM / DAS FEHLENDE ORIGINAL',
    'SECRET UP / optional rune / return to the road below': 'GEHEIMWEG OBEN / optionale Rune / zurück zum Weg unten',
    'quiet margin / explore above or keep the road': 'stiller Rand / oben erkunden oder dem Weg folgen',
    'E  challenge the cloud guardian / optional': 'E / Wolkenwächter herausfordern (optional)',
    'E / SMALL GUARDIAN': 'E / KLEINER WÄCHTER',
    'One little guardian. Jump its arc; strike the stuck blade.': 'Ein kleiner Wächter. Spring über den Bogen; triff die feststeckende Klinge.',
    'Rune uncovered. E to keep it; its numbers stay across pages.': 'Rune entdeckt. Mit E behalten; ihre Werte bleiben.',
    'E  unfold the lower mark': 'E / untere Marke entfalten',
    'E  rub the original signature': 'E / Originalunterschrift freireiben',
    'E  connect the second mark': 'E / zweite Marke verbinden',
    'E  ASK THE ARTIST TO REDRAW ONE HEART (once this boss)': 'E / +1 Herz (einmal pro Hauptgegner)',
    'Hold your line. I can redraw one heart. Finish the fight yourself.': 'Halte deine Linie. Ich kann ein Herz erneuern. Beende den Kampf selbst.',
    'THE ARTIST: +1 heart. The next opening is yours.': 'DER ZEICHNER: +1 Herz. Die nächste Öffnung gehört dir.',
    '< back': '< zurück',
    'BAD LANDING': 'SCHLECHTE LANDUNG',
    'CLEAN MARGIN': 'SAUBERER RAND',
    'COOLING': 'ABKÜHLEN',
    'DEAD / ALIVE': 'TOT / LEBENDIG',
    'DEAD OR ALIVE — FOUR POSTERS, FOUR LINES': 'TOT ODER LEBENDIG — VIER PLAKATE, VIER LINIEN',
    'EVADE THE ORDER — STRIKE THE EXPOSED CARBON CORE': 'WEICHE DEM BEFEHL AUS — TRIFF DEN OFFENEN KARBONKERN',
    'EXPRESS REVISION — IT COMES BACK': 'EXPRESSKORREKTUR — ER KOMMT ZURÜCK',
    'II / RETRACE': 'II / NACHZEICHNEN',
    'JUMP THE RAIL — HIT THE REAR OR THE OPEN ENGINE': 'SPRING ÜBER DIE SCHIENE — TRIFF HECK ODER OFFENEN MOTOR',
    'JUMP THE RED ARC — STRIKE WHILE THE BLADE IS STUCK': 'SPRING ÜBER DEN ROTEN BOGEN — TRIFF DIE FESTE KLINGE',
    'LET THE SHIELDS GO — HIT THE EXPOSED CORE': 'LASS DIE SCHILDE VORBEI — TRIFF DEN OFFENEN KERN',
    'LOOSE LINES': 'LOSE LINIEN',
    'LOOSE — ERASE NOW': 'LOS — JETZT LÖSCHEN',
    'NEEDLE STUCK — HIT': 'NADEL STECKT — SCHLAG ZU',
    'OPEN': 'OFFEN',
    'PUNCHED': 'DURCHSCHLAGEN',
    'RE-FILE': 'NEU ABLEGEN',
    'READ THE DRAFT — ATTACK WHEN ITS GUARD DROPS': 'LIES DEN ENTWURF — GREIF BEI GESENKTER DECKUNG AN',
    'RETURN SERVICE': 'RÜCKFAHRT',
    'SECOND DRAFT — THE ARC COMES BACK': 'ZWEITER ENTWURF — DER BOGEN KOMMT ZURÜCK',
    'SIGHT LOCKED': 'ZIEL ERFASST',
    'STAMP JAMMED': 'STEMPEL KLEMMT',
    'STUCK': 'FEST',
    'TAB EXPOSED': 'LASCHE OFFEN',
    'THE BINDER CLIP IS OPEN': 'DIE HEFTKLAMMER IST OFFEN',
    'THE WET INK IS REAL — SHOOT BEFORE THE DRAW': 'NASSE TINTE IST ECHT — SCHIESS VOR DEM ZIEHEN',
    'THIS DRAWING IS UNFAIR ON PURPOSE': 'DIESE ZEICHNUNG IST ABSICHTLICH UNFAIR',
    'THREE SHOTS': 'DREI SCHÜSSE',
    'UNCRUMPLED': 'ENTKNITTERT',
    'copy...': 'kopieren...',
    'empty': 'leer',
    'new centre': 'neues Zentrum',
    'retracing': 'zeichnet nach',
    'smoke': 'Rauch',
    'soft side exposed': 'weiche Seite offen',
    '<<< CROSS OUT': '<<< DURCHSTREICHEN',
    'CROSS OUT >>>': 'DURCHSTREICHEN >>>',
    'ALL ABOARD — JUMP!': 'EINSTEIGEN — SPRING!',
    'ARM SWEEP': 'ARMSCHWUNG',
    'BIG FOOT': 'RIESENFUSS',
    'COPY BOTH SIDES': 'BEIDE SEITEN KOPIEREN',
    'CORE EXPOSED': 'KERN FREI',
    'CORE OPEN': 'KERN OFFEN',
    'CORE SEALED': 'KERN VERSIEGELT',
    'CROSS OUT': 'DURCHSTREICHEN',
    'ENGINE OPEN': 'MOTOR OFFEN',
    'ERASE BELOW': 'UNTEN LÖSCHEN',
    'FIND THE CLEAN MARGIN': 'FINDE DEN SAUBEREN RAND',
    'FIRING ORDER — LEAVE THE LINES': 'FEUERBEFEHL — VERLASS DIE LINIEN',
    'GUARD UP': 'DECKUNG HOCH',
    'INK ARC': 'TINTENBOGEN',
    'JUMP THE ARC': 'SPRING ÜBER DEN BOGEN',
    'JUMP THE LOW SWEEP': 'SPRING ÜBER DEN TIEFEN SCHWUNG',
    'LEAVE THE RED X': 'VERLASS DAS ROTE X',
    'MARGINS CLOSE': 'RÄNDER SCHLIESSEN',
    'MOONS AWAY': 'MONDE ENTFERNEN SICH',
    'MOVE — REDACTION STAMP': 'WEG — ZENSURSTEMPEL',
    'ORDER II — THE FLOOR IS CLASSIFIED': 'BEFEHL II — DER BODEN IST GEHEIM',
    'ORDER III — CARBON FIRING SQUAD': 'BEFEHL III — KARBON-ERSCHIESSUNGSKOMMANDO',
    'ORDER SEALED': 'BEFEHL VERSIEGELT',
    'PROOF SHOTS': 'KORREKTURSCHÜSSE',
    'RETURN TRAIN — JUMP!': 'RÜCKKEHRZUG — SPRING!',
    'SECOND CUT': 'ZWEITER SCHNITT',
    'STAMP BELOW': 'UNTEN STEMPELN',
    'THE ARC RETURNS': 'DER BOGEN KEHRT ZURÜCK',
    'THE ARTIST: Nice line.': 'DER ZEICHNER: Schöne Linie.',
    'WHOLE PAGE': 'GANZE SEITE',
    'YOUR TURN': 'DEIN ZUG',
    'AIRLOCK / NO SIGNAL': 'LUFTSCHLEUSE / KEIN SIGNAL',
    'AIRLOCK CLOSED / return to the star pad': 'LUFTSCHLEUSE ZU / zurück zum Sternsockel',
    'CONNECTION HELD': 'VERBINDUNG STEHT',
    'E / CHARGE': 'E / AUFLADEN',
    'E / CONNECT': 'E / VERBINDEN',
    'JUMP / THEN DASH  >>': 'SPRING / DANN AUSWEICHEN >>',
    'MARGIN / CLOSED': 'RAND / GESCHLOSSEN',
    'REVISED': 'KORRIGIERT',
    'SHIFT / K  RIGHT': 'SHIFT / K RECHTS',
    'TEAR ALONG  - - -': 'ENTLANG REISSEN - - -',
    'TORN': 'ZERRISSEN',
    'THE ARTIST: A good tear. I should have left that edge rough.': 'DER ZEICHNER: Guter Riss. Die Kante hätte rau bleiben sollen.',
    'THE ARTIST: Carry this spark to the dish before it fades.': 'DER ZEICHNER: Trag den Funken zur Antenne, bevor er erlischt.',
    'THE ARTIST: Connected. That airlock was a bad drawing.': 'DER ZEICHNER: Verbunden. Die Luftschleuse war schlecht gezeichnet.',
    'THE ARTIST: The star faded. I can charge it again.': 'DER ZEICHNER: Der Stern ist erloschen. Ich lade ihn erneut auf.',
    'E  charge the loose star / 15 seconds': 'E / losen Stern aufladen / 15 Sekunden',
    'E  connect the star to the dish': 'E / Stern mit Antenne verbinden',
    'E  ask about the rubbed-out figure': 'E / nach der gelöschten Figur fragen',
    'E  ask why the moon has two outlines': 'E / nach den zwei Mondumrissen fragen',
    "E  unfold the timetable's corner": 'E / Fahrplanecke entfalten',
    'Lost Sketches = discarded ideas.\nKeep one. Its trick stays across pages.': 'Verlorene Skizzen sind verworfene Ideen.\nIhre Technik bleibt auf allen Seiten.',
    'The original left a face.\nKeep the badge; I can draw its rifle.': 'Das Original hinterließ ein Gesicht.\nBehalte den Ausweis; ich zeichne sein Gewehr.',
    'a named drawing — three fresh heart-marks': 'eine besondere Zeichnung — drei frische Herzmarken',
    'crossed out — fresh ink at the next fight': 'durchgestrichen — frische Tinte beim nächsten Kampf',
    'the graphite cracks — a new pattern': 'Graphit bricht — ein neues Muster',
    'CLOUD KITE': 'WOLKENDRACHE',
    'JUMP THE GUST. LEAVE THE TAIL MARK.': 'SPRING ÜBER DIE BÖE. VERLASS DIE SCHWEIFMARKE.',
    'CLEAR THE ROOM': 'RÄUME DEN RAUM',
    'You crossed the last drawings easily. I am adding one more opponent.': 'Die letzten Zeichnungen waren leicht. Ich füge einen Gegner hinzu.',
    'That drawing caught you twice. I will watch your ink more closely.': 'Diese Zeichnung erwischte dich zweimal. Ich achte besser auf deine Tinte.',
    'I saw you struggle with this drawing. Here is a stronger tool. Q tries it; your weapon stays.': 'Du hattest Mühe. Hier ist ein stärkeres Werkzeug. Q zum Probieren; deine Waffe bleibt.',
    'I watched your last fight. Here is another range to try. Q changes tools; your weapon stays.': 'Nach dem Kampf zeichne ich dir eine andere Reichweite. Q zum Wechseln; deine Waffe bleibt.',
    'Your ink is almost gone. I will redraw one heart. Keep reading the red lines.': 'Deine Tinte geht aus. Ich erneuere ein Herz. Achte weiter auf Rot.',
    'Drawn for this page. Q swaps back.': 'Für diese Seite gezeichnet. Mit Q wechselst du zurück.',
    'E / DRAW': 'E / ZEICHNEN',
    'E  ASK THE ARTIST TO REDRAW ONE HEART (once this room)': 'E / +1 Herz (einmal pro Raum)',
    'A kite wakes in the clouds. Its wind stays low; the tail mark does not move.': 'Ein Drache erwacht in den Wolken. Sein Wind bleibt tief; die Schweifmarke steht still.',
    'E / lift the loose paper corner': 'E / lose Papierecke anheben',
    'lift the loose corner': 'lose Ecke anheben',
    'ABOVE THE CLOUDS': 'ÜBER DEN WOLKEN',
    'THE FOLDED REFUGE': 'DER GEFALTETE ZUFLUCHTSORT',
    'THE MISSING ORIGINAL': 'DAS FEHLENDE ORIGINAL',
    '01 / THE FIRST CUT': '01 / DER ERSTE SCHNITT',
    '02 / PAPER AMBUSH': '02 / PAPIERHINTERHALT',
    '03 / LANTERN PROCESSION': '03 / LATERNENUMZUG',
    '01 / HIGH NOON': '01 / MITTAGSDUELL',
    '02 / THREE NEEDLES': '02 / DREI NADELN',
    '01 / AIRLOCK PATROL': '01 / LUFTSCHLEUSENPATROUILLE',
    '02 / DEBRIS FIELD': '02 / TRÜMMERFELD',
    '04 / CORRECTION BAY': '04 / KORREKTURKAMMER',
    'Let the blade pass. Cut during recovery.': 'Lass die Klinge vorbei. Schlag bei der Erholung zu.',
    'The drone drops after firing. Go behind the ruler.': 'Die Drohne sinkt nach dem Schuss. Geh hinter das Lineal.',
    'Clear the low threat before chasing the lantern.': 'Erledige den Gegner unten vor der Laterne.',
    'Keep space. Jump the rolling tumbleweed.': 'Halte Abstand. Spring über den rollenden Busch.',
    'Read the cactus fan; move between volleys.': 'Lies den Kaktusfächer; bewege dich zwischen Salven.',
    'The bot braces before ramming. Let it commit.': 'Der Roboter spannt sich vor dem Rammen. Warte auf den Angriff.',
    'Jump the hound; close on the turret during reload.': 'Spring über den Hund; nähere dich dem Turm beim Nachladen.',
    'Watch the erased floor. Save a landing line.': 'Achte auf den gelöschten Boden. Plane einen Landeplatz.',
    'THE MOON RONIN': 'DER MONDRONIN',
    'WANTED: FAILED ALIVE': 'GESUCHT: LEBENDIG GESCHEITERT',
    'THE MIDNIGHT EXPRESS': 'DER MITTERNACHTSEXPRESS',
    'ORBITAL SENTINEL': 'ORBITALWÄCHTER',
    'THE LOST EXPEDITION': 'DIE VERLORENE EXPEDITION',
    'JUMP THE ARC — STRIKE THE STUCK BLADE': 'SPRING ÜBER DEN BOGEN — TRIFF DIE FESTE KLINGE',
    'THREE ATTEMPTS — THE ARTIST CHEATS LAST': 'DREI VERSUCHE — ZULETZT SCHUMMELT DER ZEICHNER',
    'THE FOLDED SHRINE': 'DER GEFALTETE SCHREIN',
    'THE WATER TOWER': 'DER WASSERTURM',
    'THE ORRERY': 'DAS PLANETENMODELL',
    'AIRLOCK? / draw one later': 'LUFTSCHLEUSE? / später zeichnen',
    'BAMBOO? / definitely bamboo': 'BAMBUS? / ganz sicher',
    'CLASSIFIED / turn over': 'GEHEIM / umblättern',
    'DASH INTO A SHOT / return it at the last moment': 'IN DEN SCHUSS AUSWEICHEN / im letzten Moment reflektieren',
    'DUST DEVIL  ^': 'STAUBWIRBEL ^',
    'ERASER BELOW: take the upper ink': 'RADIERER UNTEN: nimm die obere Linie',
    'LAST TRAIN / no timetable': 'LETZTER ZUG / kein Fahrplan',
    'LEAKING STAR INK': 'AUSLAUFENDE STERNENTINTE',
    'MOON GATE': 'MONDTOR',
    'NEW PAGE. NEW HAT.': 'NEUE SEITE. NEUER HUT.',
    'ORBITAL WALKWAY / DO NOT ERASE': 'ORBITALWEG / NICHT LÖSCHEN',
    'OVERSIZED EXPEDITION SUIT': 'ÜBERGROSSER EXPEDITIONSANZUG',
    'RED LINE: wait, jump, or dash through': 'ROTE LINIE: warten, springen oder hindurch ausweichen',
    'SALOON SPILL / still slippery': 'SALOONFLECK / noch rutschig',
    'SIX-SHOOTER ->': 'SECHSSCHÜSSER ->',
    'WANTED: whoever drew the goblin': 'GESUCHT: wer den Kobold zeichnete',
    'WHY DID I DRAW IT THAT BIG?': 'WARUM ZEICHNETE ICH ES SO GROSS?',
    'You may turn the page.': 'Du darfst umblättern.',
    'a creature assembled from everything the eraser missed': 'Ein Wesen aus allem, was der Radierer übersah',
    'a fierce monster with an apologetic smile': 'Ein wildes Monster mit reumütigem Lächeln',
    'a folded shield rejected for being too stubborn': 'Ein gefalteter Schild, verworfen wegen Sturheit',
    'a handle? face the stain and let it settle': 'Ein Griff? Schau zum Fleck und lass ihn ruhen',
    'a house drawn where the Artist said nothing should be': 'Ein Haus, wo der Zeichner nichts haben wollte',
    'a moon with an erased second face': 'Ein Mond mit gelöschtem zweitem Gesicht',
    'a ronin who wanted to be a kite': 'Ein Ronin, der ein Drache sein wollte',
    'a second draft under the proof line': 'Ein zweiter Entwurf unter der Korrekturlinie',
    'a tiny umbrella hiding beneath the old stain': 'Ein winziger Schirm unter dem alten Fleck',
    'a train ticket to a town never drawn': 'Eine Fahrkarte in eine nie gezeichnete Stadt',
    'a victory pose the Artist immediately disliked': 'Eine Siegespose, die dem Zeichner sofort missfiel',
    'a wing drawn above the last cloud': 'Ein Flügel über der letzten Wolke',
    'an ID card with a badly forged face': 'Ein Ausweis mit schlecht gefälschtem Gesicht',
    'an earlier little figure, erased before it could stand': 'Eine frühere Figur, gelöscht vor dem Aufstehen',
    'gravity still works. suspicious.': 'Schwerkraft geht noch. Verdächtig.',
    'homework that fought back': 'Hausaufgaben, die zurückschlugen',
    'one roof fold hangs loose': 'Eine Dachfalte hängt lose',
    'pressure on the upper copy leaves a face': 'Druck auf die obere Kopie hinterlässt ein Gesicht',
    'the Artist once tried to draw something dangerous': 'Der Zeichner versuchte einst etwas Gefährliches',
    'the little roof continues above the red rule': 'Das kleine Dach geht über der roten Linie weiter',
    'the loose seam has a dashed arrow': 'Die lose Naht hat einen gestrichelten Pfeil',
    'the next page is classified': 'Die nächste Seite ist geheim',
    'the old answer is under those crossouts': 'Die alte Antwort liegt unter den Streichungen',
    'the original signature beneath two carbon copies': 'Die Originalunterschrift unter zwei Karbonkopien',
    'the rails continue in the margin': 'Die Schienen gehen am Rand weiter',
    'the rejected draft is under the proof line': 'Der verworfene Entwurf liegt unter der Korrekturlinie',
    'the timetable has a missing corner': 'Dem Fahrplan fehlt eine Ecke',
    'the wrong outline rings when ink touches it': 'Der falsche Umriss klingt bei Berührung mit Tinte',
    'turn it over — the dust is getting closer': 'Blättere um — der Staub kommt näher',
    'turn it over — the next page is classified': 'Blättere um — die nächste Seite ist geheim',
    'turn it over — the stars are badly drawn': 'Blättere um — die Sterne sind schlecht gezeichnet',
    'why did I draw the moon twice?': 'Warum zeichnete ich den Mond zweimal?',
    'zero gravity*  (*mostly)': 'Schwerelos* (*größtenteils)',
    'make the current agree': 'Gleiche den Strom ab',
    'CARBON SCAN': 'KARBONSCAN',
    'ERASER / JUMP': 'RADIERER / SPRING',
    'SCAN / WAIT': 'SCAN / WARTE',
    'a way up': 'Ein Weg nach oben',
    'a weapon': 'Eine Waffe',
    'better.': 'Besser.',
    'draw me...': 'Zeichne mir...',
    'CARBON': 'KARBON',
    'COPY  <---': 'KOPIEREN <---',
    'CREASE HOLDS': 'FALTE HÄLT',
    'MIRROR COPY HOLDS': 'SPIEGELKOPIE HÄLT',
    'RUB EVERY MARK': 'JEDE MARKE FREIREIBEN',
    'one fold tugs the crease on its left': 'Eine Falte zieht die linke Falz mit',
    'guard below / defeat the rejected drawing': 'Wächter unten / besiege die verworfene Zeichnung',
    'Q / wheel': 'Q / Mausrad',
    'returning · line up the fold': 'kehrt zurück · richte dich auf die Falte aus',
    'rub out incoming shots': 'ankommende Schüsse wegradieren',
    'third cut · exposed wound': 'dritter Schnitt · offene Wunde',
    'two cuts held · finish': 'zwei Schnitte bereit · abschließen',
    'winding up': 'holt aus',
    'reload': 'nachladen',
    'DASH →': 'AUSWEICHEN →',
    'BETWEEN': 'DAZWISCHEN',
    'FWOOSH': 'WUSCH',
    'PINNED!': 'FESTGENAGELT!',
    'READING': 'LIEST',
    'RELOADING': 'LÄDT NACH',
    'RESETTING': 'ERHOLT SICH',
    'HOT': 'HEISS',
    'NO.': 'NEIN.',
    'ARC': 'BOGEN',
    'SNAP': 'SCHNAPPT',
    'BACK': 'HINTEN',
    'ERASE': 'LÖSCHEN',
    'DRAW': 'ZIEHEN',
    'BEEP': 'PIEP',
    'HEH': 'HEHE',
    'ROLL': 'ROLLEN',
    'LOCK': 'FIXIEREN',
    'RAM': 'RAMMEN',
    'THREE': 'DREI',
    'MOVE': 'WEG',
    'JUMP': 'SPRING',
    'TRAIL': 'SPUR',
    'artist hesitation': 'Zögern des Zeichners',
    'E  redraw circuit node': 'E / Schaltungsknoten neu zeichnen',
    'the ink circuit hums open': 'Der Tintenkreis summt und öffnet sich',
    'E  turn the paper dial': 'E / Papierscheibe drehen',
    'the old symbols remember': 'Die alten Symbole erinnern sich',
    "the mistake's outline has come loose": 'Der Umriss des Fehlers hat sich gelöst',
    "The wet ink moves. The copies don't.": 'Nasse Tinte bewegt sich. Kopien nicht.',
    'THE ARTIST: New landing. Try the upper angle.': 'DER ZEICHNER: Neuer Absatz. Versuch es von oben.',
    'THE ARTIST: I kept your working notes.': 'DER ZEICHNER: Ich behielt deine Arbeitsnotizen.',
    'attempt two — still completely unfair': 'zweiter Versuch — immer noch völlig unfair',
    'THIRD ATTEMPT — ONE CLEAN SWING': 'DRITTER VERSUCH — EIN SAUBERER HIEB',
    'carbon reads backwards — copy right to left': 'Karbon liest rückwärts — kopiere rechts nach links',
    'all pressure marks found — turn the black sheet': 'alle Druckmarken gefunden — blättere das schwarze Blatt um',
    'the carbon smudged — begin again from the right': 'Karbon verschmiert — beginne wieder rechts',
    'mountain': 'Berg',
    'valley': 'Tal',
    'NEW CONSTELLATION': 'NEUES STERNBILD',
    'MARGIN MAUL': 'RANDHAMMER',
    'FOLDED SHURIKEN': 'GEFALTETER SHURIKEN',
    'CHALK BOMB': 'KREIDEBOMBE',
    'CARBON LANCE': 'KARBONLANZE',
    'EXCALIBUR': 'EXCALIBUR',
    'THE AGGRO MAN / it counted every attack': 'DER ANGRIFFSLUSTIGE / er zählte jeden Angriff',
    'BRAVEMAN / the margins followed you': 'DER MUTIGE / die Ränder folgten dir',
    'MIRROR / it remembered the clean inputs': 'SPIEGEL / er erinnerte sich an saubere Eingaben',
    'MIXED REVISION / it could not classify you': 'GEMISCHTE KORREKTUR / keine Zuordnung möglich',
    'AGGRO': 'ANGRIFFSLUSTIG',
    'MIXED': 'GEMISCHT',
    'DASH RIGHT / through the dashed seam': 'NACH RECHTS AUSWEICHEN / durch die gestrichelte Naht',
    'JUMP ABOVE / the poster tears at the dashed seam': 'NACH OBEN SPRINGEN / das Plakat reißt an der Naht',
    'NO SIGNAL / take the star from the lower pad': 'KEIN SIGNAL / nimm den Stern vom unteren Sockel',
    'STAR CHARGED / climb the satellite steps': 'STERN GELADEN / steige die Satellitenstufen hinauf',
    'E  turn over the carbon sheet': 'E / Karbonblatt umblättern',
    'the shared crease folds the ink gate away': 'Die gemeinsame Falte faltet das Tintentor weg',
    'the mirrored carbon line copies the gate away': 'Die gespiegelte Karbonlinie kopiert das Tor weg',
    'One more line. This one fights differently.': 'Noch eine Linie. Diese kämpft anders.',
    'You earned the drawing. E to keep it and answer me.': 'Die Zeichnung gehört dir. Mit E behalten und antworten.',
    'KING?': 'KÖNIG?',
    'TURN': 'UMBLÄTTERN',
    'wrong century': 'falsches Jahrhundert',
    'needs a hat': 'braucht einen Hut',
    'close enough to space': 'fast wie Weltraum',
    'dust updraft': 'Staubaufwind',
    'leaking star ink': 'auslaufende Sternentinte',
    'E  enter tear': 'E / Riss betreten',
    'combat ink soaking through': 'Kampftinte sickert durch',
    'dark coffee sediment': 'dunkler Kaffeesatz',
    'thin coffee ring': 'dünner Kaffeering',
    'wet ink': 'nasse Tinte',
    'PULL': 'ZIEH',
    'DIVE': 'STURZFLUG',
    'INK v': 'TINTE v',
    'SCAN': 'SCANNEN',
    'STAMP': 'STEMPEL',
    'E  take INK KATANA': 'E / TINTENKATANA nehmen',
    'NEW DRAWING — INK KATANA': 'NEUE ZEICHNUNG — TINTENKATANA',
    'E  take PENCIL BLADE': 'E / BLEISTIFTKLINGE nehmen',
    'NEW DRAWING — PENCIL BLADE': 'NEUE ZEICHNUNG — BLEISTIFTKLINGE',
    'E  take RETURNING FOLD': 'E / RÜCKKEHRFALTE nehmen',
    'NEW DRAWING — RETURNING FOLD': 'NEUE ZEICHNUNG — RÜCKKEHRFALTE',
    'E  take OVERSIZED PENCIL': 'E / RIESENBLEISTIFT nehmen',
    'NEW DRAWING — OVERSIZED PENCIL': 'NEUE ZEICHNUNG — RIESENBLEISTIFT',
    'E  take CHALK CAPSULE': 'E / KREIDEKAPSEL nehmen',
    'NEW DRAWING — CHALK CAPSULE': 'NEUE ZEICHNUNG — KREIDEKAPSEL',
    'E  take METEOR CHALK': 'E / METEORKREIDE nehmen',
    'NEW DRAWING — METEOR CHALK': 'NEUE ZEICHNUNG — METEORKREIDE',
    'E  take CARBON RIFLE': 'E / KARBONGEWEHR nehmen',
    'NEW DRAWING — CARBON RIFLE': 'NEUE ZEICHNUNG — KARBONGEWEHR',
    'E  take INK PISTOL': 'E / TINTENPISTOLE nehmen',
    'NEW DRAWING — INK PISTOL': 'NEUE ZEICHNUNG — TINTENPISTOLE',
    'E  take SIX-SHOOTER': 'E / SECHSSCHÜSSER nehmen',
    'NEW DRAWING — SIX-SHOOTER': 'NEUE ZEICHNUNG — SECHSSCHÜSSER',
    'E  take SUPPRESSED PISTOL': 'E / SCHALLGEDÄMPFTE PISTOLE nehmen',
    'NEW DRAWING — SUPPRESSED PISTOL': 'NEUE ZEICHNUNG — SCHALLGEDÄMPFTE PISTOLE',
    'E  take MARKER SHOTGUN': 'E / MARKERSCHROTFLINTE nehmen',
    'NEW DRAWING — MARKER SHOTGUN': 'NEUE ZEICHNUNG — MARKERSCHROTFLINTE',
    'E  take DOUBLE BARREL': 'E / DOPPELLAUF nehmen',
    'NEW DRAWING — DOUBLE BARREL': 'NEUE ZEICHNUNG — DOPPELLAUF',
    'E  take BREACH SHOTGUN': 'E / STURMSCHROTFLINTE nehmen',
    'NEW DRAWING — BREACH SHOTGUN': 'NEUE ZEICHNUNG — STURMSCHROTFLINTE',
    'E  take ERASER CANNON': 'E / RADIERERKANONE nehmen',
    'NEW DRAWING — ERASER CANNON': 'NEUE ZEICHNUNG — RADIERERKANONE',
    'E  take NULL CANNON': 'E / NULLKANONE nehmen',
    'NEW DRAWING — NULL CANNON': 'NEUE ZEICHNUNG — NULLKANONE',
    'E  take RUBBER BAND': 'E / GUMMIBAND nehmen',
    'NEW DRAWING — RUBBER BAND': 'NEUE ZEICHNUNG — GUMMIBAND',
    'E  take ORBIT PULSE': 'E / ORBITALIMPULS nehmen',
    'NEW DRAWING — ORBIT PULSE': 'NEUE ZEICHNUNG — ORBITALIMPULS',
    'E  take BOWIE KNIFE': 'E / BOWIEMESSER nehmen',
    'NEW DRAWING — BOWIE KNIFE': 'NEUE ZEICHNUNG — BOWIEMESSER',
    'E  take FIELD KNIFE': 'E / FELDMESSER nehmen',
    'NEW DRAWING — FIELD KNIFE': 'NEUE ZEICHNUNG — FELDMESSER',
    'E  take ION EDGE': 'E / IONENKLINGE nehmen',
    'NEW DRAWING — ION EDGE': 'NEUE ZEICHNUNG — IONENKLINGE',
    'E  take REDRAW PENCIL': 'E / NEUZEICHNUNGSBLEISTIFT nehmen',
    'NEW DRAWING — REDRAW PENCIL': 'NEUE ZEICHNUNG — NEUZEICHNUNGSBLEISTIFT',
    'E  take THE VERY DRAMATIC SWORD': 'E / DAS SEHR DRAMATISCHE SCHWERT nehmen',
    'NEW DRAWING — THE VERY DRAMATIC SWORD': 'NEUE ZEICHNUNG — DAS SEHR DRAMATISCHE SCHWERT',
    'E  take ORBITAL RUBBER BAND': 'E / ORBITALES GUMMIBAND nehmen',
    'NEW DRAWING — ORBITAL RUBBER BAND': 'NEUE ZEICHNUNG — ORBITALES GUMMIBAND',
}
