TR_COMBAT = {
'< back':'< geri','BAD LANDING':'KÖTÜ İNİŞ','CLEAN MARGIN':'TEMİZ KENAR','COOLING':'SOĞUYOR',
'DEAD / ALIVE':'ÖLÜ / DİRİ','DEAD OR ALIVE — FOUR POSTERS, FOUR LINES':'ÖLÜ YA DA DİRİ — DÖRT AFİŞ, DÖRT ÇİZGİ',
'EVADE THE ORDER — STRIKE THE EXPOSED CARBON CORE':'EMİRDEN KAÇ — AÇIK KARBON ÇEKİRDEĞİ VUR',
'EXPRESS REVISION — IT COMES BACK':'EKSPRES DÜZELTME — GERİ DÖNÜYOR','II / RETRACE':'II / TEKRAR ÇİZ',
'JUMP THE RAIL — HIT THE REAR OR THE OPEN ENGINE':'RAYIN ÜSTÜNDEN ZIPLA — ARKAYI YA DA AÇIK MOTORU VUR',
'JUMP THE RED ARC — STRIKE WHILE THE BLADE IS STUCK':'KIRMIZI YAYDAN ZIPLA — BIÇAK SAPLIYKEN VUR',
'LET THE SHIELDS GO — HIT THE EXPOSED CORE':'KALKANLARIN GEÇMESİNİ BEKLE — AÇIK ÇEKİRDEĞİ VUR',
'LOOSE LINES':'GEVŞEK ÇİZGİLER','LOOSE — ERASE NOW':'GEVŞEDİ — ŞİMDİ SİL','NEEDLE STUCK — HIT':'İĞNE SAPLANDI — VUR',
'OPEN':'AÇIK','PUNCHED':'DELİNDİ','RE-FILE':'YENİDEN DOSYALA',
'READ THE DRAFT — ATTACK WHEN ITS GUARD DROPS':'TASLAĞI OKU — SAVUNMASI DÜŞÜNCE SALDIR',
'RETURN SERVICE':'DÖNÜŞ SEFERİ','SECOND DRAFT — THE ARC COMES BACK':'İKİNCİ TASLAK — YAY GERİ DÖNÜYOR',
'SIGHT LOCKED':'NİŞAN SABİTLENDİ','STAMP JAMMED':'DAMGA SIKIŞTI','STUCK':'SAPLANDI','TAB EXPOSED':'ŞERİT AÇIK',
'THE BINDER CLIP IS OPEN':'DEFTER KLİPSİ AÇIK','THE WET INK IS REAL — SHOOT BEFORE THE DRAW':'ISLAK MÜREKKEP GERÇEK — ÇEKMEDEN ATEŞ ET',
'THIS DRAWING IS UNFAIR ON PURPOSE':'BU ÇİZİM BİLEREK HAKSIZ','THREE SHOTS':'ÜÇ ATIŞ','UNCRUMPLED':'KIRIŞIKLIĞI AÇILDI',
'WANTED':'ARANIYOR','copy...':'kopyala...','empty':'boş','new centre':'yeni merkez','retracing':'tekrar çiziyor',
'smoke':'duman','soft side exposed':'zayıf taraf açık','<<< CROSS OUT':'<<< ÜSTÜNÜ ÇİZ','CROSS OUT >>>':'ÜSTÜNÜ ÇİZ >>>',
'ALL ABOARD — JUMP!':'HERKES TRENE — ZIPLA!','ARM SWEEP':'KOL SÜPÜRMESİ','BIG FOOT':'DEV AYAK',
'COPY BOTH SIDES':'İKİ TARAFI KOPYALA','CORE EXPOSED':'ÇEKİRDEK AÇIK','CORE OPEN':'ÇEKİRDEK AÇIK',
'CORE SEALED':'ÇEKİRDEK KAPALI','CROSS OUT':'ÜSTÜNÜ ÇİZ','ENGINE OPEN':'MOTOR AÇIK','ERASE BELOW':'ALTI SİL',
'FIND THE CLEAN MARGIN':'TEMİZ KENARI BUL','FIRING ORDER — LEAVE THE LINES':'ATEŞ EMRİ — ÇİZGİLERDEN ÇIK',
'GUARD UP':'SAVUNMA AÇIK','INK ARC':'MÜREKKEP YAYI','JUMP THE ARC':'YAYIN ÜZERİNDEN ZIPLA',
'JUMP THE LOW SWEEP':'ALÇAK SÜPÜRMEDEN ZIPLA','LEAVE THE RED X':'KIRMIZI X’TEN ÇIK','MARGINS CLOSE':'KENARLAR KAPANIYOR',
'MOONS AWAY':'AYLAR UZAKLAŞIYOR','MOVE — REDACTION STAMP':'KAÇ — SANSÜR DAMGASI',
'ORDER II — THE FLOOR IS CLASSIFIED':'EMİR II — ZEMİN GİZLİ','ORDER III — CARBON FIRING SQUAD':'EMİR III — KARBON ATEŞ TİMİ',
'ORDER SEALED':'EMİR KAPALI','PROOF SHOTS':'PROVA ATIŞLARI','RETURN TRAIN — JUMP!':'GERİ DÖNEN TREN — ZIPLA!',
'SECOND CUT':'İKİNCİ KESİŞ','STAMP BELOW':'ALTA DAMGA','THE ARC RETURNS':'YAY GERİ DÖNÜYOR',
'THE ARTIST: Nice line.':'RESSAM: Güzel çizgi.','WHOLE PAGE':'TÜM SAYFA','YOUR TURN':'SIRA SENDE',
'AIRLOCK / NO SIGNAL':'HAVA KİLİDİ / SİNYAL YOK','AIRLOCK CLOSED / return to the star pad':'HAVA KİLİDİ KAPALI / yıldız yuvasına dön',
'CONNECTION HELD':'BAĞLANTI KURULDU','E / CHARGE':'E / ŞARJ ET','E / CONNECT':'E / BAĞLA',
'JUMP / THEN DASH  >>':'ZIPLA / SONRA ATIL  >>','MARGIN / CLOSED':'KENAR / KAPALI','REVISED':'DÜZELTİLDİ',
'SHIFT / K  RIGHT':'SHIFT / K  SAĞA','TEAR ALONG  - - -':'ÇİZGİDEN YIRT  - - -','TORN':'YIRTILDI',
'THE ARTIST: A good tear. I should have left that edge rough.':'RESSAM: Güzel yırttın. O kenarı pürüzlü bırakmalıydım.',
'THE ARTIST: Carry this spark to the dish before it fades.':'RESSAM: Sönmeden bu kıvılcımı antene götür.',
'THE ARTIST: Connected. That airlock was a bad drawing.':'RESSAM: Bağlandı. O hava kilidi kötü bir çizimdi.',
'THE ARTIST: The star faded. I can charge it again.':'RESSAM: Yıldız söndü. Tekrar şarj edebilirim.',
'E  charge the loose star / 15 seconds':'E  boş yıldızı şarj et / 15 saniye',
'E  connect the star to the dish':'E  yıldızı antene bağla',
'E  ask about the rubbed-out figure':'E  silinmiş figürü sor','E  ask why the moon has two outlines':'E  ayın iki dış çizgisi olmasını sor',
"E  unfold the timetable's corner":'E  tarifenin köşesini aç',
'Lost Sketches = discarded ideas.\nKeep one. Its trick stays across pages.':'Kayıp Eskizler = atılmış fikirler.\nSakla. Tekniği her sayfada kalır.',
'The original left a face.\nKeep the badge; I can draw its rifle.':'Özgün çizim bir yüz bıraktı.\nRozeti sakla; tüfeğini çizebilirim.',
'a named drawing — three fresh heart-marks':'özel bir çizim — üç taze kalp izi',
'crossed out — fresh ink at the next fight':'üstü çizildi — sonraki savaşta taze mürekkep',
'the graphite cracks — a new pattern':'grafit çatlıyor — yeni bir kalıp',
'Collect every Lost Sketch and secret rune.':'Tüm Kayıp Eskizleri ve gizli rünleri topla.',
}
