"""Authored Italian player-facing text; English sources remain canonical."""

IT = {
    'TRAINING': 'ALLENAMENTO',
    'FIELD NOTES / 0.31': 'APPUNTI / 0.31',
    'TRAINING COMPLETE / your campaign progress is kept': 'ALLENAMENTO COMPLETATO / progressi conservati',
    'F / J or left click: destroy all four targets along the practice lane.': 'F / J o clic sinistro: distruggi i quattro bersagli.',
    'Shift / K or right click: leave the frozen red column before it fires. Dodge three warnings.': 'Shift / K o clic destro: esci dalla colonna rossa prima del colpo. Schiva tre avvisi.',
    'E at the pencil lever: ask the Artist for stairs. Climb to the rune seal and read it with E.': 'E alla leva: chiedi una scala. Raggiungi il sigillo e leggilo con E.',
    'TRAINING YARD / FOUR TARGETS': 'CAMPO DI PROVA / QUATTRO BERSAGLI',
    'DODGE LANE / FOLLOW THE WARNING': "SCHIVATA / SEGUI L'AVVISO",
    "THE ARTIST'S STAIRS / CLIMB TO THE RUNE": 'LA SCALA DEL DISEGNATORE / VERSO LA RUNA',
    'E / ARTIST': 'E / DISEGNATORE',
    'E / ask the Artist to draw the training stairs': 'E / chiedi una scala',
    'Good dodge. The red mark stayed where it was drawn.': 'Bella schivata. Il segno rosso è rimasto fermo.',
    'Practice only: dash out of the red column after it appears.': 'Prova: scatta fuori dalla colonna rossa quando appare.',
    'EXPLORE / three blue marks above the road': 'ESPLORA / tre segni blu sopra il percorso',
    'E / trace the blue waypoint': 'E / traccia il segno blu',
    'E / THREE BLUE MARKS / +1 HEART': 'E / TRE SEGNI BLU / +1 CUORE',
    'The Artist traced your route and restored one heart.': 'Il Disegnatore ha tracciato il percorso e ripristinato un cuore.',
    'BAMBOO WALK': 'PASSAGGIO DI BAMBÙ',
    'THE OLD VIADUCT': 'IL VECCHIO VIADOTTO',
    'SATELLITE WALK': 'PASSAGGIO SATELLITARE',
    'THE ROOFTOP ARCHIVE': "L'ARCHIVIO SUL TETTO",
    'THE UNWRITTEN GARDEN': 'IL GIARDINO NON SCRITTO',
    'HIGH THRUST — STAY LOW': 'AFFONDO ALTO — RESTA IN BASSO',
    'LOW RICOCHET — JUMP OR RETURN': 'RIMBALZO BASSO — SALTA O RESPINGI',
    'LOW THEN HIGH — JUMP, THEN LAND': 'PRIMA BASSO, POI ALTO — SALTA E ATTERRA',
    'COMET RAIN — KEEP THE BLUE GAP': 'PIOGGIA DI COMETE — RESTA NEL VARCO BLU',
    'JUMP THE CLOSING BRACKET': 'SALTA LA PARENTESI CHE SI CHIUDE',
    'ERASER RAIN — LEAVE THE NUMBERED MARKS': 'PIOGGIA DI GOMME — LASCIA I SEGNI NUMERATI',
    'The Artist:': 'Il Disegnatore:',
    'the Artist:': 'il Disegnatore:',
    'NEW GAME': 'NUOVA PARTITA',
    'CONTINUE': 'CONTINUA',
    'SETTINGS': 'IMPOSTAZIONI',
    'QUIT': 'ESCI',
    'BACK PAGES': 'ALBUM DEGLI SCHIZZI',
    'ACHIEVEMENTS': 'OBIETTIVI',
    'ACHIEVEMENT': 'OBIETTIVO',
    'RESTART PAGE': 'RIAVVIA PAGINA',
    'TITLE': 'MENU PRINCIPALE',
    'CONTROLS': 'COMANDI',
    'Back': 'Indietro',
    'Master volume': 'Volume generale',
    'SFX volume': 'Volume effetti',
    'Music volume': 'Volume musica',
    'Window size': 'Dimensioni finestra',
    'Fullscreen': 'Schermo intero',
    'Language': 'Lingua',
    'YES': 'SÌ',
    'NO': 'NO',
    'page held open': 'pagina tenuta aperta',
    'Every line leaves a mark.': 'Ogni linea lascia un segno.',
    'FIELD NOTES / 0.30': 'APPUNTI / 0.30',
    'A longer lesson. Hidden margins.': 'Una lezione più lunga. Margini nascosti.',
    'New attacks. Ideas worth keeping.': 'Nuovi attacchi. Idee da conservare.',
    'Arrows / W S select  ·  ENTER play  ·  click to choose': 'Frecce / W S: scegli · ENTER: gioca · clic: scegli',
    'ESC continue  ·  arrows select  ·  ENTER confirm': 'ESC: continua · frecce: scegli · ENTER: conferma',
    'Learn the line, then make it yours.': 'Impara la linea, poi traccia la tua.',
    'Move': 'Movimento',
    'Jump': 'Salto',
    'Attack': 'Attacco',
    'Dash / return': 'Scatto / respingi',
    'Interact / sketch': 'Interagisci / schizzo',
    'Reload / switch': 'Ricarica / cambia',
    'Drop through': 'Scendi dalla piattaforma',
    'Pause / fullscreen': 'Pausa / schermo intero',
    'Space / W / Up  ·  release for a short jump': 'Spazio / W / ↑ · rilascia per un salto breve',
    'F / J  ·  left click aims at the pointer': 'F / J · clic sinistro: mira al puntatore',
    'Shift / K  ·  right click': 'Shift / K · clic destro',
    'R  /  Q or mouse wheel': 'R / Q o rotellina',
    'S or Down + any jump key': 'S o ↓ + tasto salto',
    'ENTER / ESC   Back': 'ENTER / ESC   Indietro',
    'Rejected drawings. Real techniques. Learned ideas survive every redraw.': 'Disegni scartati. Tecniche permanenti.',
    'next  >': 'avanti >',
    '<  previous': '< precedente',
    'A / ESC   close': 'A / ESC   chiudi',
    'B / ESC   close the back cover': "B / ESC   chiudi l'album",
    'PAD-A / PAD-B   close the back cover': "PAD-A / PAD-B   chiudi l'album",
    'PAD-A / PAD-B   close': 'PAD-A / PAD-B   chiudi',
    'D-PAD choose   •   PAD-A confirm   •   PAD-B continue': 'D-PAD: scegli • PAD-A: conferma • PAD-B: continua',
    'D-PAD change  •  PAD-A confirm  •  PAD-B returns': 'D-PAD: modifica • PAD-A: conferma • PAD-B: indietro',
    'click or use arrows  •  F11 fullscreen  •  ESC returns': 'Clic o frecce • F11: schermo intero • ESC: indietro',
    'CONTROLLER CONNECTED': 'CONTROLLER COLLEGATO',
    'CONTROLLER READY': 'CONTROLLER PRONTO',
    'condition not written down': 'condizione ancora sconosciuta',
    'the page remains open   —   ENTER': 'la pagina resta aperta — ENTER',
    'checkpoint — redrawn here': 'punto di controllo — ridisegnato qui',
    'dash': 'scatto',
    'IN HAND': 'IN MANO',
    'RELOAD': 'RICARICA',
    'EMPTY HANDS': 'MANI VUOTE',
    'the next tool is still being drawn': 'la prossima arma è ancora in fase di disegno',
    'INK KATANA': "KATANA D'INCHIOSTRO",
    'PENCIL BLADE': 'LAMA DI MATITA',
    'INK PISTOL': "PISTOLA D'INCHIOSTRO",
    'RETURNING FOLD': 'PIEGA DI RITORNO',
    'OVERSIZED PENCIL': 'MATITA GIGANTE',
    'SIX-SHOOTER': 'SEI COLPI',
    'DOUBLE BARREL': 'DOPPIETTA',
    'CHALK CAPSULE': 'CAPSULA DI GESSO',
    'METEOR CHALK': 'GESSO METEORA',
    'CARBON RIFLE': 'FUCILE CARBONE',
    'MARKER SHOTGUN': 'FUCILE A PENNARELLO',
    'ERASER CANNON': 'CANNONE GOMMA',
    'NULL CANNON': 'CANNONE VUOTO',
    'RUBBER BAND': 'ELASTICO',
    'ORBIT PULSE': 'IMPULSO ORBITALE',
    'BOWIE KNIFE': 'COLTELLO BOWIE',
    'ION EDGE': 'LAMA IONICA',
    'SUPPRESSED PISTOL': 'PISTOLA SILENZIATA',
    'BREACH SHOTGUN': 'FUCILE DA BRECCIA',
    'THE VERY DRAMATIC SWORD': 'LA SPADA MOLTO DRAMMATICA',
    'KING ARTHUR · subtlety unavailable': 'RE ARTÙ · finezza non disponibile',
    'draw dash · return step · rising launch': 'fendente in scatto · passo indietro · lancio in alto',
    'one fold at a time · catch the return line': 'una piega alla volta · afferra il ritorno',
    'wind up · crush · erase shots in reach': 'carica · schiaccia · cancella i colpi vicini',
    'six heavy shots · deliberate rhythm': 'sei colpi pesanti · ritmo preciso',
    'arc over cover · two gentle bursts': 'sopra i ripari · due piccole esplosioni',
    'two quick blasts · wide spread': 'due colpi rapidi · ampia dispersione',
    'arc around shields · small impact cloud': "arco attorno agli scudi · piccola nube d'impatto",
    'three ricochets · bank off ink': "tre rimbalzi · sfrutta l'inchiostro",
    'cut through volleys · straight flight': 'attraversa le raffiche · volo dritto',
    'one round · pierces a line · long reload': 'un colpo · perfora una fila · ricarica lenta',
    'close-range ink burst': "raffica d'inchiostro ravvicinata",
    'erase incoming fire': 'cancella i colpi in arrivo',
    'steady ink fire': "fuoco d'inchiostro costante",
    'three strokes · heavy finish': 'tre colpi · finale potente',
    '01 / FIND YOUR FEET': "01 / TROVA L'EQUILIBRIO",
    '02 / FOLLOW THE INK': "02 / SEGUI L'INCHIOSTRO",
    '03 / THE RETURNING FOLD': '03 / LA PIEGA DI RITORNO',
    '04 / LEAVE THE RED LINE': '04 / LASCIA LA LINEA ROSSA',
    '05 / IDEAS THAT STAY': '05 / IDEE CHE RESTANO',
    'A / D or Left / Right: move. Explore the first lines.': 'A / D o ← / →: muoviti. Esplora le prime linee.',
    'Space / W / Up: jump. Release early for a short jump. Collect the drawn tool.': "Spazio / W / ↑: salta. Rilascia presto per un salto breve. Prendi l'arma.",
    'F / J or left click: hit the practice drawing with your Returning Fold.': 'F / J o clic sinistro: colpisci il bersaglio con la Piega di Ritorno.',
    'Shift / K or right click: dash three times. Watch the recovery line.': 'Shift / K o clic destro: scatta tre volte. Guarda il recupero.',
    'E at the lesson seal: read how sketches work. B in pause opens your learned runes.': 'E al sigillo: scopri gli schizzi. B in pausa apre le rune apprese.',
    'Destroy the practice drawing': 'Distruggi il bersaglio',
    'Seal read': 'Sigillo letto',
    'Read the seal with E': 'Leggi il sigillo con E',
    'E / LESSON SEAL': 'E / SIGILLO DELLA LEZIONE',
    'E  read the lesson seal / sketches are lasting runes': 'E / leggi il sigillo',
    'SKETCH RUNES: Permanent techniques, clear numeric effects. They survive page turns and redraws. Find them on optional routes.': 'RUNE DEGLI SCHIZZI: tecniche permanenti con effetti precisi. Cercale nei percorsi facoltativi.',
    'FIRST LESSON COMPLETE / the combat page is open': 'PRIMA LEZIONE COMPLETATA / pagina di combattimento aperta',
    'Lost Sketches are discarded ideas. Keep them to learn lasting tricks across pages.': 'Gli Schizzi Perduti insegnano tecniche permanenti.',
    'LOST SKETCH — clipped into the back pages.': "SCHIZZO PERDUTO — aggiunto all'album.",
    'UNDISCOVERED SKETCH': 'SCHIZZO NON SCOPERTO',
    'ACTIVE': 'ATTIVA',
    'NEEDS ITS WEAPON': 'ARMA RICHIESTA',
    'SAVED / NEEDS ITS WEAPON': 'SALVATA / ARMA RICHIESTA',
    'A rejected drawing. A useful idea.': "Un disegno scartato. Un'idea utile.",
    'Clipped into BACK PAGES': "Aggiunto all'ALBUM",
    'SEALED / finish the margin challenge': 'SIGILLATO / supera la sfida del margine',
    'E  keep this drawing': 'E / conserva il disegno',
    'E  examine lost sketch': 'E / esamina lo schizzo',
    'Defeat the rejected drawing below': 'Sconfiggi il disegno scartato in basso',
    'E  challenge the drawing / optional': 'E / sfida il disegno (facoltativo)',
    'THE FIRST FIGURE': 'LA PRIMA FIGURA',
    'SECOND THOUGHT': 'SECONDO PENSIERO',
    'PRACTICE MONSTER': 'MOSTRO DI PROVA',
    'FOLLOW THROUGH': 'SLANCIO FINALE',
    'THE KITE RONIN': 'IL RONIN AQUILONE',
    'PAPER KITE': 'AQUILONE DI CARTA',
    'THE MARGIN HOUSE': 'LA CASA NEL MARGINE',
    'QUICK DRAW': 'ESTRAZIONE RAPIDA',
    'COFFEE UMBRELLA': 'OMBRELLO DI CAFFÈ',
    'TIGHT FOLD': 'PIEGA STRETTA',
    'THE VICTORY POSE': 'LA POSA VITTORIOSA',
    'MAKE SOME ROOM': 'FAI SPAZIO',
    'THE UNUSED TICKET': 'IL BIGLIETTO INUTILIZZATO',
    'THROUGH TICKET': 'BIGLIETTO DI PASSAGGIO',
    'THE APOLOGETIC BEAST': 'LA BESTIA DISPIACIUTA',
    'ELASTIC MEMORY': 'MEMORIA ELASTICA',
    'THE ERASER SURVIVOR': 'IL SOPRAVVISSUTO ALLA GOMMA',
    'CLEAN SLATE': 'PAGINA PULITA',
    'THE SECOND MOON': 'LA SECONDA LUNA',
    'LOW ORBIT': 'ORBITA BASSA',
    'THE FORGED BADGE': 'IL DISTINTIVO FALSO',
    'FAST INK': 'INCHIOSTRO RAPIDO',
    'THE LAST HOMEWORK': "L'ULTIMO COMPITO",
    'REVISION RHYTHM': 'RITMO DI REVISIONE',
    'THE RONIN': 'IL RONIN',
    'HIGH NOON': 'MEZZOGIORNO DI FUOCO',
    'THE AGENT': "L'AGENTE",
    'THE LAST DRAFT': "L'ULTIMA BOZZA",
    'Jump a little later after leaving an edge.': 'Puoi saltare poco dopo aver lasciato un bordo.',
    'Your blade finisher reaches farther.': 'Il colpo finale della lama arriva più lontano.',
    'Change direction faster in the air.': 'Cambia direzione più rapidamente in aria.',
    'Reload your sidearm faster.': 'Ricarica la pistola più rapidamente.',
    'Your scattergun keeps a tighter spread.': 'Il fucile a pallettoni disperde meno.',
    'Scattergun hits push enemies farther.': 'I colpi a pallettoni spingono i nemici più lontano.',
    'Sidearm shots pass through one enemy.': 'I proiettili della pistola attraversano un nemico.',
    'Ricochet shots bounce one more time.': 'I proiettili rimbalzano una volta in più.',
    'Reload your heavy cannon faster.': 'Ricarica il cannone pesante più rapidamente.',
    'Ricochet shots stay in flight longer.': 'I proiettili a rimbalzo restano in volo più a lungo.',
    'Sidearm bullets reach their target faster.': 'I proiettili della pistola arrivano prima al bersaglio.',
    'Your dash becomes ready sooner.': 'Lo scatto si ricarica prima.',
    'PAGE I': 'PAGINA I',
    'PAGE II': 'PAGINA II',
    'PAGE III': 'PAGINA III',
    'PAGE IV': 'PAGINA IV',
    'PAGE V': 'PAGINA V',
    'Ink of the Ronin': 'Inchiostro del Ronin',
    'Dust & Bad Decisions': 'Polvere e cattive decisioni',
    'A Very Wrong Future': 'Un futuro molto sbagliato',
    'The Carbon Agent': "L'Agente Carbone",
    'The Last Draft': "L'Ultima Bozza",
    'THE ARTIST': 'IL DISEGNATORE',
    'ARTIST': 'DISEGNATORE',
    'WAIT / the Artist is finishing this line': 'ASPETTA / il Disegnatore sta finendo la linea',
    'E  trace the first graphite mark': 'E / traccia il primo segno di grafite',
    'E  connect the upper mark': 'E / collega il segno superiore',
    'E  cross out the red margin': 'E / cancella il margine rosso',
    'FIRST / lower pencil mark': 'PRIMO / segno di matita inferiore',
    'NEXT / upper pencil mark': 'POI / segno di matita superiore',
    'LAST / cross out the margin': 'INFINE / cancella il margine',
    '1 / TRACE': '1 / TRACCIA',
    '2 / CONNECT ABOVE': '2 / COLLEGA IN ALTO',
    '3 / CROSS OUT': '3 / CANCELLA',
    'THE ARTIST: A step belongs above this line.': 'IL DISEGNATORE: Serve un gradino sopra questa linea.',
    'THE ARTIST: Yes. Find the last crossed-out mark.': "IL DISEGNATORE: Sì. Trova l'ultimo segno cancellato.",
    'THE ARTIST: Erasing the margin now.': 'IL DISEGNATORE: Ora cancello il margine.',
    'THE ARTIST: Better. That line can go.': 'IL DISEGNATORE: Meglio. Quella linea può sparire.',
    'arena sealed — clear every red mark': 'arena sigillata — elimina tutti i segni rossi',
    'arena clear — ink dries, the margin opens': 'arena libera — il margine si apre',
    'the gate shuts — a named drawing waits below': 'il cancello si chiude — un disegno speciale aspetta in basso',
    'READ THE RED MARK — MOVE, THEN PUNISH': 'LEGGI IL SEGNO ROSSO — SCHIVA, POI COLPISCI',
    'Too heavy? You asked for it. Q swaps back.': "Troppo pesante? L'hai chiesta tu. Q per tornare all'arma precedente.",
    'All right. Your way. Jump onto the new line.': 'Va bene. A modo tuo. Salta sulla nuova linea.',
    'Too many teeth. Let me fix that.': 'Troppi denti. Li sistemo io.',
    'He changed the rules. So can we. Use this line.': 'Ha cambiato le regole. Possiamo farlo anche noi. Usa questa linea.',
    'E  ASK THE ARTIST TO ERASE A FOE (once this room)': 'E / fai cancellare un nemico (una volta per stanza)',
    'DRAW A HEAVY PENCIL': 'DISEGNA UNA MATITA GIGANTE',
    'DRAW A HIGH ROAD': 'DISEGNA UN PERCORSO ALTO',
    'next lesson...': 'prossima lezione...',
    'Who drew the gun?': 'Chi ha disegnato la pistola?',
    'I did not draw that moon.': 'Non ho disegnato io quella luna.',
    'Someone is cutting the notebook.': 'Qualcuno sta tagliando il quaderno.',
    'He has been reading your moves.': 'Stava leggendo le tue mosse.',
    'a red stroke warns; a blue gap invites': 'un tratto rosso avverte; un varco blu invita',
    'a fold that finds its way back': 'una piega che trova la strada del ritorno',
    'SPACE  ^': 'SPAZIO ^',
    'A / D   ->': 'A / D ->',
    'SHIFT / K  ->  leave the red line behind': 'SHIFT / K -> lascia la linea rossa',
    'A SAFE FIRST DRAFT': 'UNA PRIMA BOZZA SICURA',
    'Cross out the opening practice drawing.': 'Cancella il primo bersaglio di prova.',
    'I CAN HEAR YOU': 'TI SENTO',
    "Reply to the Artist's margin note.": 'Rispondi alla nota del Disegnatore.',
    'A SMALL CONVERSATION': 'UNA PICCOLA CONVERSAZIONE',
    'Reply to the Artist five times.': 'Rispondi al Disegnatore cinque volte.',
    'A LINE OF YOUR OWN': 'UNA LINEA TUTTA TUA',
    'Solve a physical page puzzle.': 'Risolvi un rompicapo della pagina.',
    'REWRITE THE ROUTE': 'RIDISEGNA IL PERCORSO',
    'Solve all three page route puzzles.': 'Risolvi tutti e tre i rompicapi del percorso.',
    'FIELD NOTES': 'APPUNTI',
    'Defeat twelve different enemy kinds.': 'Sconfiggi dodici tipi diversi di nemici.',
    'UNFAMILIAR INK': 'INCHIOSTRO SCONOSCIUTO',
    'Defeat a Fold Duelist, Margin Sniper and Split Lantern.': 'Sconfiggi Duellante Piegato, Cecchino del Margine e Lanterna Spaccata.',
    'EVERY LOST LINE': 'OGNI LINEA PERDUTA',
    'Collect all twelve Lost Sketches.': 'Raccogli tutti gli Schizzi Perduti.',
    'Collect every Lost Sketch and secret rune.': 'Raccogli tutti gli Schizzi Perduti e le rune segrete.',
    'SIX SIGNATURES': 'SEI FIRME',
    'Defeat all six named bosses.': 'Sconfiggi tutti e sei i boss principali.',
    'POST OFFICE': 'UFFICIO POSTALE',
    'Perfectly return ten incoming shots.': 'Respingi dieci colpi con tempismo perfetto.',
    'MARGIN EXPLORER': 'ESPLORATORE DEI MARGINI',
    'Clear twenty encounters.': 'Completa venti scontri.',
    'FIRST CROSS-OUT': 'PRIMA CANCELLAZIONE',
    'Defeat the first hostile doodle.': 'Sconfiggi il primo scarabocchio ostile.',
    'BRAVEMAN': "L'UOMO CORAGGIOSO",
    'Reach a page turn while avoiding more than attacking.': 'Termina una pagina schivando più di quanto attacchi.',
    'THE AGGRO MAN': "L'UOMO AGGRESSIVO",
    'Attack 90 times, mostly with the Pencil Blade.': 'Attacca 90 volte, soprattutto con la Lama di Matita.',
    'NO RED MARKS': 'NESSUN SEGNO ROSSO',
    'Finish a page without taking damage.': 'Termina una pagina senza subire danni.',
    'BACK-PAGE READER': "LETTORE DELL'ALBUM",
    'Clip three Lost Sketches into the back pages.': "Aggiungi tre Schizzi Perduti all'album.",
    'TEMPORARY TOOLBOX': 'ARSENALE TEMPORANEO',
    'Attack with every ordinary page weapon.': 'Attacca con ogni arma ordinaria della pagina.',
    'QUICK REVISION': 'REVISIONE RAPIDA',
    'Clear a named boss in under 45 seconds.': 'Sconfiggi un boss principale in meno di 45 secondi.',
    'TURN ONE OVER': 'VOLTA LA PRIMA PAGINA',
    'Finish the samurai page.': 'Completa la pagina dei samurai.',
    'THREE BAD DRAFTS': 'TRE BRUTTE BOZZE',
    'Finish the first three pages.': 'Completa le prime tre pagine.',
    'KING ARTHUR': 'RE ARTÙ',
    "Pull the Artist's impossible sword from the page.": 'Estrai dalla pagina la spada impossibile del Disegnatore.',
    'FINAL PROOF': 'PROVA FINALE',
    "Defeat the Final Editor's chosen revision.": 'Sconfiggi la revisione scelta dal Revisore Finale.',
    'FIVE NAMES CROSSED OUT': 'CINQUE NOMI CANCELLATI',
    'Defeat the five original named bosses.': 'Sconfiggi i cinque boss principali originali.',
    'THE PAGE REMAINS OPEN': 'LA PAGINA RESTA APERTA',
    'Reach the blank page.': 'Raggiungi la pagina bianca.',
    'FIVE PAGES LATER': 'CINQUE PAGINE DOPO',
    'Finish all five pages.': 'Completa tutte e cinque le pagine.',
    'CUT THAT OUT': 'TAGLIALO VIA',
    'Defeat the Head of Redaction.': 'Sconfiggi il Capo della Censura.',
    'MIRROR': 'SPECCHIO',
    'Face the proof made from your clean play.': 'Affronta la prova nata dalle tue mosse precise.',
    'RETURN TO SENDER': 'RESO AL MITTENTE',
    'Return three shots with a perfectly timed dash.': 'Respingi tre colpi con uno scatto perfettamente sincronizzato.',
    'Throw this chalk over cover. Its little cloud buys space.': 'Lancia il gesso sopra i ripari. La nuvola ti dà spazio.',
    'One straight carbon line can pass through a crowd. Then reload.': 'Una linea di carbone attraversa la folla. Poi ricarica.',
    'The fold comes back. Catch it for a faster next throw.': 'La piega torna. Afferrala per lanciare più rapidamente.',
    'I made that pencil too heavy. Wind up before you swing.': 'Ho fatto la matita troppo pesante. Carica prima di colpire.',
    'This ink travels fast. Leave yourself time to reload.': 'Questo inchiostro è veloce. Lascia tempo per ricaricare.',
    'A broad marker stroke works best when you stand close.': 'Un tratto largo di pennarello funziona meglio da vicino.',
    'The eraser removes incoming marks as well as enemies.': 'La gomma cancella nemici e colpi in arrivo.',
    'Bank that shot off a line. Straight ahead is not the only way.': 'Fai rimbalzare il colpo su una linea. Puoi aggirare i ripari.',
    'I may have overdrawn the sword. Its reach is the point.': 'Forse ho esagerato con la spada. Conta la sua portata.',
    'I left that edge too faint. I have redrawn the landing.': "Il bordo era troppo sbiadito. Ho ridisegnato l'appoggio.",
    'I see it now. Leave the next line visible, please.': 'Ora la vedo. Lascia ben visibile la prossima linea.',
    'That sketch came apart. I kept your place.': 'Lo schizzo si è disfatto. Ho conservato il tuo posto.',
    'Draw me back crooked if you must. I am still here.': 'Ridisegnami pure storto. Sono ancora qui.',
    'That tool began as a margin doodle. Try how it moves.': "Quell'arma era uno scarabocchio nel margine. Provala.",
    'I will. Keep drawing different answers.': 'Lo farò. Continua a disegnare risposte diverse.',
    'Back to a close line. Its timing matters more than its ink.': "Di nuovo da vicino. Il tempismo conta più dell'inchiostro.",
    'That pencil is slow. Start the swing before they close in.': 'La matita è lenta. Inizia il colpo prima che si avvicinino.',
    'A wider mark. Make room before you draw the next one.': 'Un segno più largo. Fai spazio prima del prossimo.',
    'Different tool, different rhythm. Show me what this one can do.': 'Arma diversa, ritmo diverso. Mostrami cosa sa fare.',
    'Then watch the space it leaves behind.': 'Allora guarda lo spazio che lascia.',
    'You changed that fight without my hand on the page.': 'Hai cambiato lo scontro senza la mia mano sulla pagina.',
    'I had to. You gave me room to move.': 'Dovevo farlo. Mi hai dato spazio per muovermi.',
    'You put that step where my first line failed.': 'Hai messo il gradino dove la mia linea non bastava.',
    'Then leave space for my next answer.': 'Allora lascia spazio alla mia prossima risposta.',
    'You tore the poster exactly where I left the paper weak.': 'Hai strappato il manifesto proprio nel punto debole.',
    'You drew the seam. I chose when to hit it.': 'Tu hai disegnato la cucitura. Io ho scelto quando colpire.',
    'I drew the star. You carried it farther than I planned.': "Ho disegnato la stella. Tu l'hai portata oltre i miei piani.",
    'The next connection can be ours.': 'Il prossimo collegamento può essere nostro.',
    'You found an answer I did not draw in the margin.': 'Hai trovato una risposta che non avevo disegnato.',
    'Leave the next one unfinished. I want to try.': 'Lascia incompleta la prossima. Voglio provare io.',
    'You asked me to change the page. That changes my plan too.': 'Mi hai chiesto di cambiare pagina. Cambia anche il mio piano.',
    'Good. Let me choose where the line goes next.': 'Bene. Lascia che scelga dove va la prossima linea.',
    'I drew you a new foothold. The next move is yours.': 'Ti ho disegnato un appoggio. La prossima mossa è tua.',
    'I see it. Do not erase it yet.': 'Lo vedo. Non cancellarlo ancora.',
    'I rubbed one out. You still have to cross this page.': 'Ne ho cancellato uno. La pagina devi ancora attraversarla tu.',
    'I know. Thanks for the breath.': 'Lo so. Grazie per il respiro.',
    'That mark was mine to warn you about. Watch its red outline.': 'Avrei dovuto avvertirti. Guarda il contorno rosso.',
    'I saw it late. I will move before it lands.': "L'ho visto tardi. Mi muoverò prima del colpo.",
    'Oh. You can hear me? Try moving. I will keep drawing.': 'Oh. Mi senti? Prova a muoverti. Continuo a disegnare.',
    'A small nod. That counts. The red circle is yours to cross out.': 'Basta un cenno. Cancella tu il cerchio rosso.',
    'I drew you a hat. The gun needs time to reload.': 'Ti ho disegnato un cappello. La pistola deve ricaricarsi.',
    'Six shots. Make a little space before the seventh.': 'Sei colpi. Fai spazio prima del settimo.',
    'The stars were meant to stay still. Sorry.': 'Le stelle dovevano stare ferme. Scusa.',
    'Bank the pulse off a line. You can reach around a shield.': "Fai rimbalzare l'impulso per aggirare lo scudo.",
    'Keep your head down. This page has very good aim.': "Abbassa la testa. Questa pagina ha un'ottima mira.",
    'When the long red line stops moving, leave it behind.': 'Quando la lunga linea rossa si ferma, esci dal segno.',
    'You have changed how I draw. One more page?': "Hai cambiato il mio modo di disegnare. Un'altra pagina?",
    'All right. I will leave the last word to you.': "Va bene. L'ultima parola è tua.",
    'Three cuts, then breathe. Dash past the red warning.': "Tre colpi, poi respira. Scatta oltre l'avviso rosso.",
    'The blue marks show a boss opening. Spend them carefully.': "I segni blu mostrano un'apertura del boss. Sfruttala bene.",
    'PAD-Y: nod back': 'PAD-Y: rispondi con un cenno',
    'E: nod back': 'E: rispondi con un cenno',
    'Out, then back. The fold remembers your hand.': 'Fuori e indietro. La piega ricorda la tua mano.',
    'F / J  send it, then watch it return': 'F / J: lancia e osserva il ritorno',
    'GEOMETRY / 04': 'GEOMETRIA / 04',
    'draw the diagram first!': 'prima disegna la figura!',
    'CIRCLES': 'CERCHI',
    'circumference = 2πr': 'circonferenza = 2πr',
    'area = πr²': 'area = πr²',
    'bring my compass back :)': 'riportami il compasso :)',
    'TRIANGLES': 'TRIANGOLI',
    'CIRCULAR MOTION': 'MOTO CIRCOLARE',
    'one turn = 2π radians': 'un giro = 2π radianti',
    'why is there a sword here?': "perché c'è una spada qui?",
    'INK PRESSURE': "PRESSIONE D'INCHIOSTRO",
    'force / area = pressure': 'forza / area = pressione',
    'a narrow tip cuts deeper': 'una punta stretta taglia più a fondo',
    'do not press through the page': 'non premere fino a bucare la pagina',
    'MOON GATE SKETCH': 'SCHIZZO DELLA PORTA LUNARE',
    'arc length = rθ': 'lunghezza arco = rθ',
    'watch the end of the blade': 'guarda la punta della lama',
    'there is a gap under the swing': "c'è un varco sotto il fendente",
    'PHYSICS / MOTION': 'FISICA / MOTO',
    'remember the units!': 'ricorda le unità!',
    'PROJECTILES': 'PROIETTILI',
    'ignore air resistance...': "ignora la resistenza dell'aria...",
    'FRICTION': 'ATTRITO',
    'N = mg  (level ground)': 'N = mg (terreno piano)',
    'keep coffee off the notebook': 'niente caffè sul quaderno',
    'THE TRAIN PROBLEM': 'IL PROBLEMA DEL TRENO',
    'distance = speed × time': 'distanza = velocità × tempo',
    'the train is not drawn yet': 'il treno non è ancora disegnato',
    'BOUNTY POSTERS': 'MANIFESTI DI TAGLIA',
    'three copies / one original': 'tre copie / un originale',
    'ink dries from the outside': "l'inchiostro asciuga dall'esterno",
    'circle the wet signature': 'cerchia la firma bagnata',
    'RAILWAY TIMETABLE': 'ORARIO FERROVIARIO',
    'arrival - departure = delay': 'arrivo - partenza = ritardo',
    '23:07 - 22:40 = 27 min': '23:07 - 22:40 = 27 min',
    'jump before the second whistle': 'salta prima del secondo fischio',
    'PHYSICS / GRAVITY': 'FISICA / GRAVITÀ',
    'double r  →  one quarter F': 'r doppio → F un quarto',
    'space was not empty after all': 'lo spazio non era vuoto, dopotutto',
    'ORBITAL NOTES': 'APPUNTI ORBITALI',
    'the satellite needs batteries': 'il satellite ha bisogno di batterie',
    'VECTORS': 'VETTORI',
    'write the direction too!': 'scrivi anche la direzione!',
    'FREE FALL': 'CADUTA LIBERA',
    'Earth: g ≈ 9.8 m/s²': 'Terra: g ≈ 9.8 m/s²',
    'SATELLITE POWER': 'ENERGIA SATELLITARE',
    'the panels face the light': 'i pannelli sono rivolti alla luce',
    'the left one is folded wrong': 'quello sinistro è piegato male',
    'REENTRY ERROR': 'ERRORE DI RIENTRO',
    'heat ∝ speed²': 'calore ∝ velocità²',
    'the suit is too large': 'la tuta è troppo grande',
    'erase the pressure seal again?': 'cancellare di nuovo il sigillo?',
    'OPTICS / REFLECTION': 'OTTICA / RIFLESSIONE',
    'incident angle = reflected angle': 'angolo incidente = angolo riflesso',
    'the mirror sees everything': 'lo specchio vede tutto',
    'BINARY NUMBERS': 'NUMERI BINARI',
    '13 (decimal) = 1101 (binary)': '13 (decimale) = 1101 (binario)',
    'is this a secret message?': 'è un messaggio segreto?',
    'COORDINATES': 'COORDINATE',
    'connect the dots': 'collega i punti',
    'LENSES': 'LENTI',
    'converging lens: f > 0': 'lente convergente: f > 0',
    'I cannot see the blackboard': 'non vedo la lavagna',
    'CARBON COPIES': 'COPIE CARBONE',
    'copy 03 ≠ original': 'copia 03 ≠ originale',
    'pressure transfers the mark': 'la pressione trasferisce il segno',
    'the folder is still running': 'la cartella corre ancora',
    'EVIDENCE VAULT': 'ARCHIVIO DELLE PROVE',
    'file 04 / access denied': 'fascicolo 04 / accesso negato',
    'one stamp, two shadows': 'un timbro, due ombre',
    'follow the red line upstairs': 'segui la linea rossa al piano superiore',
    'FINAL LESSON / REVISION': 'ULTIMA LEZIONE / REVISIONE',
    'show your working!': 'mostra i passaggi!',
    "NEWTON'S THIRD LAW": 'TERZA LEGGE DI NEWTON',
    'action and reaction': 'azione e reazione',
    'the paper hits back': 'la carta colpisce a sua volta',
    'EQUATIONS': 'EQUAZIONI',
    'revise it; do not start over': 'correggi senza ricominciare',
    'IS CLASS OVER?': 'È FINITA LA LEZIONE?',
    'answer = ?': 'risposta = ?',
    'the back of this page is blank': 'il retro di questa pagina è bianco',
    'wait for the bell': 'aspetta la campanella',
    'REVISION HISTORY': 'CRONOLOGIA DELLE REVISIONI',
    'the first answer is crossed out': 'la prima risposta è cancellata',
    'you can keep the crooked one': 'puoi tenere quella storta',
    'LAST CORRIDOR': 'ULTIMO CORRIDOIO',
    'jump over what was erased': 'salta ciò che è stato cancellato',
    'turning the page is your answer': 'voltare pagina è la tua risposta',
    'boring lesson': 'lezione noiosa',
    'do not tear': 'non strappare',
    'turn me over': 'voltami',
    'ink on my hand': 'inchiostro sulla mano',
    'first attempt': 'primo tentativo',
    'bamboo exercise': 'esercizio di bambù',
    'broken footbridge': 'passerella rotta',
    'ink dojo': "dojo d'inchiostro",
    'roof of the shrine': 'tetto del santuario',
    'lantern festival': 'festa delle lanterne',
    'rejected warriors': 'guerrieri scartati',
    'moon gate': 'porta lunare',
    'the sword lesson': 'la lezione della spada',
    'after the duel': 'dopo il duello',
    'a quieter line': 'una linea più quieta',
    'end of the scroll': 'fine del rotolo',
    'railway timetable': 'orario ferroviario',
    'wanted / alive?': 'ricercato / vivo?',
    'six shots only': 'solo sei colpi',
    'coffee spill town': 'città del caffè versato',
    'beyond the red rule': 'oltre la linea rossa',
    'empty saloon': 'saloon vuoto',
    'windmill repairs': 'riparazione del mulino',
    'cactus country': 'terra dei cactus',
    'water tower': "torre dell'acqua",
    'midnight freight': 'merci di mezzanotte',
    'bounty archive': 'archivio delle taglie',
    'last station': 'ultima stazione',
    'train home': 'treno per casa',
    'missed the train': 'treno perso',
    'gravity homework': 'compiti di gravità',
    'failed launch': 'lancio fallito',
    'orbit laboratory': 'laboratorio orbitale',
    'zero garden': 'giardino zero',
    'telescope repairs': 'riparazione del telescopio',
    'debris forecast': 'previsioni di detriti',
    'moon survey': 'rilievo lunare',
    'radio silence': 'silenzio radio',
    'null chamber': 'camera del vuoto',
    'star nursery': 'vivaio stellare',
    'wrong equation': 'equazione sbagliata',
    'escape velocity': 'velocità di fuga',
    'observatory': 'osservatorio',
    'erased orbit': 'orbita cancellata',
    'the big mistake': 'il grande errore',
    'one giant baby': 'un bimbo gigante',
    'back to earth': 'ritorno sulla Terra',
    'end of experiment': "fine dell'esperimento",
    'classified homework': 'compiti segreti',
    'checkpoint sketch': 'schizzo del punto di controllo',
    'service tunnel': 'tunnel di servizio',
    'carbon copy office': 'ufficio copie carbone',
    'missing personnel': 'personale scomparso',
    'rooftop surveillance': 'sorveglianza sul tetto',
    'dead letter drop': 'consegna segreta',
    'the archive': "l'archivio",
    'office floor plan': "pianta dell'ufficio",
    'director of redaction': 'capo della censura',
    'case closed': 'caso chiuso',
    'unsigned report': 'rapporto senza firma',
    'last lesson': 'ultima lezione',
    'unfinished answer': 'risposta incompleta',
    'discard pile': 'pila degli scarti',
    'paper cemetery': 'cimitero di carta',
    'what survived': 'ciò che è sopravvissuto',
    'the rebels': 'i ribelli',
    'wrong endings': 'finali sbagliati',
    'your handwriting': 'la tua calligrafia',
    'the final question': "l'ultima domanda",
    'a new ending': 'un nuovo finale',
    'keep drawing': 'continua a disegnare',
    'after the bell': 'dopo la campanella',
    'do not sharpen the sword': 'non temperare la spada',
    'bamboo bends / ink does not': "il bambù si piega / l'inchiostro no",
    'balance before speed': 'equilibrio prima della velocità',
    'three cuts, then breathe': 'tre colpi, poi respira',
    'depart 23:07 / never on time': 'partenza 23:07 / mai in orario',
    'reward: one clean sheet': 'ricompensa: un foglio pulito',
    'wind from the coffee stain': 'vento dalla macchia di caffè',
    'draw another way out': "disegna un'altra via d'uscita",
    'mass = mistake / time²': 'massa = errore / tempo²',
    'signal lost ... try again': 'segnale perso ... riprova',
    'oxygen? forgot that part': 'ossigeno? dimenticato',
    'the moon is drifting': 'la luna sta andando alla deriva',
    'copy 03 / original missing': 'copia 03 / originale scomparso',
    'NO NAMES PAST THIS LINE': 'NESSUN NOME OLTRE QUESTA LINEA',
    'blind spot: roof access': 'punto cieco: accesso al tetto',
    'evidence must not be erased': 'le prove non vanno cancellate',
    'not every mistake needs fixing': 'non ogni errore va corretto',
    'this answer is yours': 'questa risposta è tua',
    'I kept the first version': 'ho conservato la prima versione',
    'the last word is unwritten': "l'ultima parola non è scritta",
    'revised after the bell': 'rivisto dopo la campanella',
    'roof route?': 'percorso sul tetto?',
    'wind ->': 'vento ->',
    'a different face in every lantern': 'un volto diverso in ogni lanterna',
    'do not draw the moon twice': 'non disegnare la luna due volte',
    'WANTED': 'RICERCATO',
    'for stealing my lunch': 'per aver rubato il mio pranzo',
    'next stop: wrong side of the page': 'prossima fermata: lato sbagliato della pagina',
    'water / probably coffee': 'acqua / probabilmente caffè',
    'SALOON': 'SALOON',
    'closed during maths': 'chiuso durante matematica',
    'the missing moon goes here ->': 'la luna mancante va qui ->',
    'launch postponed (again)': 'lancio rinviato (di nuovo)',
    'someone is looking back': 'qualcuno ricambia lo sguardo',
    'debris / do not stand here': 'detriti / non stare qui',
    'ORIGINAL / COPY / COPY?': 'ORIGINALE / COPIA / COPIA?',
    'names removed by the Director': 'nomi rimossi dal Direttore',
    'my route / his blind spot': 'il mio percorso / il suo punto cieco',
    'it follows the line, not you': 'segue la linea, non te',
    'FILE 04 / missing original': 'FASCICOLO 04 / originale scomparso',
    'archive route / guard crossed out': "via dell'archivio / guardia cancellata",
    'keep the crooked one': 'conserva quella storta',
    'some endings are only drafts': 'alcuni finali sono solo bozze',
    'your turn to answer': 'tocca a te rispondere',
    'no perfect version': 'nessuna versione perfetta',
    'SWORD': 'SPADA',
    'TICKET': 'BIGLIETTO',
    'ORBIT': 'ORBITA',
    'FILE': 'FASCICOLO',
    'keep one answer': 'conserva una risposta',
    'a line can still change direction': 'una linea può ancora cambiare direzione',
    'unfinished': 'incompleto',
    'check this': 'controlla questo',
    'needs another line': "serve un'altra linea",
    'not on the test': 'non è nella verifica',
    'TRAIN / PAGE': 'TRENO / PAGINA',
    'COPY 00': 'COPIA 00',
    'PAGE I  /  CUT': 'PAGINA I / TAGLIA',
    'PAGE II /  AIM': 'PAGINA II / MIRA',
    'PAGE III / FLOAT': 'PAGINA III / FLUTTUA',
    'PAGE IV / HIDE': 'PAGINA IV / NASCONDITI',
    '03    ERASED': '03    CANCELLATO',
    'BRIDGE / TRY 2': 'PONTE / TENTATIVO 2',
    'THE BLADE REMEMBERS': 'LA LAMA RICORDA',
    'A TREE I COULD NOT ERASE': 'UN ALBERO CHE NON RIUSCIVO A CANCELLARE',
    'FESTIVAL AFTER CLASS': 'FESTA DOPO LA LEZIONE',
    'THE ARC IS NOT A WALL': "L'ARCO NON È UN MURO",
    'MISSED THE FIRST TRAIN': 'PERSO IL PRIMO TRENO',
    'CLOSED FOR HOMEWORK': 'CHIUSO PER COMPITI',
    'THE WIND GOT BORED': 'IL VENTO SI ANNOIAVA',
    'WATER? / COFFEE': 'ACQUA? / CAFFÈ',
    'LAST TRAIN / 23:07': 'ULTIMO TRENO / 23:07',
    'GRAVITY / PLEASE WORK': 'GRAVITÀ / FUNZIONA, TI PREGO',
    'LAUNCH ATTEMPT 04': 'TENTATIVO DI LANCIO 04',
    'SOME ASSEMBLY REQUIRED': 'QUALCHE PEZZO DA MONTARE',
    'SIGNAL LOST': 'SEGNALE PERSO',
    'NOT TO SCALE': 'NON IN SCALA',
    'YOU ARE FILE 00': 'SEI IL FASCICOLO 00',
    'FILE 03 / ORIGINAL?': 'FASCICOLO 03 / ORIGINALE?',
    'THE SECOND COPY MOVES': 'LA SECONDA COPIA SI MUOVE',
    'BLIND SPOT': 'PUNTO CIECO',
    'EVIDENCE / DO NOT ERASE': 'PROVE / NON CANCELLARE',
    'NO ONE DREW THIS THREAD': 'NESSUNO HA DISEGNATO QUESTO FILO',
    'ONE LAST LESSON': "UN'ULTIMA LEZIONE",
    'ANSWERS IN THE MARGIN': 'RISPOSTE NEL MARGINE',
    'THE OTHER FOUR PAGES': 'LE ALTRE QUATTRO PAGINE',
    'THE OLD VERSIONS': 'LE VECCHIE VERSIONI',
    'KEEP THE WRONG ANSWER': 'CONSERVA LA RISPOSTA SBAGLIATA',
    'YOUR NEXT LINE': 'LA TUA PROSSIMA LINEA',
    'CLASSIFIED / carbon copy': 'RISERVATO / copia carbone',
    'F = ma ... maybe': 'F = ma ... forse',
    'x + y = another problem': 'x + y = un altro problema',
    'DO NOT ERASE THE HERO': "NON CANCELLARE L'EROE",
    'THE ARTIST: A small revision. Next wave in a moment.': "IL DISEGNATORE: Piccola revisione. Tra poco un'altra ondata.",
    'the ink is still wet': "l'inchiostro è ancora bagnato",
    'FIELD KNIFE': 'COLTELLO DA CAMPO',
    'rapid chain · execute wounded targets': 'combo rapida · finisci i bersagli feriti',
    'quick, precise fire · light recoil': 'fuoco rapido e preciso · rinculo leggero',
    'tight grouping · controlled shove': 'rosata stretta · spinta controllata',
    'third cut fires a piercing wave': "il terzo colpo lancia un'onda perforante",
    'stay close · mark twice · cash out': 'resta vicino · segna due volte · colpisci',
    'eight fast shots · quiet · reload often': 'otto colpi rapidi · silenziosi · ricarica spesso',
    'tight burst · controlled shove': 'raffica stretta · spinta controllata',
    'every stroke returns as a delayed trace': 'ogni colpo ritorna come una traccia ritardata',
    'two ricochets · hold to fire': 'due rimbalzi · tieni premuto per sparare',
    'lob two capsules · small paper burst': 'lancia due capsule · piccola esplosione di carta',
    'A / D   ·   Left / Right': 'A / D · ← / →',
    'the roots are lines too': 'anche le radici sono linee',
    'the page tears down here': 'qui la pagina si strappa',
    'gravity homework / use the working lines': 'compiti di gravità / usa le linee dei passaggi',
    'original above / carbon copy below': 'originale sopra / copia carbone sotto',
    'the answer climbs out of the margin': 'la risposta sale fuori dal margine',
    '01 / FALSE ID': '01 / FALSA IDENTITÀ',
    'The agent commits to three shots. Then reloads.': "L'agente spara tre volte. Poi ricarica.",
    '02 / CARBON CROSSFIRE': '02 / FUOCO INCROCIATO CARBONE',
    'Climb the ink line; drop behind the shield.': "Sali sulla linea d'inchiostro; scendi dietro lo scudo.",
    '03 / ROOFTOP REVISION': '03 / REVISIONE SUL TETTO',
    'Leave the violet column before the ink falls.': "Esci dalla colonna viola prima che cada l'inchiostro.",
    '04 / THE OFFICE BITES': "04 / L'UFFICIO MORDE",
    'Deal with the turret before the next copy.': 'Elimina la torretta prima della prossima copia.',
    '05 / EVIDENCE VAULT': '05 / ARCHIVIO DELLE PROVE',
    'Copies guard the files. Break their line of sight.': 'Le copie sorvegliano i fascicoli. Spezza la loro linea di tiro.',
    'THE HEAD OF REDACTION': 'IL CAPO DELLA CENSURA',
    'Jump his baton. Leave the firing lines. Strike the exposed core.': 'Salta il manganello. Lascia le linee di tiro. Colpisci il nucleo esposto.',
    '01 / WRONG CLASS': '01 / CLASSE SBAGLIATA',
    'Five pages of enemies. One small stick figure.': 'Cinque pagine di nemici. Un piccolo omino.',
    '02 / ERASED ANSWERS': '02 / RISPOSTE CANCELLATE',
    'A platform can save you. Watch the eraser.': 'Una piattaforma può salvarti. Guarda la gomma.',
    '03 / MARGIN REVOLT': '03 / RIVOLTA DEL MARGINE',
    'Jump the gold rake, then break the ranged line.': 'Salta il rastrello dorato, poi spezza la linea dei tiratori.',
    '04 / THE LAST CROSSOUT': "04 / L'ULTIMA CANCELLAZIONE",
    'The blue trail stays hot. Cross it in the air.': 'La scia blu resta rovente. Attraversala in aria.',
    '05 / UNFINISHED CORRIDOR': '05 / CORRIDOIO INCOMPLETO',
    'Old drafts can still fight. Move between their styles.': 'Le vecchie bozze combattono ancora. Adattati ai loro stili.',
    'THE REJECTED HERO': "L'EROE SCARTATO",
    'Read your old draft. Attack when its guard drops.': 'Leggi la vecchia bozza. Attacca quando abbassa la guardia.',
    'THE REJECTED CAST': 'IL CAST SCARTATO',
    'I left my first attempts here. They do not want to be forgotten.': 'Ho lasciato qui i primi tentativi. Non vogliono essere dimenticati.',
    'You gave the old drawing a second chance. Keep what it taught you.': 'Hai dato una seconda possibilità al vecchio disegno. Conserva ciò che ti ha insegnato.',
    'THE BOUNTY IN THE MARGIN': 'LA TAGLIA NEL MARGINE',
    'That scrap has a bounty on it. Shall I draw the ones hunting it?': "C'è una taglia su quel ritaglio. Disegno chi lo cerca?",
    'I was going to write a price. You made it a name instead.': 'Volevo scrivere un prezzo. Tu gli hai dato un nome.',
    'THE FAILED EXPERIMENT': "L'ESPERIMENTO FALLITO",
    'This experiment escaped the calculation. Help me finish it?': "L'esperimento è sfuggito al calcolo. Mi aiuti a finirlo?",
    'The mistake was useful. I will leave your answer in the margin.': "L'errore è stato utile. Lascio la tua risposta nel margine.",
    'THE CARBON ARCHIVE': "L'ARCHIVIO CARBONE",
    'That file is being watched. Open it and they will know you are here.': 'Il fascicolo è sorvegliato. Aprilo e sapranno che sei qui.',
    'A copy can hide a name. It cannot hide what you just did.': 'Una copia può nascondere un nome. Non ciò che hai appena fatto.',
    'THE UNFINISHED ANSWER': 'LA RISPOSTA INCOMPLETA',
    'These are the endings I threw away. Can you face them?': 'Questi sono i finali che ho scartato. Puoi affrontarli?',
    'All right. Your answer stays. I am putting the eraser down.': 'Va bene. La tua risposta resta. Metto via la gomma.',
    'REDRAW PENCIL': 'MATITA DI REVISIONE',
    'ORBITAL RUBBER BAND': 'ELASTICO ORBITALE',
    'Two extra rebounds for Orbit Pulse / Rubber Band.': 'Due rimbalzi extra per Impulso Orbitale / Elastico.',
    'Ricochet shots bounce twice more.': 'I proiettili rimbalzano due volte in più.',
    'THE CLOUD HEART': 'IL CUORE DELLE NUVOLE',
    'SKYWARD RUNE': 'RUNA DEL CIELO',
    'Air +35%; dash -0.08s; edge grace +0.04s.': 'Controllo in aria +35%; scatto -0,08 s; margine del salto +0,04 s.',
    'Permanent movement rune. Stacks with Paper Kite, Second Thought and Revision Rhythm.': 'Runa di movimento permanente. Si somma ad Aquilone di Carta, Secondo Pensiero e Ritmo di Revisione.',
    'THE FOLDED BASTION': 'IL BASTIONE PIEGATO',
    'BASTION RUNE': 'RUNA DEL BASTIONE',
    'Knockback +30%; spread -10%; cannon reload -10%.': 'Spinta +30%; dispersione -10%; ricarica cannone -10%.',
    'Permanent weapon rune. Works with Scattergun and Null / Eraser Cannon across pages.': "Runa d'arma permanente. Funziona con il fucile a pallettoni e il Cannone Vuoto / Gomma su ogni pagina.",
    'THE CARBON ORIGINAL': "L'ORIGINALE CARBONE",
    'ECHO RUNE': "RUNA DELL'ECO",
    'Sidearm: speed +25%; pierce +1; reload -10%.': 'Pistola: velocità +25%; perforazione +1; ricarica -10%.',
    'Permanent sidearm rune. Its piercing stacks with Through Ticket; its speed stacks with Fast Ink.': 'Runa di pistola permanente. La perforazione si somma a Biglietto di Passaggio; la velocità a Inchiostro Rapido.',
    'SECRET / ABOVE THE CLOUDS': 'SEGRETO / SOPRA LE NUVOLE',
    'SECRET / THE FOLDED REFUGE': 'SEGRETO / IL RIFUGIO PIEGATO',
    'SECRET / THE MISSING ORIGINAL': "SEGRETO / L'ORIGINALE MANCANTE",
    'SECRET UP / optional rune / return to the road below': 'SEGRETO IN ALTO / runa facoltativa / torna al percorso in basso',
    'quiet margin / explore above or keep the road': 'margine quieto / esplora in alto o segui il percorso',
    'E  challenge the cloud guardian / optional': 'E / sfida il guardiano delle nuvole (facoltativo)',
    'E / SMALL GUARDIAN': 'E / PICCOLO GUARDIANO',
    'One little guardian. Jump its arc; strike the stuck blade.': "Un piccolo guardiano. Salta l'arco; colpisci la lama bloccata.",
    'Rune uncovered. E to keep it; its numbers stay across pages.': 'Runa scoperta. E per conservarla; gli effetti restano.',
    'E  unfold the lower mark': 'E / apri il segno inferiore',
    'E  rub the original signature': 'E / strofina la firma originale',
    'E  connect the second mark': 'E / collega il secondo segno',
    'E  ASK THE ARTIST TO REDRAW ONE HEART (once this boss)': 'E / +1 cuore (una volta per boss)',
    'Hold your line. I can redraw one heart. Finish the fight yourself.': 'Tieni la linea. Posso ridisegnare un cuore. Finisci tu lo scontro.',
    'THE ARTIST: +1 heart. The next opening is yours.': 'IL DISEGNATORE: +1 cuore. La prossima apertura è tua.',
    '< back': '< indietro',
    'BAD LANDING': 'ATTERRAGGIO SBAGLIATO',
    'CLEAN MARGIN': 'MARGINE PULITO',
    'COOLING': 'RAFFREDDAMENTO',
    'DEAD / ALIVE': 'MORTO / VIVO',
    'DEAD OR ALIVE — FOUR POSTERS, FOUR LINES': 'MORTO O VIVO — QUATTRO MANIFESTI, QUATTRO LINEE',
    'EVADE THE ORDER — STRIKE THE EXPOSED CARBON CORE': "SCHIVA L'ORDINE — COLPISCI IL NUCLEO CARBONE ESPOSTO",
    'EXPRESS REVISION — IT COMES BACK': 'REVISIONE ESPRESSA — RITORNA',
    'II / RETRACE': 'II / RIPERCORRI',
    'JUMP THE RAIL — HIT THE REAR OR THE OPEN ENGINE': 'SALTA IL BINARIO — COLPISCI IL RETRO O IL MOTORE APERTO',
    'JUMP THE RED ARC — STRIKE WHILE THE BLADE IS STUCK': "SALTA L'ARCO ROSSO — COLPISCI QUANDO LA LAMA È BLOCCATA",
    'LET THE SHIELDS GO — HIT THE EXPOSED CORE': 'LASCIA PASSARE GLI SCUDI — COLPISCI IL NUCLEO ESPOSTO',
    'LOOSE LINES': 'LINEE ALLENTATE',
    'LOOSE — ERASE NOW': 'ALLENTATO — CANCELLA ORA',
    'NEEDLE STUCK — HIT': 'AGO BLOCCATO — COLPISCI',
    'OPEN': 'APERTO',
    'PUNCHED': 'PERFORATO',
    'RE-FILE': 'RIARCHIVIA',
    'READ THE DRAFT — ATTACK WHEN ITS GUARD DROPS': 'LEGGI LA BOZZA — ATTACCA QUANDO ABBASSA LA GUARDIA',
    'RETURN SERVICE': 'CORSA DI RITORNO',
    'SECOND DRAFT — THE ARC COMES BACK': "SECONDA BOZZA — L'ARCO RITORNA",
    'SIGHT LOCKED': 'MIRA BLOCCATA',
    'STAMP JAMMED': 'TIMBRO INCEPPATO',
    'STUCK': 'BLOCCATO',
    'TAB EXPOSED': 'LINGUETTA ESPOSTA',
    'THE BINDER CLIP IS OPEN': 'LA CLIP È APERTA',
    'THE WET INK IS REAL — SHOOT BEFORE THE DRAW': "L'INCHIOSTRO BAGNATO È REALE — SPARA PRIMA CHE ESTRAIGA",
    'THIS DRAWING IS UNFAIR ON PURPOSE': 'QUESTO DISEGNO È INGIUSTO DI PROPOSITO',
    'THREE SHOTS': 'TRE COLPI',
    'UNCRUMPLED': 'SPIANATO',
    'copy...': 'copia...',
    'empty': 'vuoto',
    'new centre': 'nuovo centro',
    'retracing': 'ripercorre',
    'smoke': 'fumo',
    'soft side exposed': 'lato debole esposto',
    '<<< CROSS OUT': '<<< CANCELLA',
    'CROSS OUT >>>': 'CANCELLA >>>',
    'ALL ABOARD — JUMP!': 'IN CARROZZA — SALTA!',
    'ARM SWEEP': 'SPAZZATA DEL BRACCIO',
    'BIG FOOT': 'PIEDE GIGANTE',
    'COPY BOTH SIDES': 'COPIA ENTRAMBI I LATI',
    'CORE EXPOSED': 'NUCLEO ESPOSTO',
    'CORE OPEN': 'NUCLEO APERTO',
    'CORE SEALED': 'NUCLEO SIGILLATO',
    'CROSS OUT': 'CANCELLA',
    'ENGINE OPEN': 'MOTORE APERTO',
    'ERASE BELOW': 'CANCELLA SOTTO',
    'FIND THE CLEAN MARGIN': 'TROVA IL MARGINE PULITO',
    'FIRING ORDER — LEAVE THE LINES': 'ORDINE DI FUOCO — LASCIA LE LINEE',
    'GUARD UP': 'GUARDIA ALTA',
    'INK ARC': "ARCO D'INCHIOSTRO",
    'JUMP THE ARC': "SALTA L'ARCO",
    'JUMP THE LOW SWEEP': 'SALTA LA SPAZZATA BASSA',
    'LEAVE THE RED X': 'LASCIA LA X ROSSA',
    'MARGINS CLOSE': 'I MARGINI SI CHIUDONO',
    'MOONS AWAY': 'LE LUNE SI ALLONTANANO',
    'MOVE — REDACTION STAMP': 'SPOSTATI — TIMBRO DI CENSURA',
    'ORDER II — THE FLOOR IS CLASSIFIED': 'ORDINE II — IL PAVIMENTO È RISERVATO',
    'ORDER III — CARBON FIRING SQUAD': 'ORDINE III — PLOTONE CARBONE',
    'ORDER SEALED': 'ORDINE SIGILLATO',
    'PROOF SHOTS': 'COLPI DI PROVA',
    'RETURN TRAIN — JUMP!': 'TRENO DI RITORNO — SALTA!',
    'SECOND CUT': 'SECONDO TAGLIO',
    'STAMP BELOW': 'TIMBRA SOTTO',
    'THE ARC RETURNS': "L'ARCO RITORNA",
    'THE ARTIST: Nice line.': 'IL DISEGNATORE: Bella linea.',
    'WHOLE PAGE': 'INTERA PAGINA',
    'YOUR TURN': 'TOCCA A TE',
    'AIRLOCK / NO SIGNAL': 'CAMERA STAGNA / NESSUN SEGNALE',
    'AIRLOCK CLOSED / return to the star pad': 'CAMERA STAGNA CHIUSA / torna alla base della stella',
    'CONNECTION HELD': 'COLLEGAMENTO STABILE',
    'E / CHARGE': 'E / CARICA',
    'E / CONNECT': 'E / COLLEGA',
    'JUMP / THEN DASH  >>': 'SALTA / POI SCATTA >>',
    'MARGIN / CLOSED': 'MARGINE / CHIUSO',
    'REVISED': 'RIVISTO',
    'SHIFT / K  RIGHT': 'SHIFT / K DESTRA',
    'TEAR ALONG  - - -': 'STRAPPA LUNGO - - -',
    'TORN': 'STRAPPATO',
    'THE ARTIST: A good tear. I should have left that edge rough.': 'IL DISEGNATORE: Bello strappo. Dovevo lasciare il bordo ruvido.',
    'THE ARTIST: Carry this spark to the dish before it fades.': "IL DISEGNATORE: Porta la scintilla all'antenna prima che svanisca.",
    'THE ARTIST: Connected. That airlock was a bad drawing.': 'IL DISEGNATORE: Collegato. Quella camera stagna era disegnata male.',
    'THE ARTIST: The star faded. I can charge it again.': 'IL DISEGNATORE: La stella si è spenta. Posso ricaricarla.',
    'E  charge the loose star / 15 seconds': 'E / carica la stella libera / 15 secondi',
    'E  connect the star to the dish': "E / collega la stella all'antenna",
    'E  ask about the rubbed-out figure': 'E / chiedi della figura cancellata',
    'E  ask why the moon has two outlines': 'E / chiedi perché la luna ha due contorni',
    "E  unfold the timetable's corner": "E / apri l'angolo dell'orario",
    'Lost Sketches = discarded ideas.\nKeep one. Its trick stays across pages.': 'Gli Schizzi Perduti sono idee scartate.\nLa loro tecnica resta su ogni pagina.',
    'The original left a face.\nKeep the badge; I can draw its rifle.': "L'originale ha lasciato un volto.\nConserva il distintivo; posso disegnare il suo fucile.",
    'a named drawing — three fresh heart-marks': 'un disegno speciale — tre segni di cuore freschi',
    'crossed out — fresh ink at the next fight': 'cancellato — inchiostro fresco al prossimo scontro',
    'the graphite cracks — a new pattern': 'la grafite si spezza — un nuovo schema',
    'CLOUD KITE': 'AQUILONE DELLE NUVOLE',
    'JUMP THE GUST. LEAVE THE TAIL MARK.': 'SALTA LA RAFFICA. LASCIA IL SEGNO DELLA CODA.',
    'CLEAR THE ROOM': 'LIBERA LA STANZA',
    'You crossed the last drawings easily. I am adding one more opponent.': 'Hai superato facilmente gli ultimi disegni. Aggiungo un avversario.',
    'That drawing caught you twice. I will watch your ink more closely.': "Quel disegno ti ha colpito due volte. Terrò d'occhio il tuo inchiostro.",
    'I saw you struggle with this drawing. Here is a stronger tool. Q tries it; your weapon stays.': "Hai avuto difficoltà. Ecco un'arma più forte. Q per provarla; la tua resta.",
    'I watched your last fight. Here is another range to try. Q changes tools; your weapon stays.': "Dopo lo scontro, ecco un'arma per un'altra distanza. Q per cambiarla; la tua resta.",
    'Your ink is almost gone. I will redraw one heart. Keep reading the red lines.': "L'inchiostro sta finendo. Ridisegno un cuore. Continua a guardare i segni rossi.",
    'Drawn for this page. Q swaps back.': "Disegnata per questa pagina. Q per tornare all'arma precedente.",
    'E / DRAW': 'E / DISEGNA',
    'E  ASK THE ARTIST TO REDRAW ONE HEART (once this room)': 'E / +1 cuore (una volta per stanza)',
    'A kite wakes in the clouds. Its wind stays low; the tail mark does not move.': 'Un aquilone si sveglia tra le nuvole. Il vento resta basso; il segno della coda è fermo.',
    'E / lift the loose paper corner': "E / solleva l'angolo libero della carta",
    'lift the loose corner': "solleva l'angolo libero",
    'ABOVE THE CLOUDS': 'SOPRA LE NUVOLE',
    'THE FOLDED REFUGE': 'IL RIFUGIO PIEGATO',
    'THE MISSING ORIGINAL': "L'ORIGINALE MANCANTE",
    '01 / THE FIRST CUT': '01 / IL PRIMO TAGLIO',
    '02 / PAPER AMBUSH': '02 / IMBOSCATA DI CARTA',
    '03 / LANTERN PROCESSION': '03 / CORTEO DI LANTERNE',
    '01 / HIGH NOON': '01 / MEZZOGIORNO DI FUOCO',
    '02 / THREE NEEDLES': '02 / TRE AGHI',
    '01 / AIRLOCK PATROL': '01 / PATTUGLIA DELLA CAMERA STAGNA',
    '02 / DEBRIS FIELD': '02 / CAMPO DI DETRITI',
    '04 / CORRECTION BAY': '04 / STANZA DELLE CORREZIONI',
    'Let the blade pass. Cut during recovery.': 'Lascia passare la lama. Colpisci durante il recupero.',
    'The drone drops after firing. Go behind the ruler.': 'Il drone scende dopo il colpo. Passa dietro il righello.',
    'Clear the low threat before chasing the lantern.': 'Elimina la minaccia in basso prima di inseguire la lanterna.',
    'Keep space. Jump the rolling tumbleweed.': 'Mantieni la distanza. Salta il cespuglio rotolante.',
    'Read the cactus fan; move between volleys.': 'Guarda i colpi del cactus; muoviti tra le raffiche.',
    'The bot braces before ramming. Let it commit.': 'Il robot si prepara prima di caricare. Aspetta la mossa.',
    'Jump the hound; close on the turret during reload.': 'Salta il segugio; avvicinati alla torretta mentre ricarica.',
    'Watch the erased floor. Save a landing line.': "Guarda il pavimento cancellato. Conserva un punto d'atterraggio.",
    'THE MOON RONIN': 'IL RONIN LUNARE',
    'WANTED: FAILED ALIVE': 'RICERCATO: FALLITO VIVO',
    'THE MIDNIGHT EXPRESS': "L'ESPRESSO DI MEZZANOTTE",
    'ORBITAL SENTINEL': 'SENTINELLA ORBITALE',
    'THE LOST EXPEDITION': 'LA SPEDIZIONE PERDUTA',
    'JUMP THE ARC — STRIKE THE STUCK BLADE': "SALTA L'ARCO — COLPISCI LA LAMA BLOCCATA",
    'THREE ATTEMPTS — THE ARTIST CHEATS LAST': 'TRE TENTATIVI — ALLA FINE IL DISEGNATORE BARA',
    'THE FOLDED SHRINE': 'IL SANTUARIO PIEGATO',
    'THE WATER TOWER': "LA TORRE DELL'ACQUA",
    'THE ORRERY': 'IL PLANETARIO',
    'AIRLOCK? / draw one later': 'CAMERA STAGNA? / disegnala dopo',
    'BAMBOO? / definitely bamboo': 'BAMBÙ? / sicuramente bambù',
    'CLASSIFIED / turn over': 'RISERVATO / volta pagina',
    'DASH INTO A SHOT / return it at the last moment': "SCATTA NEL COLPO / respingilo all'ultimo istante",
    'DUST DEVIL  ^': 'VORTICE DI POLVERE ^',
    'ERASER BELOW: take the upper ink': 'GOMMA IN BASSO: usa la linea superiore',
    'LAST TRAIN / no timetable': 'ULTIMO TRENO / nessun orario',
    'LEAKING STAR INK': 'INCHIOSTRO STELLARE CHE COLA',
    'MOON GATE': 'PORTA LUNARE',
    'NEW PAGE. NEW HAT.': 'NUOVA PAGINA. NUOVO CAPPELLO.',
    'ORBITAL WALKWAY / DO NOT ERASE': 'PASSAGGIO ORBITALE / NON CANCELLARE',
    'OVERSIZED EXPEDITION SUIT': 'TUTA DA SPEDIZIONE TROPPO GRANDE',
    'RED LINE: wait, jump, or dash through': 'LINEA ROSSA: aspetta, salta o scatta attraverso',
    'SALOON SPILL / still slippery': 'CAFFÈ VERSATO / ancora scivoloso',
    'SIX-SHOOTER ->': 'SEI COLPI ->',
    'WANTED: whoever drew the goblin': 'RICERCATO: chi ha disegnato il goblin',
    'WHY DID I DRAW IT THAT BIG?': "PERCHÉ L'HO DISEGNATO COSÌ GRANDE?",
    'You may turn the page.': 'Puoi voltare pagina.',
    'a creature assembled from everything the eraser missed': 'una creatura fatta di ciò che la gomma ha mancato',
    'a fierce monster with an apologetic smile': 'un mostro feroce con un sorriso dispiaciuto',
    'a folded shield rejected for being too stubborn': 'uno scudo piegato, scartato perché troppo ostinato',
    'a handle? face the stain and let it settle': 'un manico? guarda la macchia e aspetta che si fermi',
    'a house drawn where the Artist said nothing should be': 'una casa dove il Disegnatore voleva lasciare il vuoto',
    'a moon with an erased second face': 'una luna con un secondo volto cancellato',
    'a ronin who wanted to be a kite': 'un ronin che voleva essere un aquilone',
    'a second draft under the proof line': 'una seconda bozza sotto la linea di prova',
    'a tiny umbrella hiding beneath the old stain': 'un ombrellino nascosto sotto la vecchia macchia',
    'a train ticket to a town never drawn': 'un biglietto per una città mai disegnata',
    'a victory pose the Artist immediately disliked': 'una posa vittoriosa subito sgradita al Disegnatore',
    'a wing drawn above the last cloud': "un'ala disegnata sopra l'ultima nuvola",
    'an ID card with a badly forged face': 'un documento con un volto mal falsificato',
    'an earlier little figure, erased before it could stand': 'un primo omino, cancellato prima di potersi alzare',
    'gravity still works. suspicious.': 'la gravità funziona ancora. sospetto.',
    'homework that fought back': 'compiti che hanno reagito',
    'one roof fold hangs loose': 'una piega del tetto è allentata',
    'pressure on the upper copy leaves a face': 'premere la copia superiore lascia un volto',
    'the Artist once tried to draw something dangerous': 'il Disegnatore provò a disegnare qualcosa di pericoloso',
    'the little roof continues above the red rule': 'il piccolo tetto continua sopra la linea rossa',
    'the loose seam has a dashed arrow': 'la cucitura libera ha una freccia tratteggiata',
    'the next page is classified': 'la prossima pagina è riservata',
    'the old answer is under those crossouts': 'la vecchia risposta è sotto le cancellature',
    'the original signature beneath two carbon copies': 'la firma originale sotto due copie carbone',
    'the rails continue in the margin': 'i binari continuano nel margine',
    'the rejected draft is under the proof line': 'la bozza scartata è sotto la linea di prova',
    'the timetable has a missing corner': "manca un angolo all'orario",
    'the wrong outline rings when ink touches it': "il contorno sbagliato suona al tocco dell'inchiostro",
    'turn it over — the dust is getting closer': 'volta pagina — la polvere si avvicina',
    'turn it over — the next page is classified': 'volta pagina — la prossima pagina è riservata',
    'turn it over — the stars are badly drawn': 'volta pagina — le stelle sono disegnate male',
    'why did I draw the moon twice?': 'perché ho disegnato la luna due volte?',
    'zero gravity*  (*mostly)': 'gravità zero* (*quasi)',
    'make the current agree': 'allinea la corrente',
    'CARBON SCAN': 'SCANSIONE CARBONE',
    'ERASER / JUMP': 'GOMMA / SALTA',
    'SCAN / WAIT': 'SCANSIONE / ASPETTA',
    'a way up': 'una via per salire',
    'a weapon': "un'arma",
    'better.': 'meglio.',
    'draw me...': 'disegnami...',
    'CARBON': 'CARBONE',
    'COPY  <---': 'COPIA <---',
    'CREASE HOLDS': 'PIEGA STABILE',
    'MIRROR COPY HOLDS': 'COPIA SPECULARE STABILE',
    'RUB EVERY MARK': 'STROFINA OGNI SEGNO',
    'one fold tugs the crease on its left': 'una piega tira anche quella alla sua sinistra',
    'guard below / defeat the rejected drawing': 'guardia in basso / sconfiggi il disegno scartato',
    'Q / wheel': 'Q / rotellina',
    'returning · line up the fold': 'in ritorno · allineati alla piega',
    'rub out incoming shots': 'cancella i colpi in arrivo',
    'third cut · exposed wound': 'terzo taglio · ferita esposta',
    'two cuts held · finish': 'due tagli pronti · finisci',
    'winding up': 'in caricamento',
    'reload': 'ricarica',
    'DASH →': 'SCATTA →',
    'BETWEEN': 'TRA I COLPI',
    'FWOOSH': 'FUUU',
    'PINNED!': 'INCHIODATO!',
    'READING': 'LEGGE',
    'RELOADING': 'RICARICA',
    'RESETTING': 'RECUPERA',
    'HOT': 'ROVENTE',
    'NO.': 'NO.',
    'ARC': 'ARCO',
    'SNAP': 'SCATTO',
    'BACK': 'DIETRO',
    'ERASE': 'CANCELLA',
    'DRAW': 'ESTRAI',
    'BEEP': 'BIP',
    'HEH': 'EH',
    'ROLL': 'ROTOLA',
    'LOCK': 'BLOCCA',
    'RAM': 'CARICA',
    'THREE': 'TRE',
    'MOVE': 'SPOSTATI',
    'JUMP': 'SALTA',
    'TRAIL': 'SCIA',
    'artist hesitation': 'esitazione del Disegnatore',
    'E  redraw circuit node': 'E / ridisegna il nodo del circuito',
    'the ink circuit hums open': "il circuito d'inchiostro si apre ronzando",
    'E  turn the paper dial': 'E / gira il quadrante di carta',
    'the old symbols remember': 'i vecchi simboli ricordano',
    "the mistake's outline has come loose": "il contorno dell'errore si è allentato",
    "The wet ink moves. The copies don't.": "L'inchiostro bagnato si muove. Le copie no.",
    'THE ARTIST: New landing. Try the upper angle.': "IL DISEGNATORE: Nuovo appoggio. Prova dall'alto.",
    'THE ARTIST: I kept your working notes.': 'IL DISEGNATORE: Ho conservato i tuoi appunti.',
    'attempt two — still completely unfair': 'secondo tentativo — ancora del tutto ingiusto',
    'THIRD ATTEMPT — ONE CLEAN SWING': 'TERZO TENTATIVO — UN COLPO PULITO',
    'carbon reads backwards — copy right to left': 'il carbone si legge al contrario — copia da destra a sinistra',
    'all pressure marks found — turn the black sheet': 'tutti i segni trovati — volta il foglio nero',
    'the carbon smudged — begin again from the right': 'il carbone si è sbavato — ricomincia da destra',
    'mountain': 'monte',
    'valley': 'valle',
    'NEW CONSTELLATION': 'NUOVA COSTELLAZIONE',
    'MARGIN MAUL': 'MARTELLO DEL MARGINE',
    'FOLDED SHURIKEN': 'SHURIKEN PIEGATO',
    'CHALK BOMB': 'BOMBA DI GESSO',
    'CARBON LANCE': 'LANCIA CARBONE',
    'EXCALIBUR': 'EXCALIBUR',
    'THE AGGRO MAN / it counted every attack': "L'UOMO AGGRESSIVO / ha contato ogni attacco",
    'BRAVEMAN / the margins followed you': "L'UOMO CORAGGIOSO / i margini ti seguivano",
    'MIRROR / it remembered the clean inputs': 'SPECCHIO / ricordava le mosse precise',
    'MIXED REVISION / it could not classify you': 'REVISIONE MISTA / non riusciva a classificarti',
    'AGGRO': 'AGGRESSIVO',
    'MIXED': 'MISTO',
    'DASH RIGHT / through the dashed seam': 'SCATTA A DESTRA / attraverso la cucitura tratteggiata',
    'JUMP ABOVE / the poster tears at the dashed seam': 'SALTA IN ALTO / il manifesto si strappa lungo la cucitura',
    'NO SIGNAL / take the star from the lower pad': 'NESSUN SEGNALE / prendi la stella dalla base inferiore',
    'STAR CHARGED / climb the satellite steps': 'STELLA CARICA / sali i gradini del satellite',
    'E  turn over the carbon sheet': 'E / volta il foglio carbone',
    'the shared crease folds the ink gate away': "la piega condivisa apre il cancello d'inchiostro",
    'the mirrored carbon line copies the gate away': 'la linea carbone speculare apre il cancello copiandolo',
    'One more line. This one fights differently.': "Un'altra linea. Questa combatte diversamente.",
    'You earned the drawing. E to keep it and answer me.': 'Hai meritato il disegno. E per conservarlo e rispondermi.',
    'KING?': 'RE?',
    'TURN': 'VOLTA',
    'wrong century': 'secolo sbagliato',
    'needs a hat': 'serve un cappello',
    'close enough to space': 'quasi come lo spazio',
    'dust updraft': 'corrente di polvere',
    'leaking star ink': 'inchiostro stellare che cola',
    'E  enter tear': 'E / entra nello strappo',
    'combat ink soaking through': 'inchiostro dello scontro che filtra',
    'dark coffee sediment': 'fondo di caffè scuro',
    'thin coffee ring': 'sottile anello di caffè',
    'wet ink': 'inchiostro bagnato',
    'PULL': 'TIRA',
    'DIVE': 'PICCHIATA',
    'INK v': 'INCHIOSTRO v',
    'SCAN': 'SCANSIONA',
    'STAMP': 'TIMBRO',
    'E  take INK KATANA': "E / prendi KATANA D'INCHIOSTRO",
    'NEW DRAWING — INK KATANA': "NUOVO DISEGNO — KATANA D'INCHIOSTRO",
    'E  take PENCIL BLADE': 'E / prendi LAMA DI MATITA',
    'NEW DRAWING — PENCIL BLADE': 'NUOVO DISEGNO — LAMA DI MATITA',
    'E  take RETURNING FOLD': 'E / prendi PIEGA DI RITORNO',
    'NEW DRAWING — RETURNING FOLD': 'NUOVO DISEGNO — PIEGA DI RITORNO',
    'E  take OVERSIZED PENCIL': 'E / prendi MATITA GIGANTE',
    'NEW DRAWING — OVERSIZED PENCIL': 'NUOVO DISEGNO — MATITA GIGANTE',
    'E  take CHALK CAPSULE': 'E / prendi CAPSULA DI GESSO',
    'NEW DRAWING — CHALK CAPSULE': 'NUOVO DISEGNO — CAPSULA DI GESSO',
    'E  take METEOR CHALK': 'E / prendi GESSO METEORA',
    'NEW DRAWING — METEOR CHALK': 'NUOVO DISEGNO — GESSO METEORA',
    'E  take CARBON RIFLE': 'E / prendi FUCILE CARBONE',
    'NEW DRAWING — CARBON RIFLE': 'NUOVO DISEGNO — FUCILE CARBONE',
    'E  take INK PISTOL': "E / prendi PISTOLA D'INCHIOSTRO",
    'NEW DRAWING — INK PISTOL': "NUOVO DISEGNO — PISTOLA D'INCHIOSTRO",
    'E  take SIX-SHOOTER': 'E / prendi SEI COLPI',
    'NEW DRAWING — SIX-SHOOTER': 'NUOVO DISEGNO — SEI COLPI',
    'E  take SUPPRESSED PISTOL': 'E / prendi PISTOLA SILENZIATA',
    'NEW DRAWING — SUPPRESSED PISTOL': 'NUOVO DISEGNO — PISTOLA SILENZIATA',
    'E  take MARKER SHOTGUN': 'E / prendi FUCILE A PENNARELLO',
    'NEW DRAWING — MARKER SHOTGUN': 'NUOVO DISEGNO — FUCILE A PENNARELLO',
    'E  take DOUBLE BARREL': 'E / prendi DOPPIETTA',
    'NEW DRAWING — DOUBLE BARREL': 'NUOVO DISEGNO — DOPPIETTA',
    'E  take BREACH SHOTGUN': 'E / prendi FUCILE DA BRECCIA',
    'NEW DRAWING — BREACH SHOTGUN': 'NUOVO DISEGNO — FUCILE DA BRECCIA',
    'E  take ERASER CANNON': 'E / prendi CANNONE GOMMA',
    'NEW DRAWING — ERASER CANNON': 'NUOVO DISEGNO — CANNONE GOMMA',
    'E  take NULL CANNON': 'E / prendi CANNONE VUOTO',
    'NEW DRAWING — NULL CANNON': 'NUOVO DISEGNO — CANNONE VUOTO',
    'E  take RUBBER BAND': 'E / prendi ELASTICO',
    'NEW DRAWING — RUBBER BAND': 'NUOVO DISEGNO — ELASTICO',
    'E  take ORBIT PULSE': 'E / prendi IMPULSO ORBITALE',
    'NEW DRAWING — ORBIT PULSE': 'NUOVO DISEGNO — IMPULSO ORBITALE',
    'E  take BOWIE KNIFE': 'E / prendi COLTELLO BOWIE',
    'NEW DRAWING — BOWIE KNIFE': 'NUOVO DISEGNO — COLTELLO BOWIE',
    'E  take FIELD KNIFE': 'E / prendi COLTELLO DA CAMPO',
    'NEW DRAWING — FIELD KNIFE': 'NUOVO DISEGNO — COLTELLO DA CAMPO',
    'E  take ION EDGE': 'E / prendi LAMA IONICA',
    'NEW DRAWING — ION EDGE': 'NUOVO DISEGNO — LAMA IONICA',
    'E  take REDRAW PENCIL': 'E / prendi MATITA DI REVISIONE',
    'NEW DRAWING — REDRAW PENCIL': 'NUOVO DISEGNO — MATITA DI REVISIONE',
    'E  take THE VERY DRAMATIC SWORD': 'E / prendi LA SPADA MOLTO DRAMMATICA',
    'NEW DRAWING — THE VERY DRAMATIC SWORD': 'NUOVO DISEGNO — LA SPADA MOLTO DRAMMATICA',
    'E  take ORBITAL RUBBER BAND': 'E / prendi ELASTICO ORBITALE',
    'NEW DRAWING — ORBITAL RUBBER BAND': 'NUOVO DISEGNO — ELASTICO ORBITALE',
}
