"""Turkish text verified against the actual five-page runtime and HUD."""

TR_REVISION = {
    'CLOUD KITE': 'BULUT UÇURTMASI',
    'JUMP THE GUST. LEAVE THE TAIL MARK.': 'RÜZGÂRDAN ZIPLA. KUYRUK İZİNDEN ÇIK.',
    'CLEAR THE ROOM': 'ODAYI TEMİZLE',
    'You crossed the last drawings easily. I am adding one more opponent.': 'Son çizimleri kolayca geçtin. Bir rakip daha ekliyorum.',
    'That drawing caught you twice. I will watch your ink more closely.': 'Bu çizim seni iki kez yakaladı. Mürekkebini daha dikkatli izleyeceğim.',
    'I saw you struggle with this drawing. Here is a stronger tool. Q tries it; your weapon stays.': 'Bu çizimde zorlandığını gördüm. Daha güçlü bir araç çizdim. Q ile dene; elindeki silah duruyor.',
    'I watched your last fight. Here is another range to try. Q changes tools; your weapon stays.': 'Son dövüşünü izledim. Farklı mesafede kullanabileceğin bir araç çizdim. Q ile dene; elindeki silah duruyor.',
    'Your ink is almost gone. I will redraw one heart. Keep reading the red lines.': 'Mürekkebin neredeyse bitti. Bir kalbi yeniden çizeceğim. Kırmızı uyarıları izlemeye devam et.',
    'Drawn for this page. Q swaps back.': 'Bu sayfa için çizildi. Q ile geri değiştir.',
    'E / DRAW': 'E / ÇİZ',
    'E  ASK THE ARTIST TO REDRAW ONE HEART (once this room)': 'E  RESSAMDAN BİR KALP ÇİZMESİNİ İSTE (bu odada bir kez)',
    'A kite wakes in the clouds. Its wind stays low; the tail mark does not move.': 'Bulutlarda bir uçurtma uyanır. Rüzgârı alçaktan geçer; kuyruk izi yerinde kalır.',
    'E / lift the loose paper corner': 'E / gevşek kağıt köşesini kaldır',
    'lift the loose corner': 'gevşek köşeyi kaldır',
    'ABOVE THE CLOUDS': 'BULUTLARIN ÜSTÜNDE',
    'THE FOLDED REFUGE': 'KATLANMIŞ SIĞINAK',
    'THE MISSING ORIGINAL': 'KAYIP ASIL',
    '01 / THE FIRST CUT': '01 / İLK KESİŞ',
    '02 / PAPER AMBUSH': '02 / KAĞIT PUSUSU',
    '03 / LANTERN PROCESSION': '03 / FENER ALAYI',
    '01 / HIGH NOON': '01 / ÖĞLE DÜELLOSU',
    '02 / THREE NEEDLES': '02 / ÜÇ İĞNE',
    '01 / AIRLOCK PATROL': '01 / HAVA KİLİDİ DEVRİYESİ',
    '02 / DEBRIS FIELD': '02 / ENKAZ ALANI',
    '04 / CORRECTION BAY': '04 / DÜZELTME ODASI',
    'Let the blade pass. Cut during recovery.': 'Kılıcın geçmesini bekle. Toparlanırken vur.',
    'The drone drops after firing. Go behind the ruler.': 'Dron atıştan sonra alçalır. Cetvelin arkasına geç.',
    'Clear the low threat before chasing the lantern.': 'Feneri kovalamadan önce alçaktaki düşmanı yen.',
    'Keep space. Jump the rolling tumbleweed.': 'Mesafeni koru. Yuvarlanan çalının üstünden zıpla.',
    'Read the cactus fan; move between volleys.': 'Kaktüsün saçılımını izle; yaylımlar arasında hareket et.',
    'The bot braces before ramming. Let it commit.': 'Robot çarpmadan önce hazırlanır. Hamlesini bekle.',
    'Jump the hound; close on the turret during reload.': 'Köpeğin üstünden zıpla; taret dolarken yaklaş.',
    'Watch the erased floor. Save a landing line.': 'Silinen zemini izle. İneceğin bir çizgi bırak.',
    'THE MOON RONIN': 'AY RONİNİ',
    'WANTED: FAILED ALIVE': 'ARANIYOR: BAŞARISIZ VE DİRİ',
    'THE MIDNIGHT EXPRESS': 'GECE YARISI EKSPRESİ',
    'ORBITAL SENTINEL': 'YÖRÜNGE NÖBETÇİSİ',
    'THE LOST EXPEDITION': 'KAYIP SEFER',
    'JUMP THE ARC — STRIKE THE STUCK BLADE': 'YAYDAN ZIPLA — SAPLANAN BIÇAĞI VUR',
    'THREE ATTEMPTS — THE ARTIST CHEATS LAST': 'ÜÇ DENEME — SONUNDA RESSAM HİLE YAPAR',
    'THE FOLDED SHRINE': 'KATLANMIŞ TAPINAK',
    'THE WATER TOWER': 'SU KULESİ',
    'THE ORRERY': 'GÖKYÜZÜ MODELİ',
    'AIRLOCK? / draw one later': 'HAVA KİLİDİ? / sonra bir tane çiz',
    'BAMBOO? / definitely bamboo': 'BAMBU? / kesinlikle bambu',
    'CLASSIFIED / turn over': 'GİZLİ / sayfayı çevir',
    'DASH INTO A SHOT / return it at the last moment': 'ATIŞA ATIL / son anda geri yansıt',
    'DUST DEVIL  ^': 'TOZ HORTUMU  ^',
    'ERASER BELOW: take the upper ink': 'AŞAĞIDA SİLGİ VAR: üst çizgiden git',
    'LAST TRAIN / no timetable': 'SON TREN / tarife yok',
    'LEAKING STAR INK': 'SIZAN YILDIZ MÜREKKEBİ',
    'MOON GATE': 'AY KAPISI',
    'NEW PAGE. NEW HAT.': 'YENİ SAYFA. YENİ ŞAPKA.',
    'ORBITAL WALKWAY / DO NOT ERASE': 'YÖRÜNGE GEÇİDİ / SİLME',
    'OVERSIZED EXPEDITION SUIT': 'FAZLA BÜYÜK SEFER KIYAFETİ',
    'RED LINE: wait, jump, or dash through': 'KIRMIZI ÇİZGİ: bekle, zıpla ya da atılmayla geç',
    'SALOON SPILL / still slippery': 'MEYHANE DÖKÜNTÜSÜ / hâlâ kaygan',
    'SIX-SHOOTER ->': 'ALTIPATLAR ->',
    'WANTED: whoever drew the goblin': 'ARANIYOR: goblini çizen kişi',
    'WHY DID I DRAW IT THAT BIG?': 'BUNU NİYE BU KADAR BÜYÜK ÇİZDİM?',
    'You may turn the page.': 'Sayfayı çevirebilirsin.',
    'a creature assembled from everything the eraser missed': 'silginin kaçırdığı parçalardan yapılmış bir yaratık',
    'a fierce monster with an apologetic smile': 'mahcup gülümseyen vahşi bir canavar',
    'a folded shield rejected for being too stubborn': 'fazla inatçı olduğu için atılmış katlı bir kalkan',
    'a handle? face the stain and let it settle': 'bir sap mı? lekeye dön ve durulmasını bekle',
    'a house drawn where the Artist said nothing should be': 'Ressamın boş bırakmak istediği yere çizilmiş bir ev',
    'a moon with an erased second face': 'ikinci yüzü silinmiş bir ay',
    'a ronin who wanted to be a kite': 'uçurtma olmak isteyen bir ronin',
    'a second draft under the proof line': 'prova çizgisinin altında ikinci bir taslak',
    'a tiny umbrella hiding beneath the old stain': 'eski lekenin altında saklanan küçük bir şemsiye',
    'a train ticket to a town never drawn': 'hiç çizilmemiş bir kasabaya tren bileti',
    'a victory pose the Artist immediately disliked': 'Ressamın hemen beğenmediği bir zafer pozu',
    'a wing drawn above the last cloud': 'son bulutun üstüne çizilmiş bir kanat',
    'an ID card with a badly forged face': 'yüzü kötü taklit edilmiş bir kimlik',
    'an earlier little figure, erased before it could stand': 'ayağa kalkamadan silinmiş ilk küçük figür',
    'gravity still works. suspicious.': 'yerçekimi hâlâ çalışıyor. şüpheli.',
    'homework that fought back': 'karşılık veren bir ödev',
    'one roof fold hangs loose': 'çatının bir katı gevşek duruyor',
    'pressure on the upper copy leaves a face': 'üst kopyaya bastırınca bir yüz kalır',
    'the Artist once tried to draw something dangerous': 'Ressam bir zamanlar tehlikeli bir şey çizmeye çalışmış',
    'the little roof continues above the red rule': 'küçük çatı kırmızı çizginin üstünde devam ediyor',
    'the loose seam has a dashed arrow': 'gevşek dikişte kesik çizgili bir ok var',
    'the next page is classified': 'sonraki sayfa gizli',
    'the old answer is under those crossouts': 'eski cevap şu karalamaların altında',
    'the original signature beneath two carbon copies': 'iki karbon kopyasının altındaki asıl imza',
    'the rails continue in the margin': 'raylar kenarda devam ediyor',
    'the rejected draft is under the proof line': 'atılmış taslak prova çizgisinin altında',
    'the timetable has a missing corner': 'tarifenin bir köşesi eksik',
    'the wrong outline rings when ink touches it': 'yanlış dış çizgi mürekkep değince çınlar',
    'turn it over — the dust is getting closer': 'sayfayı çevir — toz yaklaşıyor',
    'turn it over — the next page is classified': 'sayfayı çevir — sonraki sayfa gizli',
    'turn it over — the stars are badly drawn': 'sayfayı çevir — yıldızlar kötü çizilmiş',
    'why did I draw the moon twice?': 'ayı neden iki kez çizdim?',
    'zero gravity*  (*mostly)': 'sıfır yerçekimi*  (*çoğunlukla)',
    'make the current agree': 'akımı eşitle',
    'CARBON SCAN': 'KARBON TARAMASI',
    'ERASER / JUMP': 'SİLGİ / ZIPLA',
    'SCAN / WAIT': 'TARAMA / BEKLE',
    'a way up': 'yukarıya bir yol',
    'a weapon': 'bir silah',
    'better.': 'daha iyi.',
    'draw me...': 'bana çiz...',
    'CARBON': 'KARBON',
    'COPY  <---': 'KOPYALA  <---',
    'CREASE HOLDS': 'KATLAMA TAMAM',
    'MIRROR COPY HOLDS': 'AYNA KOPYASI TAMAM',
    'RUB EVERY MARK': 'HER İZİ OV',
    'one fold tugs the crease on its left': 'bir katlama solundaki kıvrımı da çeker',
    'guard below / defeat the rejected drawing': 'aşağıda muhafız var / atılmış çizimi yen',
    'Q / wheel': 'Q / tekerlek',
    'returning · line up the fold': 'geri dönüyor · katlamayla hizalan',
    'rub out incoming shots': 'gelen atışları sil',
    'third cut · exposed wound': 'üçüncü kesiş · açık yara',
    'two cuts held · finish': 'iki kesiş hazır · bitir',
    'winding up': 'hazırlanıyor',
    'reload': 'doldur',
    'DASH →': 'ATIL →',
    'dash': 'atılma',
    'Dash / return': 'Atılma / geri yansıtma',
    'Air +35%; dash -0.08s; edge grace +0.04s.': 'Hava kontrolü +%35; atılma -0,08 sn; kenar payı +0,04 sn.',
    'BETWEEN': 'ARADAN GEÇ',
    'FWOOSH': 'VUUŞ',
    'PINNED!': 'SAPLANDI!',
    'READING': 'OKUYOR',
    'RELOADING': 'DOLDURUYOR',
    'RESETTING': 'TOPARLANIYOR',
    'HOT': 'SICAK',
    'NO.': 'HAYIR.',
    'ARC': 'YAY',
    'SNAP': 'KAPANIYOR',
    'BACK': 'ARKA',
    'ERASE': 'SİL',
    'DRAW': 'ÇEK',
    'BEEP': 'BİP',
    'HEH': 'HEH',
    'ROLL': 'YUVARLAN',
    'LOCK': 'SABİTLE',
    'RAM': 'ÇARPMA',
    'THREE': 'ÜÇ',
    'MOVE': 'KAÇ',
    'JUMP': 'ZIPLA',
    'TRAIL': 'İZ',
    'artist hesitation': 'ressam duraksaması',
    'E  redraw circuit node': 'E  devre düğümünü yeniden çiz',
    'the ink circuit hums open': 'mürekkep devresi açılıyor',
    'E  turn the paper dial': 'E  kağıt kadranı çevir',
    'the old symbols remember': 'eski simgeler hatırlıyor',
    "the mistake's outline has come loose": 'hatalı çizimin dış çizgisi gevşedi',
    "The wet ink moves. The copies don't.": 'Islak mürekkep hareket eder. Kopyalar etmez.',
    'THE ARTIST: A small revision. Next wave in a moment.': 'RESSAM: Küçük bir düzeltme. Sıradaki dalga birazdan.',
    'THE ARTIST: New landing. Try the upper angle.': 'RESSAM: Yeni bir basamak. Üst açıdan dene.',
    'THE ARTIST: I kept your working notes.': 'RESSAM: Çalışma notlarını sakladım.',
    'attempt two — still completely unfair': 'ikinci deneme — hâlâ tamamen haksız',
    'THIRD ATTEMPT — ONE CLEAN SWING': 'ÜÇÜNCÜ DENEME — TEK TEMİZ VURUŞ',
    'carbon reads backwards — copy right to left': 'karbon tersten okunur — sağdan sola kopyala',
    'all pressure marks found — turn the black sheet': 'tüm baskı izleri bulundu — siyah sayfayı çevir',
    'the carbon smudged — begin again from the right': 'karbon bulaştı — sağdan tekrar başla',
    'mountain': 'tepe',
    'valley': 'vadi',
    'NEW CONSTELLATION': 'YENİ TAKIMYILDIZI',
    'MARGIN MAUL': 'DEV KALEM',
    'FOLDED SHURIKEN': 'GERİ DÖNEN KATLAMA',
    'CHALK BOMB': 'TEBEŞİR KAPSÜLÜ',
    'CARBON LANCE': 'KARBON TÜFEĞİ',
    'EXCALIBUR': 'KRAL ARTHUR’UN KILICI',
    'THE AGGRO MAN / it counted every attack': 'SALDIRGAN ADAM / her saldırını saydı',
    'BRAVEMAN / the margins followed you': 'CESUR ADAM / kenarlar seni izledi',
    'MIRROR / it remembered the clean inputs': 'AYNA / temiz hamlelerini hatırladı',
    'MIXED REVISION / it could not classify you': 'KARMA DÜZELTME / seni sınıflandıramadı',
    'AGGRO': 'SALDIRGAN',
    'MIXED': 'KARMA',
    'DASH RIGHT / through the dashed seam': 'SAĞA ATIL / kesik çizgili dikişten geç',
    'JUMP ABOVE / the poster tears at the dashed seam': 'YUKARI ZIPLA / afiş kesik çizgiden yırtılır',
    'NO SIGNAL / take the star from the lower pad': 'SİNYAL YOK / alttaki yuvadan yıldızı al',
    'STAR CHARGED / climb the satellite steps': 'YILDIZ DOLDU / uydu basamaklarına tırman',
    'E  turn over the carbon sheet': 'E  karbon sayfasını çevir',
    'the shared crease folds the ink gate away': 'ortak kıvrım mürekkep kapısını katlayıp açtı',
    'the mirrored carbon line copies the gate away': 'aynalı karbon çizgisi kapıyı kopyalayıp açtı',
    'One more line. This one fights differently.': 'Bir çizgi daha. Bu farklı dövüşür.',
    'You earned the drawing. E to keep it and answer me.': 'Çizimi hak ettin. E ile sakla ve bana cevap ver.',
    'KING?': 'KRAL?',
    'TURN': 'ÇEVİR',
    'SALOON': 'MEYHANE',
    'wrong century': 'yanlış yüzyıl',
    'needs a hat': 'bir şapka gerek',
    'close enough to space': 'uzaya yeterince benziyor',
    'dust updraft': 'yükselen toz',
    'leaking star ink': 'sızan yıldız mürekkebi',
    'E  enter tear': 'E  yırtıktan gir',
    'combat ink soaking through': 'sayfaya işleyen dövüş mürekkebi',
    'dark coffee sediment': 'koyu kahve tortusu',
    'thin coffee ring': 'ince kahve halkası',
    'wet ink': 'ıslak mürekkep',
    'PULL': 'ÇEK',
    'DIVE': 'DAL',
    'INK v': 'MÜREKKEP v',
    'SCAN': 'TARA',
    'STAMP': 'DAMGA',
}


def _translated(text):
    # Import at call time: localization loads this dictionary during startup.
    from localization import translate
    return translate(text)


PATTERNS_REVISION = (
    (r'^TOOL ADDED — (.+) / Q to try it$', lambda m: 'ARAÇ EKLENDİ — '+_translated(m[1])+' / Q ile dene'),
    (r'^wave (\d+)/(\d+)$', r'dalga \1/\2'),
    (r'^Dashes: (.+)$', r'Atılma: \1'),
    (r'^Dash recovery is (.+) seconds shorter\.$', r'Atılma dolum süresi \1 saniye kısalır.'),
    (r'^COPY: (.+)$', lambda m: 'KOPYA: '+_translated(m[1])),
    (r'^ORBIT (\d+) / (\d+) — NEW CONSTELLATION$', r'YÖRÜNGE \1 / \2 — YENİ TAKIMYILDIZI'),
    (r'^clue: (.+)$', r'ipucu: \1'),
    (r'^crease clue:  (.+)$', r'katlama ipucu:  \1'),
    (r'^STAR  /  (.+)s$', r'YILDIZ  /  \1 sn'),
    (r'^E  fold tab (\d+) \((mountain|valley)\)$',
     lambda m: 'E  '+m[1]+'. şeridi katla ('+_translated(m[2])+')'),
    (r'^E  rub impression (\d+)$', r'E  \1. baskı izini ov'),
    (r'^impression (\d+) already revealed$', r'\1. baskı izi zaten açıldı'),
    (r'^E  transfer impression (\d+) \(right to left\)$', r'E  \1. baskı izini aktar (sağdan sola)'),
    (r'^E  take (.+)$', lambda m: 'E  '+_translated(m[1])+' al'),
    (r'^NEW DRAWING — (.+)$', lambda m: 'YENİ ÇİZİM — '+_translated(m[1])),
    (r'^FIELD NOTES / (.+)$', r'SAHA NOTLARI / \1'),
    (r'^(.+?) ->$', lambda m: _translated(m[1])+' ->'),
)
